"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Brand from '../../components/Brand';
import {api,setApiUser} from '../../lib/api';
export default function Pair(){
 const [credentials,setCredentials]=useState(null),[user,setUser]=useState(null),[details,setDetails]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState('');const popup=useRef(null),pairRef=useRef(null);
 const check=useCallback(async()=>{try{const data=await api('/api/session');setUser(data.user);setApiUser(data.user);return data.user;}catch(e){setError(e.message);return null;}},[]);
 useEffect(()=>{const values=new URLSearchParams(window.location.hash.slice(1)),id=values.get('id'),token=values.get('token');if(id&&token)pairRef.current={id,token};if(pairRef.current){setCredentials(pairRef.current);window.history.replaceState(null,'',window.location.pathname);}else setError('Abra esta página lendo o QR Code exibido no computador.');check();const resume=()=>{if(!document.hidden)check();},message=e=>{if(e.origin===window.location.origin&&e.source===popup.current&&e.data?.type==='lifeos-login-complete')check();};window.addEventListener('focus',resume);window.addEventListener('message',message);document.addEventListener('visibilitychange',resume);return()=>{window.removeEventListener('focus',resume);window.removeEventListener('message',message);document.removeEventListener('visibilitychange',resume);};},[check]);
 useEffect(()=>{if(!user||user.temporary||!credentials||done)return;let cancelled=false;api('/api/auth/qr',{method:'POST',body:JSON.stringify({action:'details',...credentials})}).then(data=>{if(!cancelled){setDetails(data);setError('');}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[user?.id,credentials,done]);
 useEffect(()=>{if(user||!credentials)return;let timer,stopped=false;const poll=async()=>{if(!document.hidden)await check();if(!stopped)timer=setTimeout(poll,2000);};timer=setTimeout(poll,2000);return()=>{stopped=true;clearTimeout(timer);};},[user,credentials,check]);
 async function decide(approve){setBusy(true);setError('');try{await api('/api/auth/qr',{method:'POST',body:JSON.stringify({action:approve?'approve':'deny',...credentials})});setDone(approve?'Computador autorizado. Você pode voltar ao LifeOS.':'Acesso recusado.');setDetails(null);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="login-shell"><div className="login-card qr-pair"><h1><Brand/></h1><h2>Autorizar computador</h2>{done?<p role="status">{done}</p>:user?.temporary?<p className="date-error">Use uma sessão iniciada pelo Google para autorizar outro computador.</p>:!user?<><p className="muted">O navegador que abriu este link precisa estar conectado à sua conta Google autorizada no LifeOS. Seu Google continua apenas no celular.</p><button className="primary" onClick={()=>{popup.current=window.open('/api/auth/google?popup=1','lifeos-google-login');if(!popup.current)setError('Permita a janela de login e tente novamente.');}}>Entrar com Google no celular</button><button className="ghost" onClick={check}>Já entrei — verificar</button></>:details?<><p>Conectado como <strong>{user.name||user.email}</strong></p><p className="muted">Autorize somente o computador que você está usando. Confira se o código abaixo é igual ao da tela dele.</p><strong className="qr-number">{details.code.slice(0,3)} {details.code.slice(3)}</strong><p className="small muted">{details.origin}<br/>{details.device}</p><p className="small muted">Acesso por até 30 minutos, com encerramento após 10 minutos sem interação. Você poderá desconectar pelo menu da sua conta.</p><div className="qr-actions"><button className="primary" disabled={busy} onClick={()=>decide(true)}>Autorizar este computador</button><button className="ghost" disabled={busy} onClick={()=>decide(false)}>Recusar</button></div></>:<p>Verificando pedido…</p>}{error&&<p className="date-error" role="alert">{error}</p>}<a className="ghost" href="/">Voltar ao LifeOS</a></div></main>;
}
