import {lookup} from 'node:dns/promises';
import {isIP} from 'node:net';
import {randomUUID,createHash} from 'node:crypto';
import {AppError,legacyEmail} from './auth';
import {redis,withWriteLock} from './coordination';
import {MAINTENANCE_KEY,ROUTING_KEY,maintenance} from './maintenance';
import {DB,LABELS,schema,notion as notionRequest,queryAll,plain,uploadFile} from './notion';
const CREATED='LifeOS Criado originalmente';
const INDEX='lifeos:backups:v1',ACTIVE='lifeos:backup-active:v1',JOB=id=>'lifeos:backup-job:'+id,TTL=900,MARKER='LifeOS Backup origem';
let lastNotionCall=0;
async function notion(path,options){const wait=350-(Date.now()-lastNotionCall);if(wait>0)await new Promise(r=>setTimeout(r,wait));lastNotionCall=Date.now();return notionRequest(path,options);}
const text=value=>[{type:'text',text:{content:String(value)}}];
export function backupAdmin(user){if(!user||user.email!==legacyEmail())throw new AppError('Backup disponível apenas para o usuário principal.',403);}
const root=()=>{const id=process.env.NOTION_BACKUP_PAGE_ID;if(!/^[a-f\d-]{32,36}$/i.test(id||''))throw new AppError('Configure NOTION_BACKUP_PAGE_ID com a página de destino autorizada no Notion.',503);return id;};
const getJSON=async key=>JSON.parse(await redis(['GET',key])||'null');
async function save(job){job.updatedAt=new Date().toISOString();await redis(['SET',JOB(job.id),JSON.stringify(job),'EX',30*86400]);}
async function pulse(job){const lock=await maintenance();if(lock?.id!==job.id)throw new AppError('A operação perdeu o bloqueio por inatividade. Cancele e crie uma nova cópia; os bancos ativos não foram substituídos.',409);await redis(['SET',MAINTENANCE_KEY,JSON.stringify({id:job.id,mode:job.mode,at:job.startedAt}),'EX',TTL]);}
async function release(job){await redis(['EVAL',"local x=redis.call('get',KEYS[1]);if x and cjson.decode(x).id==ARGV[1] then return redis.call('del',KEYS[1]) else return 0 end",1,MAINTENANCE_KEY,job.id]);await redis(['DEL',ACTIVE]);}
const PHASES={folder:'Criando pasta',definitions:'Criando bancos',relationSchemas:'Preparando relações',enumerate:'Conferindo registros',copy:'Copiando conteúdo e anexos',relations:'Reconstruindo relações',verifyRecords:'Verificando conteúdo e arquivos',verify:'Conferindo integridade',finish:'Concluindo',completed:'Concluído'};
const publicJob=j=>j?{id:j.id,mode:j.mode,phase:j.phase,startedAt:j.startedAt,updatedAt:j.updatedAt,done:j.done||0,total:j.total||0,message:j.message,error:j.error||'',status:j.status}:null;
export async function backupStatus(user){const lock=await maintenance();if(user.email!==legacyEmail())return {maintenance:!!lock};const active=await getJSON(ACTIVE),job=active?await getJSON(JOB(active)):null;return {configured:!!process.env.NOTION_BACKUP_PAGE_ID,maintenance:!!lock,job:publicJob(job),backups:(await getJSON(INDEX)||[]).map(({banks,activity,...item})=>item)};}
function groupList(banks){return Object.entries(banks).map(([kind,b])=>({kind,databaseId:b.databaseId,sourceId:b.sourceId}));}
async function prepareGroup(ref){const s=await notion(`/data_sources/${ref.sourceId}`);return {...ref,properties:s.properties,rows:[],target:null};}
export async function startBackup(user,mode='backup',backupId){backupAdmin(user);root();return withWriteLock(async guard=>{
 if(await getJSON(ACTIVE))throw new AppError('Há uma operação pendente. Retome ou cancele antes de começar outra.',409);
 const entries=await getJSON(INDEX)||[],chosen=mode==='restore'?entries.find(b=>b.id===backupId):null;if(mode==='restore'&&!chosen)throw new AppError('Selecione um backup concluído.',404);
 const routing=await getJSON(ROUTING_KEY)||{},groups=[];
 for(const [kind,[env,fallback]] of Object.entries(DB)){if(routing.banks?.[kind]||process.env[env]||fallback){const source=await schema(kind);groups.push({kind,databaseId:source.databaseId,sourceId:source.id});}}
 if(mode==='restore'&&groups.map(g=>g.kind).sort().join()!==Object.keys(chosen.banks).sort().join())throw new AppError('Este backup não contém o mesmo conjunto de bancos atualmente configurados. Não é seguro ativá-lo automaticamente.',409);
 if(groups.some(g=>g.databaseId.replaceAll('-','')===root().replaceAll('-','')))throw new AppError('O destino deve ser uma página separada dos bancos ativos.');
 const job={id:randomUUID(),mode,startedAt:new Date().toISOString(),phase:'folder',status:'running',groups,group:0,row:0,done:0,total:0,map:{},files:{},chosen,stage:mode==='restore'?'safety':'backup',routingBefore:routing,activity:await getJSON('lifeos:shared:last:v1')||{}};
 await guard();await redis(['SET',MAINTENANCE_KEY,JSON.stringify({id:job.id,mode,at:job.startedAt}),'NX','EX',TTL]);await save(job);await redis(['SET',ACTIVE,JSON.stringify(job.id)]);return publicJob(job);
 });}
function cleanRich(list){return (list||[]).map(p=>p.type==='text'?{type:'text',text:p.text,annotations:p.annotations}:p.type==='mention'?{type:'mention',mention:p.mention,annotations:p.annotations}:p.type==='equation'?{type:'equation',equation:p.equation,annotations:p.annotations}:p);}
export function cloneDefinition(property){const type=property.type;if(type==='relation')return null;if(type==='status')return {select:{options:property.status.options.map(o=>({name:o.name,color:o.color}))}};if(['select','multi_select'].includes(type))return {[type]:{options:property[type].options.map(o=>({name:o.name,color:o.color}))}};if(['title','rich_text','date','checkbox','files','url','email','phone_number','people'].includes(type))return {[type]:{}};if(type==='number')return {number:{format:property.number?.format||'number'}};throw new AppError(`A propriedade “${property.name}” (${type}) não pode ser copiada com segurança nesta versão. Nenhuma cópia incompleta será considerada válida.`,422);}
function trustedAsset(url){let u;try{u=new URL(url);}catch{throw new AppError('Endereço de anexo inválido.');}const h=u.hostname.toLowerCase();if(u.protocol!=='https:'||u.username||u.password||u.port&&u.port!=='443'||!['amazonaws.com','notion.so','notion.com','notion-static.com','notionusercontent.com','prod-files-secure.s3.us-west-2.amazonaws.com'].some(d=>h===d||h.endsWith('.'+d)))throw new AppError('Um anexo externo não está hospedado no Notion. Envie uma cópia ao Notion antes de realizar o backup.',422);return u.href;}
function publicAddress(ip){if(isIP(ip)===4){const n=ip.split('.').map(Number);return !(n[0]===0||n[0]===10||n[0]===127||n[0]>=224||n[0]===169&&n[1]===254||n[0]===172&&n[1]>=16&&n[1]<=31||n[0]===192&&(n[1]===168||n[1]===0)||n[0]===100&&n[1]>=64&&n[1]<=127||n[0]===198&&(n[1]===18||n[1]===19));}if(isIP(ip)===6){const first=parseInt(ip.split(':')[0],16);return first>=0x2000&&first<=0x3fff&&!ip.toLowerCase().startsWith('2001:db8:');}return false;}
async function checkedAsset(url){const safe=trustedAsset(url);const addresses=await lookup(new URL(safe).hostname,{all:true});if(!addresses.length||addresses.some(a=>!publicAddress(a.address)))throw new AppError('O endereço do arquivo aponta para uma rede não permitida.',403);return safe;}
async function copyFile(file,job,key){if(job.files[key])return job.files[key];let url=await checkedAsset(file[file.type]?.url),response;for(let i=0;i<4;i++){response=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(20000),cache:'no-store'});if([301,302,303,307,308].includes(response.status)){url=await checkedAsset(new URL(response.headers.get('location'),url).href);continue;}break;}if(!response?.ok)throw new AppError('Não foi possível baixar um anexo para a cópia. Retome a operação.',502);const limit=20*1024*1024;if(Number(response.headers.get('content-length')||0)>limit)throw new AppError('Esta versão copia arquivos de até 20 MB. O backup não será concluído enquanto houver um arquivo maior.',413);const reader=response.body.getReader(),chunks=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>limit){await reader.cancel();throw new AppError('Arquivo maior que 20 MB.',413);}chunks.push(value);}const bytes=Buffer.concat(chunks.map(b=>Buffer.from(b))),name=file.name||'arquivo';const upload=await uploadFile(new File([bytes],name,{type:response.headers.get('content-type')||'application/octet-stream'}),limit);const result={name,type:'file_upload',file_upload:{id:upload.uploadId},sha256:createHash('sha256').update(bytes).digest('hex'),size};job.files[key]=result;await save(job);return result;}
async function filePayload(file,job,key){const {sha256,size,...payload}=await copyFile(file,job,key);return payload;}
export async function cloneValues(page,job,relations=false){if(!relations&&plain(page.properties['URL da capa']?.rich_text)&&page.properties.Capa?.type==='files'&&!page.properties.Capa.files.length)throw new AppError('Uma capa está somente como link externo. Salve uma cópia da imagem no campo Capa do Notion antes de criar o backup completo.',422);const values={};for(const [name,p] of Object.entries(page.properties)){if(p.has_more)throw new AppError(`A propriedade ${name} excede a resposta paginada. Esta cópia foi interrompida sem modificar o original.`,422);let type=p.type;if(type==='relation'){if(relations){values[name]={relation:(p.relation||[]).map(r=>{const id=job.map[r.id];if(!id)throw new AppError(`A relação ${name} aponta para uma página fora dos bancos copiados.`,422);return {id};})};}continue;}if(relations)continue;let value=p[type];if(type==='status'){type='select';value=value?{name:value.name}:null;}else if(['select','multi_select'].includes(type))value=Array.isArray(value)?value.map(o=>({name:o.name})):value?{name:value.name}:null;else if(['title','rich_text'].includes(type))value=cleanRich(value);else if(type==='files'){const files=[];for(let i=0;i<(value||[]).length;i++)files.push(await filePayload(value[i],job,page.id+':'+name+':'+i));value=files;}else if(type==='people')value=(value||[]).map(u=>({object:'user',id:u.id}));else if(type==='date')value=value?{start:value.start,end:value.end,time_zone:value.time_zone}:null;values[name]={[type]:value};}values[MARKER]={rich_text:text(page.id)};if(!relations)values[CREATED]={date:{start:page.properties[CREATED]?.date?.start||page.created_time||new Date().toISOString()}};return values;}
function signature(p,map=null){if(!p)return null;switch(p.type){case 'title':case 'rich_text':return plain(p[p.type]);case 'select':case 'status':return p[p.type]?.name||null;case 'multi_select':return p.multi_select.map(o=>o.name).sort();case 'people':return p.people.map(o=>o.id).sort();case 'relation':return p.relation.map(o=>map?map[o.id]:o.id).sort();case 'files':return p.files.map(f=>f.name);case 'date':return p.date?{start:p.date.start,end:p.date.end||null}:null;default:return p[p.type];}}
async function verifyValues(original,copied,job){
 for(const [name,p]of Object.entries(original.properties)){if(name===MARKER)continue;const a=signature(p,p.type==='relation'?job.map:null),b=signature(copied.properties[name]);if(JSON.stringify(a)!==JSON.stringify(b))throw new AppError(`A verificação de ${name} falhou. A cópia não foi ativada.`,409);if(p.type==='files'){for(let i=0;i<(p.files||[]).length;i++){const expected=job.files[original.id+':'+name+':'+i];if(!expected)throw new AppError('Anexo sem comprovação de cópia.',409);const file=copied.properties[name].files[i];const response=await fetch(await checkedAsset(file[file.type]?.url),{redirect:'error',signal:AbortSignal.timeout(20000),cache:'no-store'});if(!response.ok||Number(response.headers.get('content-length')||0)>20*1024*1024)throw new AppError('Não foi possível verificar o anexo copiado.',502);const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length!==expected.size||createHash('sha256').update(bytes).digest('hex')!==expected.sha256)throw new AppError('O conteúdo de um anexo copiado difere do original.',409);}}
 }
 await verifyBody(original.id,copied.id,job);
}
async function verifyBody(originalId,copiedId,job){const a=await blocks(originalId),b=await blocks(copiedId);if(a.length!==b.length)throw new AppError('O corpo da página não foi copiado integralmente.',409);for(let i=0;i<a.length;i++){const x=a[i],y=b[i];if(x.type!==y.type)throw new AppError('Blocos divergentes na cópia.',409);const u=x[x.type],v=y[y.type];for(const key of ['rich_text','caption'])if(plain(u[key])!==plain(v[key]))throw new AppError('Texto de bloco divergente na cópia.',409);for(const key of ['checked','language','expression','url','table_width','has_column_header','has_row_header'])if(JSON.stringify(u[key]??null)!==JSON.stringify(v[key]??null))throw new AppError('Configuração de bloco divergente na cópia.',409);if(u.cells&&JSON.stringify(u.cells.map(plain))!==JSON.stringify((v.cells||[]).map(plain)))throw new AppError('Tabela divergente na cópia.',409);if(['image','file','video','audio'].includes(x.type)){const expected=job.files['block:'+x.id];const response=await fetch(await checkedAsset(v[v.type]?.url),{redirect:'error',signal:AbortSignal.timeout(20000)});if(!response.ok)throw new AppError('Não foi possível conferir o arquivo de um bloco.',502);const bytes=Buffer.from(await response.arrayBuffer());if(!expected||bytes.length!==expected.size||createHash('sha256').update(bytes).digest('hex')!==expected.sha256)throw new AppError('Arquivo de bloco divergente na cópia.',409);}if(x.has_children||y.has_children)await verifyBody(x.id,y.id,job);}}
async function blocks(id){let cursor;const all=[];do{const r=await notion(`/blocks/${id}/children?page_size=100${cursor?'&start_cursor='+encodeURIComponent(cursor):''}`);all.push(...r.results);cursor=r.has_more?r.next_cursor:null;}while(cursor);return all;}
const BLOCKS=new Set(['paragraph','heading_1','heading_2','heading_3','bulleted_list_item','numbered_list_item','to_do','toggle','quote','callout','code','divider','image','file','video','audio','bookmark','embed','equation','table','table_row','column_list','column']);
async function bodyCopy(id,job){const output=[];for(const block of await blocks(id)){if(!BLOCKS.has(block.type))throw new AppError(`Conteúdo de página não suportado: ${block.type}. O backup foi interrompido para não omitir conteúdo.`,422);const data={...block[block.type]};if(data.rich_text)data.rich_text=cleanRich(data.rich_text);if(data.caption)data.caption=cleanRich(data.caption);if(['image','file','video','audio'].includes(block.type)){const media=await filePayload({...data,name:data.name||block.type},job,'block:'+block.id);const caption=data.caption;Object.keys(data).forEach(k=>delete data[k]);Object.assign(data,media);delete data.name;if(caption)data.caption=caption;}if(block.has_children)data.children=await bodyCopy(block.id,job);output.push({object:'block',type:block.type,[block.type]:data});}if(output.length>100)throw new AppError('Uma página possui mais de 100 blocos diretos. Esta versão interrompe a cópia para evitar omissões.',422);return output;}
async function ensureFolder(job,guard){const children=await blocks(root());const name=`${job.stage==='restoreCopy'?'Restaurado':'Backup'} ${job.startedAt} · ${job.id}${job.stage==='safety'?' · Antes da restauração':''}`;const existing=children.find(b=>b.type==='child_page'&&b.child_page.title===name);if(existing)job.folderId=existing.id;else{await guard();job.folderId=(await notion('/pages',{method:'POST',body:{parent:{type:'page_id',page_id:root()},properties:{title:{title:text(name)}}}})).id;}job.phase='definitions';job.group=0;}
async function finish(job,guard){const banks=Object.fromEntries(job.groups.map(g=>[g.kind,g.target]));if(job.stage==='restoreCopy'){
 await guard();await redis(['SET',ROUTING_KEY,JSON.stringify({version:randomUUID(),banks,folderId:job.folderId,restoredAt:new Date().toISOString(),previous:job.routingBefore.banks||null})]);await redis(['SET','lifeos:shared:last:v1',JSON.stringify(job.chosen.activity||{})]);job.status='completed';job.phase='completed';job.message='Restauração verificada e ativada. Os bancos anteriores foram preservados.';
 }else{
 const entries=await getJSON(INDEX)||[],entry={id:job.id+(job.stage==='safety'?':safety':''),pageId:job.folderId,at:new Date().toISOString(),name:job.stage==='safety'?'Antes da restauração':'Backup manual',records:job.total,files:Object.keys(job.files).length,banks,activity:job.activity};if(!entries.some(e=>e.id===entry.id)){const manifest={format:'LifeOS backup v1',...entry};const uploaded=await uploadFile(new File([JSON.stringify(manifest,null,2)],'lifeos-backup-manifest.json',{type:'application/json'}));await guard();await notion(`/blocks/${job.folderId}/children`,{method:'PATCH',body:{children:[{object:'block',type:'file',file:{type:'file_upload',file_upload:{id:uploaded.uploadId},caption:text('Manifesto de recuperação LifeOS')}}]}});entries.unshift(entry);await redis(['SET',INDEX,JSON.stringify(entries)]);}
 if(job.mode==='restore'){job.groups=groupList(job.chosen.banks);job.stage='restoreCopy';job.folderId=null;job.phase='folder';job.group=0;job.row=0;job.done=0;job.total=0;job.map={};job.files={};return;}
 job.status='completed';job.phase='completed';job.message='Cópia completa verificada.';
 }
 // Retention never touches active restored banks or the previous active originals.
 const entries=await getJSON(INDEX)||[];try{while(entries.length>3){const old=entries[entries.length-1];await guard();await notion(`/pages/${old.pageId}`,{method:'PATCH',body:{archived:true}});entries.pop();await redis(['SET',INDEX,JSON.stringify(entries)]);}}catch{job.message+=' A cópia mais antiga foi mantida porque o arquivamento não pôde ser concluído.';}
 await save(job);await release(job);
}
export async function backupStep(user,id){backupAdmin(user);const job=await getJSON(JOB(id));if(!job||job.id!==await getJSON(ACTIVE))throw new AppError('Operação não encontrada.',404);return withWriteLock(async guard=>{await pulse(job);job.error='';job.status='running';try{
 if(job.phase==='folder')await ensureFolder(job,guard);
 else if(job.phase==='definitions'){
  if(job.group>=job.groups.length){job.group=0;job.phase='relationSchemas';}
  else{let g=job.groups[job.group];if(!g.properties){g=await prepareGroup(g);job.groups[job.group]=g;}const defs={};for(const [name,p]of Object.entries(g.properties)){const d=cloneDefinition(p);if(d)defs[name]=d;}defs[MARKER]={rich_text:{}};defs[CREATED]={date:{}};
   const found=(await blocks(job.folderId)).find(b=>b.type==='child_database'&&b.child_database.title===LABELS[g.kind]);let db;
   if(found)db=await notion(`/databases/${found.id}`);else{await guard();db=await notion('/databases',{method:'POST',body:{parent:{type:'page_id',page_id:job.folderId},title:text(LABELS[g.kind]),initial_data_source:{properties:defs}}});}if(!db.data_sources?.[0]?.id)throw new AppError('O Notion não retornou a fonte do banco copiado.',502);g.target={databaseId:db.id,sourceId:db.data_sources[0].id};job.group++;}
 }else if(job.phase==='relationSchemas'){
  if(job.group>=job.groups.length){job.group=0;job.phase='enumerate';}else{const g=job.groups[job.group],defs={};for(const [name,p]of Object.entries(g.properties)){if(p.type!=='relation')continue;const to=job.groups.find(t=>p.relation.data_source_id?t.sourceId===p.relation.data_source_id:t.databaseId.replaceAll('-','')===p.relation.database_id.replaceAll('-',''));if(!to)throw new AppError(`A relação ${name} aponta para um banco fora do LifeOS.`,422);defs[name]={relation:{data_source_id:to.target.sourceId,type:'single_property',single_property:{}}};}if(Object.keys(defs).length){await guard();await notion(`/data_sources/${g.target.sourceId}`,{method:'PATCH',body:{properties:defs}});}job.group++;}
 }else if(job.phase==='enumerate'){
  if(job.group>=job.groups.length){job.group=0;job.row=0;job.phase='copy';}else{const g=job.groups[job.group],rows=await queryAll(g.sourceId);g.rows=rows.map(r=>({id:r.id,edited:r.last_edited_time}));job.total+=g.rows.length;job.group++;}
 }else if(job.phase==='copy'||job.phase==='relations'){
  if(job.group>=job.groups.length){job.group=0;job.row=0;job.phase=job.phase==='copy'?'relations':'verifyRecords';}
  else{const g=job.groups[job.group],ref=g.rows[job.row];if(!ref){job.group++;job.row=0;}else{const page=await notion(`/pages/${ref.id}`);if(page.archived||page.in_trash||page.last_edited_time!==ref.edited)throw new AppError('Um registro mudou diretamente no Notion durante a cópia. Cancele e inicie novamente.',409);if(job.phase==='relations'){const values=await cloneValues(page,job,true);if(Object.keys(values).length>1){await guard();await notion(`/pages/${job.map[page.id]}`,{method:'PATCH',body:{properties:values}});}}
   else{const found=await notion(`/data_sources/${g.target.sourceId}/query`,{method:'POST',body:{filter:{property:MARKER,rich_text:{equals:page.id}},page_size:2}});if(found.results.length>1)throw new AppError('Duplicação detectada na cópia.',409);let copied=found.results[0];if(!copied){const properties=await cloneValues(page,job),children=await bodyCopy(page.id,job),assets={};for(const key of ['icon','cover']){if(page[key]){if(page[key].type==='emoji')assets[key]=page[key];else{const asset=await filePayload({...page[key],name:key+'.png'},job,page.id+':'+key);delete asset.name;assets[key]=asset;}}}await guard();copied=await notion('/pages',{method:'POST',body:{parent:{type:'data_source_id',data_source_id:g.target.sourceId},properties,...assets,...(children.length?{children}:{})}});}job.map[page.id]=copied.id;job.done++;}job.row++;}}
 }else if(job.phase==='verifyRecords'){
  if(job.group>=job.groups.length){job.group=0;job.phase='verify';}else{const g=job.groups[job.group],r=g.rows[job.row];if(!r){job.group++;job.row=0;}else{const original=await notion(`/pages/${r.id}`),copied=await notion(`/pages/${job.map[r.id]}`);await verifyValues(original,copied,job);job.row++;}}
 }else if(job.phase==='verify'){
  if(job.group>=job.groups.length){job.phase='finish';}else{const g=job.groups[job.group],original=await queryAll(g.sourceId),copied=await queryAll(g.target.sourceId);if(original.length!==g.rows.length||copied.length!==g.rows.length||original.some(p=>!g.rows.some(r=>r.id===p.id&&r.edited===p.last_edited_time))||g.rows.some(r=>!copied.some(p=>p.id===job.map[r.id]&&plain(p.properties[MARKER]?.rich_text)===r.id)))throw new AppError('A conferência da cópia falhou. Os bancos ativos permanecem intactos.',409);job.group++;}
 }else if(job.phase==='finish')await finish(job,guard);
 job.message=job.status==='completed'?job.message:`${job.stage==='safety'?'Cópia de segurança atual':job.stage==='restoreCopy'?'Preparando restauração':'Backup'} · ${PHASES[job.phase]||job.phase}`;await save(job);return publicJob(job);
 }catch(e){job.status='paused';job.error=e instanceof AppError?e.message:'Operação interrompida. Retome para tentar novamente.';await save(job);throw e;}
 },id);}
export async function cancelBackup(user,id){backupAdmin(user);const job=await getJSON(JOB(id));if(!job||id!==await getJSON(ACTIVE))throw new AppError('Operação não encontrada.',404);return withWriteLock(async()=>{job.status='cancelled';job.message='Operação cancelada. As cópias incompletas não são usadas para restaurar.';await save(job);await release(job);return publicJob(job);},id);}
