import {randomBytes,createHash} from 'node:crypto';
import {OAuth2Client} from 'google-auth-library';
import {AppError,allowedEmails,appOrigin,configured,seal,unseal,cookieValue,sessionCookie} from './auth';
const STATE_COOKIE='lifeos_google_flow';
const flowCookie=(value,age)=>`${STATE_COOKIE}=${value}; HttpOnly; SameSite=Lax; Path=/api/auth/google; Max-Age=${age}${process.env.NODE_ENV==='production'?'; Secure':''}`;
export const clearFlow=()=>flowCookie('',0);
const client=()=>new OAuth2Client(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,appOrigin()+'/api/auth/google/callback');
export function startGoogle(){if(!configured())throw new AppError('Configure as variáveis do Google na Vercel antes de entrar.',503);const state=randomBytes(32).toString('base64url'),nonce=randomBytes(32).toString('base64url'),verifier=randomBytes(48).toString('base64url');const url=client().generateAuthUrl({scope:['openid','email','profile'],response_type:'code',prompt:'select_account',state,nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'});return {url,cookie:flowCookie(seal({state,nonce,verifier,exp:Date.now()+600000}),600)};}
export function validateGooglePayload(payload,nonce){if(!payload||payload.nonce!==nonce||payload.email_verified!==true||!payload.sub||!payload.email?.endsWith('@gmail.com'))throw new AppError('Não foi possível validar a conta Google.',401);const email=payload.email.toLowerCase();if(!allowedEmails().includes(email))throw new AppError('Esta conta Google não está autorizada a acessar o LifeOS.',403);return {id:'google:'+payload.sub,email,name:String(payload.name||email.split('@')[0]).slice(0,100)};}
export async function finishGoogle(request){const params=new URL(request.url).searchParams,flow=unseal(cookieValue(request,STATE_COOKIE));if(!configured()||!flow||flow.exp<Date.now()||flow.exp>Date.now()+600000||!params.get('state')||params.get('state')!==flow.state||!params.get('code')||params.has('error'))throw new AppError('Login cancelado ou expirado. Tente novamente.',401);const oauth=client();const {tokens}=await oauth.getToken({code:params.get('code'),codeVerifier:flow.verifier});if(!tokens.id_token)throw new AppError('O Google não retornou a identificação da conta.',401);const ticket=await oauth.verifyIdToken({idToken:tokens.id_token,audience:process.env.GOOGLE_CLIENT_ID});const user=validateGooglePayload(ticket.getPayload(),flow.nonce);return {user,cookie:sessionCookie(user)};}
