const dns=require('node:dns/promises');const originalLookup=dns.lookup;dns.lookup=async()=>[{address:'8.8.8.8',family:4}];
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),swc=require('next/dist/build/swc'),{randomUUID}=require('node:crypto');
const originalNow=Date.now;let clock=originalNow();Date.now=()=>{clock+=500;return clock;};
const root=path.resolve('.backup-test');fs.mkdirSync(root,{recursive:true});for(const file of ['backup','maintenance','auth','coordination','notion'])fs.writeFileSync(path.join(root,file+'.js'),swc.transformSync(fs.readFileSync('lib/server/'+file+'.js','utf8'),{jsc:{parser:{syntax:'ecmascript'},target:'es2022'},module:{type:'commonjs'}}).code);
process.env.LIFEOS_LEGACY_OWNER_EMAIL='periclesbernardes@gmail.com';process.env.NOTION_BACKUP_PAGE_ID=randomUUID();const admin={email:process.env.LIFEOS_LEGACY_OWNER_EMAIL},other={email:'leticiacost3@gmail.com'},kv=new Map(),pages=new Map(),sources=new Map(),dbs=new Map(),tree=new Map(),files=new Map();
let locked=false,uploadCount=0,failCreate=false;const clone=x=>structuredClone(x);
async function redis(c){if(c[0]==='GET')return kv.get(c[1])||null;if(c[0]==='SET'){if(c.includes('NX')&&kv.has(c[1]))return null;kv.set(c[1],c[2]);return 'OK';}if(c[0]==='DEL'){kv.delete(c[1]);return 1;}if(c[0]==='EVAL'){const value=JSON.parse(kv.get(c[3])||'null');if(value?.id===c[4])kv.delete(c[3]);return 1;}throw Error(c[0]);}
require.cache[path.join(root,'coordination.js')]={exports:{redis,withWriteLock:async(fn,id)=>{if(locked)throw Error('locked');locked=true;try{await require(path.join(root,'maintenance')).ensureWritable(id);return await fn(async()=>{});}finally{locked=false;}}}};
const cfg={};for(const kind of ['projects','tasks','recados']){const databaseId=randomUUID(),sourceId=randomUUID();cfg[kind]={databaseId,sourceId};dbs.set(databaseId,{id:databaseId,data_sources:[{id:sourceId}]});sources.set(sourceId,{id:sourceId,properties:{Nome:{name:'Nome',type:'title',title:{}},Texto:{name:'Texto',type:'rich_text',rich_text:{}},Anexos:{name:'Anexos',type:'files',files:{}},'LifeOS Usuário':{name:'LifeOS Usuário',type:'rich_text',rich_text:{}}}});process.env['NOTION_'+kind.toUpperCase()+'_DATABASE_ID']=databaseId;}
sources.get(cfg.tasks.sourceId).properties.Projeto={name:'Projeto',type:'relation',relation:{data_source_id:cfg.projects.sourceId}};
const rich=value=>[{type:'text',text:{content:value}}];const originalProject=randomUUID(),originalTask=randomUUID(),originalRecado=randomUUID();const bytes=Buffer.from('Imagem e anexo binário de teste'),assetURL='https://files.notionusercontent.com/original';files.set(assetURL,bytes);
function addPage(id,sourceId,name,owner,props={}){const row={id,parent:{data_source_id:sourceId},created_time:'2026-01-02T12:00:00Z',last_edited_time:'2026-01-02T12:00:00Z',properties:{Nome:{type:'title',title:rich(name)},Texto:{type:'rich_text',rich_text:rich('Mensagem de teste')},Anexos:{type:'files',files:[]},'LifeOS Usuário':{type:'rich_text',rich_text:rich(owner)},...props}};pages.set(id,row);return row;}
addPage(originalProject,cfg.projects.sourceId,'Projeto Péricles','google:p',{Anexos:{type:'files',files:[{name:'foto.png',type:'file',file:{url:assetURL}}]}});addPage(originalTask,cfg.tasks.sourceId,'Tarefa Letícia','google:l',{Projeto:{type:'relation',relation:[{id:originalProject}]}});addPage(originalRecado,cfg.recados.sourceId,'Recado','google:p');
function storeBlocks(owner,children){tree.set(owner,children.map(child=>{const row=clone(child),data=row[row.type],nested=data.children||[];row.id=randomUUID();row.has_children=!!nested.length;delete data.children;if(['image','file','video','audio'].includes(row.type)&&data.type==='file_upload'){const url='https://files.notionusercontent.com/'+data.file_upload.id;delete data.file_upload;data.type='file';data.file={url};}if(nested.length)storeBlocks(row.id,nested);return row;}));}
tree.set(originalProject,[{id:randomUUID(),type:'paragraph',has_children:false,paragraph:{rich_text:rich('Texto no corpo da página')}},{id:randomUUID(),type:'image',has_children:false,image:{type:'file',file:{url:assetURL},caption:rich('Imagem no corpo')}}]);
function storedProperties(values){const result={};for(const [name,value]of Object.entries(values)){const type=Object.keys(value)[0];result[name]={type,[type]:type==='files'?value.files.map(f=>{const url='https://files.notionusercontent.com/'+f.file_upload.id;return {name:f.name,type:'file',file:{url}};}):clone(value[type])};}return result;}
async function notion(url,opts={}){const body=opts.body||{};if(url.startsWith('/blocks/')){const id=url.split('/')[2];if(opts.method==='PATCH')tree.set(id,[...(tree.get(id)||[]),...body.children]);return {results:clone(tree.get(id)||[]),has_more:false};}if(url==='/databases'){
 const id=randomUUID(),sid=randomUUID(),props=Object.fromEntries(Object.entries(body.initial_data_source.properties).map(([n,p])=>[n,{name:n,type:Object.keys(p)[0],...p}]));sources.set(sid,{id:sid,properties:props});const db={id,data_sources:[{id:sid}]};dbs.set(id,db);const children=tree.get(body.parent.page_id)||[];children.push({id,type:'child_database',child_database:{title:body.title[0].text.content}});tree.set(body.parent.page_id,children);return clone(db);
 }if(url.startsWith('/databases/'))return clone(dbs.get(url.split('/')[2]));if(url.startsWith('/data_sources/')){const id=url.split('/')[2];if(url.endsWith('/query')){let results=[...pages.values()].filter(p=>p.parent.data_source_id===id&&!p.archived);if(body.filter)results=results.filter(p=>p.properties[body.filter.property]?.rich_text?.[0]?.text?.content===body.filter.rich_text.equals);return {results:clone(results),has_more:false};}const s=sources.get(id);if(opts.method==='PATCH')for(const [n,p]of Object.entries(body.properties))s.properties[n]={name:n,type:Object.keys(p)[0],...p};return clone(s);}
 if(url==='/pages'){if(failCreate&&body.parent.data_source_id){failCreate=false;throw Error('simulated timeout');}const id=randomUUID();if(body.parent.page_id){const title=body.properties.title.title[0].text.content;pages.set(id,{id,parent:{page_id:body.parent.page_id},properties:{},last_edited_time:'2026-01-02T12:00:00Z'});const children=tree.get(body.parent.page_id)||[];children.push({id,type:'child_page',child_page:{title}});tree.set(body.parent.page_id,children);return {id};}const p={id,parent:body.parent,created_time:new Date().toISOString(),last_edited_time:new Date().toISOString(),properties:storedProperties(body.properties)};pages.set(id,p);storeBlocks(id,body.children||[]);return clone(p);}
 if(url.startsWith('/pages/')){const p=pages.get(url.split('/')[2]);assert.ok(p);if(opts.method==='PATCH'){if(body.archived)p.archived=true;if(body.properties)Object.assign(p.properties,storedProperties(body.properties));}return clone(p);}throw Error(url);
}
const notionMock={DB:Object.fromEntries(Object.keys(cfg).map(k=>[k,['NOTION_'+k.toUpperCase()+'_DATABASE_ID','']])),LABELS:{projects:'Projetos',tasks:'Tarefas',recados:'Recados'},notion,schema:async kind=>{const route=JSON.parse(kv.get('lifeos:database-routing:v1')||'{}');const g=route.banks?.[kind]||cfg[kind];return {databaseId:g.databaseId,id:g.sourceId};},queryAll:async id=>clone([...pages.values()].filter(p=>p.parent.data_source_id===id&&!p.archived)),plain:list=>(list||[]).map(p=>p.text?.content||p.plain_text||'').join(''),uploadFile:async f=>{uploadCount++;const id=randomUUID();files.set('https://files.notionusercontent.com/'+id,Buffer.from(await f.arrayBuffer()));return {uploadId:id,name:f.name};}};
require.cache[path.join(root,'notion.js')]={exports:notionMock};global.fetch=async url=>{const b=files.get(String(url));assert.ok(b,'File URL must belong to Notion');return new Response(b,{headers:{'content-length':b.length,'content-type':'image/png'}});};const api=require(path.join(root,'backup'));
async function complete(id){for(let i=0;i<200;i++){const result=await api.backupStep(admin,id);if(result.status==='completed')return result;}throw Error('Never completed');}
(async()=>{try{
 await assert.rejects(()=>api.startBackup(other),e=>e.status===403);assert.throws(()=>api.cloneDefinition({name:'Calculated',type:'formula'}),e=>e.status===422);
 const original=clone([...pages.values()]);let job=await api.startBackup(admin);await assert.rejects(()=>require(path.join(root,'maintenance')).ensureWritable(),e=>e.status===423);assert.deepEqual(await api.backupStatus(other),{maintenance:true});
 failCreate=true;let paused=false;for(let i=0;i<20&&!paused;i++){try{await api.backupStep(admin,job.id);}catch(e){paused=true;}}assert.ok(paused);assert.equal((await api.backupStatus(admin)).backups.length,0);
 for(let i=0;i<100;i++){const step=await api.backupStep(admin,job.id);if(step.phase==='verifyRecords')break;}const inProgress=JSON.parse(kv.get('lifeos:backup-job:'+job.id));const staged=pages.get(inProgress.map[originalProject]),testURL=staged.properties.Anexos.files[0].file.url,validBytes=files.get(testURL);files.set(testURL,Buffer.from('Arquivo corrompido'));await assert.rejects(()=>api.backupStep(admin,job.id),/difere do original/);assert.equal((await api.backupStatus(admin)).backups.length,0);files.set(testURL,validBytes);await complete(job.id);
 let status=await api.backupStatus(admin);assert.equal(status.maintenance,false);assert.equal(status.backups.length,1);assert.ok(uploadCount);const saved=JSON.parse(kv.get('lifeos:backups:v1'))[0];const copiedProject=[...pages.values()].find(p=>p.parent.data_source_id===saved.banks.projects.sourceId);const copiedTask=[...pages.values()].find(p=>p.parent.data_source_id===saved.banks.tasks.sourceId);assert.equal(copiedTask.properties.Projeto.relation[0].id,copiedProject.id);assert.equal(copiedTask.properties['LifeOS Usuário'].rich_text[0].text.content,'google:l');assert.notEqual(copiedProject.properties.Anexos.files[0].file.url,assetURL);
 for(const p of original)assert.deepEqual(pages.get(p.id),p,'Backup must not modify originals');
 pages.get(originalProject).properties.Texto.rich_text=rich('Texto alterado depois do backup');pages.get(originalProject).last_edited_time='2026-10-06T18:00:00Z';const editedOriginal=clone(pages.get(originalProject));job=await api.startBackup(admin,'restore',saved.id);await complete(job.id);const routing=JSON.parse(kv.get('lifeos:database-routing:v1'));assert.notEqual(routing.banks.projects.databaseId,cfg.projects.databaseId);const restored=[...pages.values()].find(p=>p.parent.data_source_id===routing.banks.projects.sourceId);assert.equal(restored.properties.Texto.rich_text[0].text.content,'Mensagem de teste');assert.deepEqual(pages.get(originalProject),editedOriginal,'Restore must preserve previous originals');status=await api.backupStatus(admin);assert.equal(status.maintenance,false);assert.equal(status.backups.length,2,'Safety copy must exist before restore');
 job=await api.startBackup(admin);await api.cancelBackup(admin,job.id);assert.equal((await api.backupStatus(admin)).maintenance,false);assert.equal(JSON.parse(kv.get('lifeos:database-routing:v1')).version,routing.version,'Cancellation must not change active banks');
 for(let i=0;i<2;i++){job=await api.startBackup(admin);await complete(job.id);}assert.equal((await api.backupStatus(admin)).backups.length,3);assert.ok(!pages.get(routing.folderId).archived,'Retention must never archive active restored banks');
 console.log('PASSOU: administrador exclusivo, bloqueio das duas contas, retomada após falha, cópia binária verificada, relações e proprietários preservados, restauração em bancos novos com cópia de segurança, cancelamento sem alterar bancos ativos e retenção de três cópias.');
 }finally{Date.now=originalNow;dns.lookup=originalLookup;fs.rmSync(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
