const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),swc=require('next/dist/build/swc');const file=path.resolve('.external-links-test.cjs');fs.writeFileSync(file,swc.transformSync(fs.readFileSync('lib/externalLinks.js','utf8'),{jsc:{parser:{syntax:'ecmascript'},target:'es2022'},module:{type:'commonjs'}}).code);
try{const {externalUrl,chromeIntent,routeExternalClick}=require(file),origin='https://lifeos.test';assert.equal(externalUrl('/pair#id=private&token=private',origin),null);assert.equal(externalUrl('/api/notion/attachment?kind=tasks&id=1',origin),null);assert.equal(externalUrl('javascript:alert(1)',origin),null);assert.equal(externalUrl('intent://evil/#Intent;end',origin),null);assert.equal(externalUrl('https://name:secret@example.com',origin),null);
 const url=new URL('https://example.com/path?query=%23Intent%3Bpackage%3Devil'),intent=chromeIntent(url);assert.ok(intent.includes('package=com.android.chrome;'));assert.ok(intent.endsWith(';end'));assert.ok(intent.includes('S.browser_fallback_url='+encodeURIComponent(url.href)));assert.equal(chromeIntent(new URL('https://example.com/path#section')),null);
 function link(href,attrs={}){const values={href,...attrs};return {values,getAttribute:k=>values[k]||null,setAttribute:(k,v)=>values[k]=v,hasAttribute:k=>Object.hasOwn(values,k)};}
 function click(anchor,androidInstalled=true,overrides={}){let restore;const event={button:0,target:{closest:()=>anchor},...overrides};routeExternalClick(event,{origin,androidInstalled,defer:fn=>restore=fn});return restore;}
 const a=link(url.href,{rel:'nofollow'}),restore=click(a);assert.equal(a.values.target,'_blank');assert.ok(a.values.rel.includes('noopener'));assert.ok(a.values.rel.includes('noreferrer'));assert.ok(a.values.rel.includes('external'));assert.ok(a.values.rel.includes('nofollow'));assert.equal(a.values.href,intent);restore();assert.equal(a.values.href,url.href);
 const ios=link('https://example.com');assert.equal(click(ios,false),undefined);assert.equal(ios.values.href,'https://example.com');assert.equal(ios.values.target,'_blank');
 for(const overrides of [{ctrlKey:true},{metaKey:true},{shiftKey:true},{altKey:true},{button:1},{defaultPrevented:true}]){const n=link('https://example.com');click(n,true,overrides);assert.equal(n.values.target,undefined);assert.equal(n.values.href,'https://example.com');}
 for(const href of ['/pair','/api/auth/google','/api/notion/attachment?name=file','https://lifeos.test/pair#id=secret&token=secret','mailto:user@example.com','javascript:bad']){const n=link(href);click(n);assert.deepEqual(n.values,{href});}
 const download=link('https://example.com/file',{download:''});click(download);assert.equal(download.values.target,undefined);
 const fragment=link('https://example.com#keep');click(fragment);assert.equal(fragment.values.href,'https://example.com#keep');assert.equal(fragment.values.target,'_blank');
 const rerender=link(url.href),undo=click(rerender);rerender.setAttribute('href','https://different.test');undo();assert.equal(rerender.values.href,'https://different.test');
 console.log('PASSOU: Chrome Intent apenas no Android instalado, fallback preservado, abertura separada no iOS/desktop, links internos e QR/autenticação intactos, fragmentos, downloads e cliques modificados preservados.');
}finally{fs.rmSync(file,{force:true});}
