const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),swc=require('next/dist/build/swc'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const folder=path.resolve('.finance-test');
for(const dir of ['lib','components']){fs.mkdirSync(path.join(folder,dir),{recursive:true});for(const name of fs.readdirSync(dir)){if(!name.endsWith('.js'))continue;fs.writeFileSync(path.join(folder,dir,name),swc.transformSync(fs.readFileSync(path.join(dir,name),'utf8'),{filename:name,jsc:{parser:{syntax:'ecmascript',jsx:true},transform:{react:{runtime:'automatic'}},target:'es2022'},module:{type:'commonjs'}}).code);}}
try{
 const {parseMonth,maskMonth,parseMoney,consolidate,sankeyLayout,currentMonth,maskReal,completeReal,startOfMonth,endOfMonth,normalizeTransaction,sortedCategories}=require(path.join(folder,'lib/finance'));
 assert.deepEqual(parseMonth('3',2026),{value:'2026-03'});assert.deepEqual(parseMonth('11/2025'),{value:'2025-11'});assert.ok(parseMonth('13').error);assert.ok(parseMonth('02/26').error);assert.equal(maskMonth('122026'),'12/2026');
 assert.equal(maskReal('1250'),'R$ 1.250');assert.equal(completeReal('1250'),'R$ 1.250,00');assert.equal(completeReal('1250,5'),'R$ 1.250,50');assert.equal(maskReal('R$ 1.250,56'),'R$ 1.250,56');assert.equal(completeReal(''),'');
 assert.equal(parseMoney('1.234,56'),123456);assert.equal(parseMoney('12,3'),1230);assert.equal(parseMoney('0,01'),1);assert.equal(parseMoney('-5'),null);assert.equal(parseMoney('0'),null);assert.equal(parseMoney('1,234'),null);
 assert.equal(startOfMonth('2026-10'),'2026-10-01');assert.equal(endOfMonth('2024-02'),'2024-02-29');assert.equal(endOfMonth('2026-02'),'2026-02-28');assert.equal(normalizeTransaction({id:'old',month:'2026-10'}).date,'2026-10-01');
 const {hasChanges}=require(path.join(folder,'lib/notionDiff'));
 assert.ok(hasChanges({projects:[],transactions:[{id:'old',month:'2026-10'}]},{projects:[],transactions:[{id:'old',month:'2026-11'}]}),'Mudança de mês em rascunho antigo precisa ser preservada');
 const unsorted=[{id:'z',name:'Zebra'},{id:'a',name:'Água'},{id:'c',name:'contas'}];assert.deepEqual(sortedCategories(unsorted).map(item=>item.name),['Água','contas','Zebra']);assert.equal(unsorted[0].name,'Zebra');
 const categories=[{id:'a',name:'Salário',flow:'in'},{id:'b',name:'Contas',flow:'out'}],month=currentMonth();
 const tx=[{id:'1',category:'a',amount:100000,month},{id:'2',category:'b',amount:60000,month},{id:'3',category:'a',amount:12345,month:'2025-01'}];
 const positive=consolidate(categories,tx,month,month);assert.equal(positive.balance,40000);assert.equal(positive.right.find(n=>n.system).value,40000);assert.equal(positive.left.some(n=>n.system),false);
 const negative=consolidate(categories,[{category:'b',amount:60000,month}],month,month);assert.equal(negative.balance,-60000);assert.equal(negative.left[0].flow,'deficit');assert.equal(negative.right.some(n=>n.system),false);assert.equal(negative.left.reduce((s,n)=>s+n.value,0),negative.right.reduce((s,n)=>s+n.value,0));
 const zero=consolidate(categories,[{category:'a',amount:1,month},{category:'b',amount:1,month}],month,month);assert.equal(zero.balance,0);assert.equal([...zero.left,...zero.right].some(n=>n.system),false);
 const year=consolidate(categories,tx,'2025-01','2025-12');assert.equal(year.income,12345);assert.equal(year.expense,0);assert.equal(consolidate(categories,tx,'2025-01',month).income,112345);
 const byDay=[{category:'a',date:'2026-10-01',amount:100},{category:'a',date:'2026-10-10',amount:200},{category:'b',date:'2026-10-20',amount:50},{category:'a',date:'2026-10-31',amount:300}];
 const specific=consolidate(categories,byDay,'2026-10-10','2026-10-20');assert.equal(specific.income,200);assert.equal(specific.expense,50);assert.equal(consolidate(categories,byDay,'2026-10-01','2026-10-31').income,600);assert.equal(consolidate(categories,byDay,'2026-01-01','2026-12-31').expense,50);
 const {parseDateInput}=require(path.join(folder,'lib/dateInput'));assert.equal(parseDateInput('14/10',2026).value,'2026-10-14');
 const layout=sankeyLayout(positive);assert.ok(Math.abs(layout.left.reduce((s,n)=>s+n.h,0)-layout.right.reduce((s,n)=>s+n.h,0))<0.001);
 const FinanceView=require(path.join(folder,'components/FinanceView')).default;
 const html=renderToStaticMarkup(React.createElement(FinanceView,{categories,transactions:tx,configured:true,setFinance(){}}));assert.match(html,/Saldo restante/);assert.match(html,/Gerenciar categorias/);assert.match(html,/R\$ 400,00/);assert.match(html,/role="button"/);assert.match(html,/Adicionar valor/);
 const deficitHtml=renderToStaticMarkup(React.createElement(FinanceView,{categories,transactions:[{category:'b',amount:60000,month}],configured:true,setFinance(){}}));assert.match(deficitHtml,/Saldo faltante/);assert.match(deficitHtml,/#f26d64/);assert.match(deficitHtml,/-R\$ 600,00/);assert.doesNotMatch(deficitHtml,/Entradas \+ saldo faltante/);
 const partialDeficit=renderToStaticMarkup(React.createElement(FinanceView,{categories,transactions:[{category:'a',amount:100000,month},{category:'b',amount:160000,month}],configured:true,setFinance(){}}));assert.match(partialDeficit,/<text x="550" y="44"[^>]*>R\$ 1.000,00<\/text>/);assert.match(partialDeficit,/Saldo faltante: -R\$ 600,00/);
 const setup=renderToStaticMarkup(React.createElement(FinanceView,{configured:false,setFinance(){}}));assert.match(setup,/NOTION_FINANCE_CATEGORIES_DATABASE_ID/);

 const oldRAF=global.requestAnimationFrame;global.requestAnimationFrame=()=>{};
 const originalRef=React.useRef,originalEffect=React.useEffect;React.useRef=value=>({current:value});React.useEffect=()=>{};const originalState=React.useState,slots=[];let cursor=0,model={categories:[],transactions:[]};
 React.useState=initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return [slots[i],update=>{slots[i]=typeof update==='function'?update(slots[i]):update;}];};
 function walk(node,predicate){if(!node||typeof node!=='object')return null;if(predicate(node))return node;for(const child of React.Children.toArray(node.props?.children)){const result=walk(child,predicate);if(result)return result;}return null;}
 const button=(tree,text)=>walk(tree,node=>node.type==='button'&&node.props.children===text);
 const label=(tree,text)=>walk(tree,node=>node.type==='label'&&React.Children.toArray(node.props.children)[0]===text);
 const control=(node,type)=>walk(node,item=>item.type===type);
 try{
  const render=()=>{cursor=0;return FinanceView({...model,configured:true,setFinance:update=>{model=typeof update==='function'?update(model):update;}});};
  let tree=render();button(tree,'Gerenciar categorias').props.onClick();tree=render();control(label(tree,'Nome'),'input').props.onChange({target:{value:'Salário'}});tree=render();button(tree,'+ Criar categoria').props.onClick();assert.equal(model.categories.length,1);assert.equal(model.categories[0].flow,'in');
  tree=render();assert.ok(walk(tree,node=>node.props?.['aria-label']==='Categorias de entradas'));assert.ok(walk(tree,node=>node.props?.['aria-label']==='Categorias de saídas'));button(tree,'Fechar').props.onClick();tree=render();control(label(tree,'Categoria'),'select').props.onChange({target:{value:model.categories[0].id}});control(label(tree,'Valor'),'input').props.onChange({target:{value:'1.500,00',selectionStart:8}});walk(label(tree,'Data'),node=>node.type?.name==='DateInput').props.onChange({target:{value:month+'-15'}});walk(tree,node=>node.props?.['aria-label']==='Observação do lançamento').props.onChange({target:{value:'Compra planejada\nGuardar comprovante'}});tree=render();button(tree,'+ Adicionar').props.onClick();assert.equal(model.transactions.length,1);assert.equal(model.transactions[0].amount,150000);assert.equal(model.transactions[0].date,month+'-15');assert.equal(model.transactions[0].notes,'Compra planejada\nGuardar comprovante');
  tree=render();walk(tree,node=>node.type?.name==='Sankey').props.onSelect(model.categories[0].id);tree=render();button(tree,'Editar').props.onClick();tree=render();walk(tree,node=>node.type==='input'&&node.props.value==='R$ 1.500,00').props.onChange({target:{value:'2000,00',selectionStart:7}});tree=render();walk(tree,node=>node.type?.name==='DateInput'&&node.props['aria-label']==='Editar data do lançamento').props.onChange({target:{value:month+'-27'}});tree=render();walk(tree,node=>node.props?.['aria-label']==='Editar observação do lançamento').props.onChange({target:{value:'Observação editada'}});tree=render();button(tree,'Salvar').props.onClick();assert.equal(model.transactions[0].amount,200000);assert.equal(model.transactions[0].date,month+'-27');assert.equal(model.transactions[0].notes,'Observação editada');
  tree=render();button(tree,'Fechar').props.onClick();tree=render();button(tree,'Ano').props.onClick();tree=render();button(tree,'Hoje').props.onClick();tree=render();assert.ok(walk(tree,node=>node.type?.name==='MonthInput'&&node.props.value===month),'Hoje volta ao mês atual');walk(tree,node=>node.type?.name==='Sankey').props.onSelect(model.categories[0].id);tree=render();
  global.window={confirm:()=>false};tree=render();button(tree,'Excluir').props.onClick();assert.equal(model.transactions.length,1,'Cancelar exclusão mantém o registro');global.window.confirm=()=>true;button(tree,'Excluir').props.onClick();assert.equal(model.transactions.length,0);
 }finally{React.useState=originalState;React.useRef=originalRef;React.useEffect=originalEffect;global.requestAnimationFrame=oldRAF;delete global.window;}
 console.log('PASSOU: mês com ano automático, valores em centavos, consolidação anual e por período, sobra e déficit automáticos, proporções do Sankey, blocos interativos e tela de configuração.');
}finally{fs.rmSync(folder,{recursive:true,force:true});}
