const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),swc=require('next/dist/build/swc');
const root=path.resolve('.google-test');fs.mkdirSync(path.join(root,'lib/server'),{recursive:true});
for(const name of ['auth.js','google.js','googleCompletion.js'])fs.writeFileSync(path.join(root,'lib/server',name),swc.transformSync(fs.readFileSync(path.join('lib/server',name),'utf8'),{jsc:{parser:{syntax:'ecmascript'},target:'es2022'},module:{type:'commonjs'}}).code);
process.env.NOTION_TOKEN='test';process.env.GOOGLE_CLIENT_ID='client.apps.googleusercontent.com';process.env.GOOGLE_CLIENT_SECRET='secret';process.env.LIFEOS_SESSION_SECRET='x'.repeat(48);process.env.LIFEOS_APP_URL='https://lifeos-two-kohl-18.vercel.app';process.env.LIFEOS_ALLOWED_GOOGLE_EMAILS='periclesbernardes@gmail.com,leticiacost3@gmail.com';process.env.LIFEOS_LEGACY_OWNER_EMAIL='periclesbernardes@gmail.com';
const auth=require(path.join(root,'lib/server/auth')),google=require(path.join(root,'lib/server/google')),{OAuth2Client}=require('google-auth-library');
(async()=>{try{
 const flow=google.startGoogle(),url=new URL(flow.url),cookie=flow.cookie.split(';')[0],data=auth.unseal(cookie.split('=')[1]);assert.equal(url.hostname,'accounts.google.com');assert.equal(url.searchParams.get('redirect_uri'),process.env.LIFEOS_APP_URL+'/api/auth/google/callback');assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(url.searchParams.get('nonce'),data.nonce);assert.ok(flow.cookie.includes('HttpOnly'));assert.ok(flow.cookie.includes('SameSite=Lax'));
 const popupFlow=google.startGoogle(true),popupData=auth.unseal(popupFlow.cookie.split(';')[0].split('=')[1]);assert.equal(popupData.popup,true);assert.equal(google.googlePopupFlow(new Request(process.env.LIFEOS_APP_URL+'/api/auth/google/callback?state='+popupData.state,{headers:{cookie:popupFlow.cookie.split(';')[0]}})),true);assert.equal(google.googlePopupFlow(new Request(process.env.LIFEOS_APP_URL+'/api/auth/google/callback?state=wrong',{headers:{cookie:popupFlow.cookie.split(';')[0]}})),false);
 const {googleCompletion}=require(path.join(root,'lib/server/googleCompletion'));const completion=googleCompletion(process.env.LIFEOS_APP_URL,'</script><script>alert(1)</script>');assert.ok(completion.body.includes('postMessage'));assert.ok(completion.body.includes('window.close()'));assert.ok(completion.headers['Content-Security-Policy'].includes("frame-ancestors 'none'"));assert.equal(completion.body.includes('</script><script>alert(1)'),false);assert.equal(completion.body.includes('lifeos_google_session'),false);
 const payload={sub:'10001',email:'periclesbernardes@gmail.com',email_verified:true,name:'Péricles',nonce:data.nonce};assert.equal(google.validateGooglePayload(payload,data.nonce).id,'google:10001');assert.throws(()=>google.validateGooglePayload({...payload,email:'stranger@gmail.com'},data.nonce),error=>error.status===403);assert.throws(()=>google.validateGooglePayload({...payload,email_verified:false},data.nonce),error=>error.status===401);assert.throws(()=>google.validateGooglePayload(payload,'wrong-nonce'),error=>error.status===401);
 const originalGet=OAuth2Client.prototype.getToken,originalVerify=OAuth2Client.prototype.verifyIdToken;let verifyArgs;
 OAuth2Client.prototype.getToken=async args=>{assert.equal(args.codeVerifier,data.verifier);return {tokens:{id_token:'verified-by-library-mock'}};};OAuth2Client.prototype.verifyIdToken=async args=>{verifyArgs=args;return {getPayload:()=>payload};};
 try{const request=new Request(process.env.LIFEOS_APP_URL+'/api/auth/google/callback?code=test-code&state='+data.state,{headers:{cookie}}),result=await google.finishGoogle(request);assert.equal(verifyArgs.audience,process.env.GOOGLE_CLIENT_ID);const sessionRequest=new Request(process.env.LIFEOS_APP_URL+'/api/notion',{headers:{cookie:result.cookie.split(';')[0]}});assert.equal(auth.authorize(sessionRequest).email,payload.email);assert.equal(auth.authenticated(new Request(sessionRequest.url,{headers:{cookie:result.cookie.split(';')[0]+'tampered'}})),false);await assert.rejects(()=>google.finishGoogle(new Request(process.env.LIFEOS_APP_URL+'/api/auth/google/callback?code=test&state=wrong',{headers:{cookie}})),error=>error.status===401);assert.throws(()=>auth.authorize(new Request(sessionRequest.url,{headers:{cookie:result.cookie.split(';')[0],'X-LifeOS-User':'google:someone-else'}})),error=>error.status===401);}finally{OAuth2Client.prototype.getToken=originalGet;OAuth2Client.prototype.verifyIdToken=originalVerify;}
 const expired=auth.seal({id:'google:10001',email:payload.email,exp:Date.now()-1});assert.equal(auth.authenticated(new Request(process.env.LIFEOS_APP_URL,{headers:{cookie:'lifeos_google_session='+expired}})),false);assert.equal(auth.authenticated(new Request(process.env.LIFEOS_APP_URL,{headers:{cookie:'lifeos_session=old-password-cookie'}})),false);assert.throws(()=>auth.checkOrigin(new Request(process.env.LIFEOS_APP_URL,{headers:{origin:'https://evil.test'}})),error=>error.status===403);
 console.log('PASSOU: OAuth com state, nonce e PKCE; apenas duas contas; sessão assinada; expiração; troca de usuário e ausência de acesso por senha.');
}finally{fs.rmSync(root,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
