const assert=require('node:assert/strict'),path=require('path'),fs=require('fs'),swc=require('next/dist/build/swc'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const folder=path.resolve('.habits-test');
for(const dir of ['lib','components']){fs.mkdirSync(path.join(folder,dir),{recursive:true});for(const name of fs.readdirSync(dir)){if(!name.endsWith('.js'))continue;fs.writeFileSync(path.join(folder,dir,name),swc.transformSync(fs.readFileSync(path.join(dir,name),'utf8'),{filename:name,jsc:{parser:{syntax:'ecmascript',jsx:true},transform:{react:{runtime:'automatic'}},target:'es2022'},module:{type:'commonjs'}}).code);}}
try{
 const h=require(path.join(folder,'lib/habits')),today=h.habitToday(),habit={id:'h1',name:'Ler',context:'personal',color:'blue',icon:'book',start:'2026-01-01'};
 assert.equal(h.validHabit(habit),'');assert.ok(h.validHabit({...habit,icon:'unknown'}));assert.ok(h.validHabit({...habit,color:'unknown'}));assert.equal(h.HABIT_COLORS.length,8);assert.equal(h.HABIT_ICONS.length,16);
 const logs=h.toggleHabit([],habit,today);assert.equal(logs.length,1);assert.equal(h.toggleHabit(logs,habit,today).length,0);assert.throws(()=>h.toggleHabit([],habit,'2999-01-01'),/dias/);assert.throws(()=>h.toggleHabit([],habit,'2025-12-31'),/dias/);
 const oldLogs=[{id:'old',habit:habit.id,date:'2026-01-01'}];const history=h.toggleHabit(oldLogs,habit,today);assert.equal(history.length,2);assert.equal(history[0].date,'2026-01-01');
 const summary=h.habitPeriod(habit,[{habit:'h1',date:'2026-01-01'},{habit:'h1',date:'2026-01-02'},{habit:'h1',date:'2026-01-02'}],'2026-01-01','2026-01-31','2026-01-05');assert.deepEqual(summary,{done:2,total:5,percent:40});assert.deepEqual(h.habitPeriod({...habit,start:'2026-01-04'},[],'2026-01-01','2026-01-31','2026-01-05'),{done:0,total:2,percent:0});assert.equal(h.habitPeriod(habit,logs,'2999-01-01','2999-12-31',today).total,0);assert.equal(h.habitMonthDays(2024,2).length,29);assert.equal(h.habitMonthDays(2026,2).length,28);
 const View=require(path.join(folder,'components/HabitsView')).default,html=renderToStaticMarkup(React.createElement(View,{habits:[habit],logs,context:'personal',configured:true}));assert.ok(html.includes('Concluído hoje'));assert.ok(html.includes('habit-card complete'));assert.ok(html.includes('Seu progresso'));assert.ok(html.includes('Ano'));const tomorrow='2999-01-01';assert.equal(logs.filter(p=>p.date===tomorrow).length,0,'Marcações não se repetem automaticamente no dia seguinte');const setup=renderToStaticMarkup(React.createElement(View,{configured:false}));assert.ok(setup.includes('NOTION_HABITS_DATABASE_ID'));
 const savedHooks={useState:React.useState,useEffect:React.useEffect},RealDate=global.Date,realInterval=global.setInterval,realClear=global.clearInterval;let clock='2026-10-05T15:00:00Z',callback,slot=0;const slots=[];
 global.Date=class extends RealDate{constructor(...args){super(...(args.length?args:[clock]));}static now(){return new RealDate(clock).getTime();}};
 React.useState=initial=>{const index=slot++;if(!slots[index])slots[index]={value:typeof initial==='function'?initial():initial};return [slots[index].value,next=>{slots[index].value=typeof next==='function'?next(slots[index].value):next;}];};React.useEffect=effect=>{effect();};global.setInterval=fn=>{callback=fn;return 1;};global.clearInterval=()=>{};global.window={addEventListener(){},removeEventListener(){}};global.document={addEventListener(){},removeEventListener(){}};
 try{slot=0;View({habits:[],logs:[],setHabits(){},context:'personal',configured:true});assert.equal(slots[1].value,'2026-10-05');clock='2026-10-06T15:00:00Z';callback();assert.equal(slots[0].value,'2026-10-06');assert.equal(slots[1].value,'2026-10-06','Hoje acompanha a virada do dia');slot=0;View({habits:[],logs:[],setHabits(){},context:'personal',configured:true});slots[1].value='2026-10-01';clock='2026-10-07T15:00:00Z';callback();assert.equal(slots[1].value,'2026-10-01','Consulta antiga permanece selecionada');}finally{Object.assign(React,savedHooks);global.Date=RealDate;global.setInterval=realInterval;global.clearInterval=realClear;delete global.window;delete global.document;}
 console.log('PASSOU: cores e ícones, marcação/desmarcação por dia, histórico preservado, início e dias futuros, calendário bissexto, progresso e cards concluídos.');
}finally{fs.rmSync(folder,{recursive:true,force:true});}
