const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),swc=require('next/dist/build/swc'),React=require('react');
const folder=path.resolve('.inbox-test');const files=['components/Inbox.js','components/AutoTextarea.js','components/ModalLayer.js','components/LinkText.js','lib/useBackNavigation.js','lib/backNavigation.js','lib/inboxInput.js','lib/nav.js'];
for(const file of files){const dest=path.join(folder,file);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,swc.transformSync(fs.readFileSync(file,'utf8'),{jsc:{parser:{syntax:'ecmascript',jsx:true},transform:{react:{runtime:'automatic'}},target:'es2022'},module:{type:'commonjs'}}).code);}
const saved={useState:React.useState,useRef:React.useRef,useEffect:React.useEffect},oldWindow=global.window;const slots=[];let index=0,mobile=true,added=[];
React.useState=initial=>{const i=index++;if(!(i in slots))slots[i]=initial;return [slots[i],value=>slots[i]=typeof value==='function'?value(slots[i]):value];};React.useRef=value=>({current:value});React.useEffect=()=>{};global.window={matchMedia:()=>({matches:mobile})};
function walk(node,check){if(!node||typeof node!=='object')return null;if(check(node))return node;for(const child of React.Children.toArray(node.props?.children)){const match=walk(child,check);if(match)return match;}return null;}
try{
 const Inbox=require(path.join(folder,'components/Inbox')).default;function render(){index=0;return Inbox({items:[],tabId:'compras',onAdd:text=>added.push(text)});}const input=tree=>walk(tree,node=>node.type?.name==='AutoTextarea');
 let tree=render();input(tree).props.onChange({target:{value:'Mercado\nArroz\nCafé'}});tree=render();let prevented=false;input(tree).props.onKeyDown({key:'Enter',nativeEvent:{isComposing:false},preventDefault:()=>prevented=true});assert.equal(prevented,false);assert.equal(added.length,0);assert.equal(input(tree).props.enterKeyHint,'enter');
 walk(tree,node=>node.type==='button'&&node.props.children==='Adicionar').props.onClick();assert.deepEqual(added,['Mercado\nArroz\nCafé']);tree=render();assert.equal(input(tree).props.value,'');assert.equal(walk(tree,node=>node.type==='button'&&node.props.children==='Adicionar').props.disabled,true);
 input(tree).props.onChange({target:{value:'Rascunho\ncontinuação'}});tree=render();walk(tree,node=>node.type==='button'&&node.props['aria-expanded']===false).props.onClick();tree=render();walk(tree,node=>node.type==='button'&&node.props['aria-expanded']===true).props.onClick();tree=render();assert.equal(input(tree).props.value,'Rascunho\ncontinuação');
 mobile=false;input(tree).props.onKeyDown({key:'Enter',shiftKey:true,nativeEvent:{isComposing:false},preventDefault:()=>{throw Error('Shift+Enter deve inserir linha');}});assert.equal(added.length,1);input(tree).props.onKeyDown({key:'Enter',nativeEvent:{isComposing:false},preventDefault:()=>prevented=true});assert.equal(added.length,2);assert.equal(added[1],'Rascunho\ncontinuação');
 console.log('PASSOU: Inbox mobile aceita quebras de linha e botão Adicionar; desktop mantém atalhos; recolher preserva o texto.');
}finally{Object.assign(React,saved);if(oldWindow===undefined)delete global.window;else global.window=oldWindow;fs.rmSync(folder,{recursive:true,force:true});}
