const assert=require('node:assert/strict'),path=require('path'),fs=require('fs'),swc=require('next/dist/build/swc'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const folder=path.resolve('.media-test');
for(const file of ['lib/entertainment.js','lib/api.js','lib/server/auth.js','lib/server/mediaSearch.js','lib/server/mediaCover.js','components/EntertainmentView.js','components/MediaIcon.js','components/ModalLayer.js']){const dest=path.join(folder,file);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,swc.transformSync(fs.readFileSync(file,'utf8'),{filename:file,jsc:{parser:{syntax:'ecmascript',jsx:true},transform:{react:{runtime:'automatic'}},target:'es2022'},module:{type:'commonjs'}}).code);}
(async()=>{try{
 const media=require(path.join(folder,'lib/entertainment')),search=require(path.join(folder,'lib/server/mediaSearch'));
 const sections=media.DEFAULT_SECTIONS.map((p,i)=>({...p,id:'s'+i})),book={id:'b',name:'Duna',section:'s0',author:'Frank Herbert',status:'planned',rating:0,comment:'Ficção',coverUrl:'',sourceUrl:'',provider:'',attachments:[]};
 const blank={id:'blank',_notionId:'notion-blank',name:'',type:'',icon:'',color:''};let sequence=0;const initialized=media.createMainSections([blank],()=>String(++sequence));assert.equal(initialized.length,4);assert.equal(initialized[0].name,'Leitura');assert.equal(initialized[0]._notionId,'notion-blank');assert.equal(initialized[0].id,'blank');assert.deepEqual(media.createMainSections(initialized,()=>String(++sequence)),initialized);assert.equal(media.createMainSections([sections[2]],()=>String(++sequence)).length,4);assert.ok(media.sectionValidationError(blank).includes('nome'));
 assert.ok(media.validMedia(book));assert.ok(!media.validMedia({...book,rating:6}));assert.ok(!media.validMedia({...book,coverUrl:'javascript:alert(1)'}));assert.ok(media.validMediaSection(sections[0]));assert.ok(!media.validMediaSection({...sections[0],icon:'bad'}));
 assert.equal(media.filterMedia([book],'ficcao','all').length,1);assert.equal(media.filterMedia([book],'','done').length,0);assert.equal(media.mediaLabels('book').done,'Lido');assert.equal(media.mediaLabels('series').done,'Assistida');
 const books=search.normalizeBookResults({docs:[{key:'/works/OL1W',title:'Duna',author_name:['Frank Herbert'],cover_i:123,first_publish_year:1965},{key:'bad',title:'Sem capa'}]});assert.equal(books[0].author,'Frank Herbert');assert.equal(books[0].coverUrl,'https://covers.openlibrary.org/b/id/123-M.jpg');assert.equal(books[1].coverUrl,'');assert.equal(books[1].sourceUrl,'');
 const series=search.normalizeSeriesResults([{show:{id:1,name:'Dark',url:'https://www.tvmaze.com/shows/1/dark',image:{medium:'https://static.tvmaze.com/dark.jpg'},premiered:'2017-12-01'}},{show:{id:2,name:'No image',image:null,url:'javascript:bad'}}]);assert.equal(series[0].name,'Dark');assert.equal(series[0].author,'');assert.equal(series[1].coverUrl,'');assert.equal(series[1].sourceUrl,'');
 let count=0;global.fetch=async(url,options)=>{count++;assert.ok(url.startsWith('https://openlibrary.org/search.json?title=')||url.startsWith('https://api.tvmaze.com/search/shows?q='));assert.ok(options.headers['User-Agent'].startsWith('LifeOS'));return Response.json(url.includes('openlibrary')?{docs:[{title:'Duna',author_name:['Frank Herbert'],cover_i:123}]}:[{show:{id:1,name:'Dark',image:null}}]);};
 const user={id:'test'};assert.equal((await search.searchMedia('book','Duna',user))[0].name,'Duna');await search.searchMedia('book','Duna',user);assert.equal(count,1,'Busca repetida usa cache de metadados');await assert.rejects(()=>search.searchMedia('series','Dark',user),e=>e.status===429);assert.equal((await search.searchMedia('series','Dark',{id:'other'}))[0].name,'Dark');await assert.rejects(()=>search.searchMedia('game','Duna',user),/livros e séries/);
 const View=require(path.join(folder,'components/EntertainmentView')).default,html=renderToStaticMarkup(React.createElement(View,{sections,items:[book,{...book,id:'g',section:'s2',name:'Jogo'}],setEntertainment(){},configured:true}));for(const label of ['Entretenimento','Leitura','Filmes','Jogos','Séries','Quero começar','Em andamento','Concluídos','Marcar como lido','Marcar como jogado','Nova seção'])assert.ok(html.includes(label),label);assert.ok(html.includes('estrela'));assert.ok(html.includes('media-cover'));
 const cover=require(path.join(folder,'lib/server/mediaCover'));
 assert.ok(cover.allowedCoverUrl('https://covers.openlibrary.org/b/id/123-M.jpg'));
 assert.ok(cover.allowedCoverUrl('https://static.tvmaze.com/uploads/images/medium_portrait/2/34.jpg'));
 for(const url of ['http://covers.openlibrary.org/b/id/1-M.jpg','https://127.0.0.1/a','https://covers.openlibrary.org.evil.test/b/id/1-M.jpg','https://static.tvmaze.com/admin','https://user:pass@covers.openlibrary.org/b/id/1-M.jpg'])assert.ok(!cover.allowedCoverUrl(url),url);
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1cAAAAASUVORK5CYII=','base64');
 global.fetch=async(url,options)=>{assert.equal(options.redirect,'manual');return new Response(png,{headers:{'content-type':'image/png'}});};
 const image=await cover.downloadMediaCover('https://covers.openlibrary.org/b/id/123-M.jpg','Duna');assert.equal(image.type,'image/png');assert.equal(image.name,'Duna.png');assert.equal(image.size,png.length);
 global.fetch=async()=>new Response('html');await assert.rejects(()=>cover.downloadMediaCover('https://covers.openlibrary.org/b/id/123-M.jpg'),/imagem compatível/);
 global.fetch=async()=>new Response(null,{status:302,headers:{location:'https://127.0.0.1/private'}});await assert.rejects(()=>cover.downloadMediaCover('https://covers.openlibrary.org/b/id/123-M.jpg'),/não suportado/);
 global.fetch=async()=>new Response(png,{headers:{'content-length':String(5*1024*1024)}});await assert.rejects(()=>cover.downloadMediaCover('https://covers.openlibrary.org/b/id/123-M.jpg'),e=>e.status===413);
 global.fetch=async()=>new Response(new Uint8Array(4*1024*1024+1));await assert.rejects(()=>cover.downloadMediaCover('https://covers.openlibrary.org/b/id/123-M.jpg'),e=>e.status===413);
 console.log('PASSOU: entretenimento, filtros, estrelas, ícones, importação de livros/séries, URLs seguras, cache e limite de busca.');
 }finally{fs.rmSync(folder,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
