// Executes the production Redis Lua scripts in an isolated Lua VM; no real service is contacted.
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),swc=require('next/dist/build/swc');
const {lua,lauxlib,lualib,to_luastring,to_jsstring}=require('fengari');
const root=path.resolve('.qr-test');
for(const name of ['auth','qrAuth','coordination','maintenance']){const target=path.join(root,'lib/server',name+'.js');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,swc.transformSync(fs.readFileSync('lib/server/'+name+'.js','utf8'),{jsc:{parser:{syntax:'ecmascript'},target:'es2022'},module:{type:'commonjs'}}).code);}
for(const name of ['auth/qr','session']){const target=path.join(root,'app/api',name,'route.js');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,swc.transformSync(fs.readFileSync('app/api/'+name+'/route.js','utf8'),{jsc:{parser:{syntax:'ecmascript'},target:'es2022'},module:{type:'commonjs'}}).code);}
process.env.NOTION_TOKEN='test';process.env.GOOGLE_CLIENT_ID='test';process.env.GOOGLE_CLIENT_SECRET='test';process.env.LIFEOS_SESSION_SECRET='x'.repeat(48);process.env.LIFEOS_APP_URL='https://lifeos.test';process.env.LIFEOS_ALLOWED_GOOGLE_EMAILS='periclesbernardes@gmail.com,leticiacost3@gmail.com';process.env.LIFEOS_LEGACY_OWNER_EMAIL='periclesbernardes@gmail.com';process.env.UPSTASH_REDIS_REST_URL='https://redis.test';process.env.UPSTASH_REDIS_REST_TOKEN='write-test';
let now=Date.now();const originalNow=Date.now,originalFetch=global.fetch;Date.now=()=>now;const store=new Map(),sets=new Map(),ttls=new Map();
function redis(args){const [command,key,...rest]=args.map(String);if(ttls.has(key)&&ttls.get(key)<=now){store.delete(key);sets.delete(key);ttls.delete(key);}switch(command.toUpperCase()){
 case 'GET':return store.get(key)||null;
 case 'SET':store.set(key,rest[0]);{const px=rest.indexOf('PX');if(px>=0)ttls.set(key,now+Number(rest[px+1]));}return 'OK';
 case 'DEL':store.delete(key);sets.delete(key);ttls.delete(key);return 1;
 case 'INCR':{const n=Number(store.get(key)||0)+1;store.set(key,String(n));return n;}
 case 'EXPIRE':ttls.set(key,now+Number(rest[0])*1000);return 1;
 case 'SADD':{const values=sets.get(key)||new Set();rest.forEach(v=>values.add(v));sets.set(key,values);return 1;}
 case 'SREM':rest.forEach(v=>sets.get(key)?.delete(v));return 1;
 case 'SMEMBERS':return [...(sets.get(key)||[])];
 default:throw Error('Unsupported Redis command '+command);
}}
function push(L,value){if(value===null||value===undefined)lua.lua_pushnil(L);else if(typeof value==='string')lua.lua_pushstring(L,to_luastring(value));else if(typeof value==='number')lua.lua_pushnumber(L,value);else if(typeof value==='boolean')lua.lua_pushboolean(L,value);else{lua.lua_newtable(L);for(const [k,v] of Object.entries(value)){push(L,v);if(Array.isArray(value))lua.lua_rawseti(L,-2,Number(k)+1);else lua.lua_setfield(L,-2,to_luastring(k));}}}
function read(L,index){const type=lua.lua_type(L,index);if(type===lua.LUA_TNIL)return null;if(type===lua.LUA_TSTRING)return to_jsstring(lua.lua_tostring(L,index));if(type===lua.LUA_TNUMBER)return lua.lua_tonumber(L,index);if(type===lua.LUA_TBOOLEAN)return lua.lua_toboolean(L,index);if(type===lua.LUA_TTABLE){const result={},absolute=lua.lua_absindex(L,index);lua.lua_pushnil(L);while(lua.lua_next(L,absolute)){result[read(L,-2)]=read(L,-1);lua.lua_pop(L,1);}return result;}throw Error('Unsupported Lua type');}
function evalLua(script,keys,args){const L=lauxlib.luaL_newstate();lualib.luaL_openlibs(L);push(L,keys);lua.lua_setglobal(L,to_luastring('KEYS'));push(L,args.map(String));lua.lua_setglobal(L,to_luastring('ARGV'));lua.lua_newtable(L);lua.lua_pushjsfunction(L,()=>{const values=[];for(let i=1;i<=lua.lua_gettop(L);i++)values.push(read(L,i));push(L,redis(values));return 1;});lua.lua_setfield(L,-2,to_luastring('call'));lua.lua_setglobal(L,to_luastring('redis'));lua.lua_newtable(L);lua.lua_pushjsfunction(L,()=>{push(L,JSON.parse(read(L,1)));return 1;});lua.lua_setfield(L,-2,to_luastring('decode'));lua.lua_pushjsfunction(L,()=>{push(L,JSON.stringify(read(L,1)));return 1;});lua.lua_setfield(L,-2,to_luastring('encode'));lua.lua_setglobal(L,to_luastring('cjson'));if(lauxlib.luaL_dostring(L,to_luastring(script))!==lua.LUA_OK)throw Error(read(L,-1));const result=read(L,-1);lua.lua_close(L);return result;}
global.fetch=async(url,options)=>{assert.equal(url,'https://redis.test');const cmd=JSON.parse(options.body);let result;if(cmd[0]==='EVAL'){const n=Number(cmd[2]);result=evalLua(cmd[1],cmd.slice(3,3+n),cmd.slice(3+n));}else result=redis(cmd);return Response.json({result});};
const auth=require(path.join(root,'lib/server/auth')),qr=require(path.join(root,'lib/server/qrAuth')),route=require(path.join(root,'app/api/auth/qr/route')),sessions=require(path.join(root,'app/api/session/route'));
const principal={id:'google:p',name:'Péricles',email:'periclesbernardes@gmail.com'},other={id:'google:l',name:'Letícia',email:'leticiacost3@gmail.com'};
const request=(cookie='',input,headers={})=>new Request('https://lifeos.test/api/auth/qr',{method:input?'POST':'GET',headers:{cookie,origin:'https://lifeos.test','user-agent':'Test desktop',...headers},...(input?{body:JSON.stringify(input)}:{})});
const dataOf=start=>{const url=new URL(start.url),params=new URLSearchParams(url.hash.slice(1));return {id:params.get('id'),token:params.get('token')};};
(async()=>{try{
 const googleCookie=auth.sessionCookie(principal).split(';')[0];const googleRequest=request(googleCookie);assert.equal((await auth.authorizeLive(googleRequest)).email,principal.email);
 const a=await qr.startQr(request()),cookie=a.cookie.split(';')[0],credentials=dataOf(a);assert.equal(a.code.length,6);assert.equal(a.expiresAt,now+120000);assert.ok(a.cookie.includes('HttpOnly'));assert.ok(a.cookie.includes('SameSite=Strict'));assert.equal(new URL(a.url).search,'');assert.equal((await qr.qrDetails(principal,credentials.id,credentials.token)).code,a.code);
 await assert.rejects(qr.redeemQr(request(cookie)),e=>e.status===401);await assert.rejects(qr.qrDetails(principal,credentials.id,'0'.repeat(64)),e=>e.status===410);
 const unauthorized=await route.POST(request('',{action:'approve',...credentials,email:principal.email}));assert.equal(unauthorized.status,401);
 const changed=await route.POST(request(googleCookie,{action:'approve',...credentials},{'X-LifeOS-User':other.id}));assert.equal(changed.status,401,'Account switch during approval must be rejected');
 const stranger=auth.sessionCookie({...principal,email:'stranger@test.com'}).split(';')[0];assert.equal((await route.POST(request(stranger,{action:'approve',...credentials}))).status,401);
 await qr.approveQr(principal,credentials.id,credentials.token,true);assert.equal((await qr.pollQr(request(cookie))).status,'approved');await assert.rejects(qr.approveQr(other,credentials.id,credentials.token,true),e=>e.status===409);
 const second=await qr.startQr(request());await assert.rejects(qr.redeemQr(request(second.cookie.split(';')[0])),e=>e.status===401);
 const outcomes=await Promise.allSettled([qr.redeemQr(request(cookie)),qr.redeemQr(request(cookie))]);assert.equal(outcomes.filter(p=>p.status==='fulfilled').length,1,'Atomic one-time redemption');const redeemed=outcomes.find(p=>p.status==='fulfilled').value;const tempCookie=redeemed.cookie.split(';')[0],temp=auth.readSession(request(tempCookie));assert.equal(temp.temporary,true);assert.equal(temp.draftKey,null);assert.ok(!redeemed.cookie.includes('Max-Age'),'Nonpersistent desktop cookie');assert.equal((await auth.authorizeLive(request(tempCookie))).id,principal.id);assert.equal((await qr.listQrSessions(principal)).length,1);assert.equal((await qr.listQrSessions(other)).length,0);await assert.rejects(qr.listQrSessions(temp),e=>e.status===403);await assert.rejects(qr.qrDetails(temp,credentials.id,credentials.token),e=>e.status===403);await assert.rejects(qr.revokeQrSession(other,temp.sessionId),e=>e.status===403);
 await qr.revokeQrSession(principal,temp.sessionId);assert.equal(await auth.liveSession(request(tempCookie)),null);await assert.rejects(auth.authorizeLive(request(tempCookie)),e=>e.status===401);
 const denied=await qr.startQr(request()),dc=dataOf(denied);await qr.approveQr(other,dc.id,dc.token,false);assert.equal((await qr.pollQr(request(denied.cookie.split(';')[0]))).status,'denied');await assert.rejects(qr.redeemQr(request(denied.cookie.split(';')[0])),e=>e.status===401);
 const idle=await qr.startQr(request()),ic=dataOf(idle);await qr.approveQr(other,ic.id,ic.token,true);const idleSession=await qr.redeemQr(request(idle.cookie.split(';')[0]));const idleCookie=idleSession.cookie.split(';')[0];now+=600001;assert.equal(await auth.liveSession(request(idleCookie)),null,'Idle expiration enforced server-side');
 const expire=await qr.startQr(request()),ec=dataOf(expire);now+=120001;await assert.rejects(qr.qrDetails(principal,ec.id,ec.token),e=>e.status===410);
 const absolute=await qr.startQr(request()),ac=dataOf(absolute);await qr.approveQr(principal,ac.id,ac.token,true);const abs=await qr.redeemQr(request(absolute.cookie.split(';')[0]));for(let i=0;i<5;i++){now+=300000;assert.ok(await auth.liveSession(request(abs.cookie.split(';')[0])));}now+=300001;assert.equal(await auth.liveSession(request(abs.cookie.split(';')[0])),null,'Absolute expiration cannot be extended');
 const apiStart=await route.POST(request('',{action:'start'}));assert.equal(apiStart.status,200);const result=await apiStart.json();assert.ok(result.image.startsWith('data:image/png;base64,'));assert.equal(result.url,undefined,'Approval token not returned apart from QR pixels');assert.equal(result.token,undefined);assert.equal(apiStart.headers.get('cache-control'),'no-store');
 assert.equal((await route.POST(request('',{action:'start'},{origin:'https://evil.test'}))).status,403);
 const loggedOut=await sessions.DELETE(request(tempCookie));assert.equal(loggedOut.status,200);assert.ok(loggedOut.headers.get('set-cookie').includes('Max-Age=0'));
 for(let i=0;i<31;i++)await route.POST(request('',{action:'start'},{'x-vercel-forwarded-for':'abusive-test'}));assert.equal((await route.POST(request('',{action:'start'},{'x-vercel-forwarded-for':'abusive-test'}))).status,429);
 console.log('PASSOU: QR local, duas contas Google, confirmação explícita, vínculo ao navegador, Lua real de uso único/concorrência, recusa, expiração absoluta e por inatividade, revogação isolada, sessão sem chave de rascunho e origem protegida.');
}finally{Date.now=originalNow;global.fetch=originalFetch;fs.rmSync(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
