const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),swc=require('next/dist/build/swc');
const root=path.resolve('.recados-test');fs.mkdirSync(path.join(root,'lib/server'),{recursive:true});
for(const name of ['lib/recados.js','lib/server/recados.js','lib/server/auth.js','lib/server/notion.js','lib/server/coordination.js'])fs.writeFileSync(path.join(root,name),swc.transformSync(fs.readFileSync(name,'utf8'),{jsc:{parser:{syntax:'ecmascript'},target:'es2022'},module:{type:'commonjs'}}).code);
process.env.LIFEOS_SESSION_SECRET='x'.repeat(48);process.env.LIFEOS_ALLOWED_GOOGLE_EMAILS='periclesbernardes@gmail.com,leticiacost3@gmail.com';process.env.NOTION_RECADOS_DATABASE_ID='bank';
const auth=require(path.join(root,'lib/server/auth')),dates=require(path.join(root,'lib/recados'));const a={id:'google:a',email:'periclesbernardes@gmail.com'},b={id:'google:b',email:'leticiacost3@gmail.com'};
const rows=[],source={id:'source',databaseId:'bank',fields:{date:{name:'Data'}},tracking:{name:'LifeOS ID'}};let writes=0,tail=Promise.resolve(),lastFilter;
require.cache[path.join(root,'lib/server/coordination.js')]={exports:{withWriteLock:fn=>{const run=tail.then(()=>fn(async()=>{}));tail=run.catch(()=>{});return run;}}};
require.cache[path.join(root,'lib/server/notion.js')]={exports:{schema:async()=>source,plain:r=>r?.map(x=>x.text.content).join('')||'',decode:(kind,row)=>({...row.properties,id:row.id}),encode:(kind,value,src,keys)=>keys?Object.fromEntries(keys.map(k=>[k,value[k]])):{...value},notion:async(url,options={})=>{if(url.includes('/query')){lastFilter=options.body.filter;return {results:rows,has_more:false};}if(url==='/pages'){writes++;const row={id:'12345678-1234-1234-1234-123456789012',parent:{data_source_id:'source'},properties:options.body.properties};rows.push(row);return row;}const row=rows.find(r=>url==='/pages/'+r.id);assert.ok(row);if(options.method==='PATCH'){writes++;Object.assign(row.properties,options.body.properties);}return row;}}};
const api=require(path.join(root,'lib/server/recados'));
(async()=>{try{
 assert.equal(dates.recadoToday(new Date('2026-10-06T02:59:00Z')),'2026-10-05');assert.equal(dates.recadoToday(new Date('2026-10-06T03:00:00Z')),'2026-10-06');assert.deepEqual(dates.recadoMonthBounds('2026-12'),['2026-12-01','2027-01-01']);
 const today=dates.recadoToday();await assert.rejects(()=>api.sendRecado(a,{date:'2000-01-01',text:'Oi'}),e=>e.status===409);await assert.rejects(()=>api.sendRecado(a,{date:today,text:' '}));
 const proof=auth.seal({user:b.id,uploadId:'upload',kind:'recados-image',exp:Date.now()+10000});await assert.rejects(()=>api.sendRecado(a,{date:today,text:'Oi',attachment:{uploadId:'upload',uploadProof:proof}}),e=>e.status===403);
 const input={date:today,title:'Para você',text:'Bom dia ❤️',sender:b.email,recipient:a.email};const [first,retry]=await Promise.all([api.sendRecado(a,input),api.sendRecado(a,input)]);assert.equal(writes,1);assert.equal(first.id,retry.id);assert.equal(first.sender,a.email);assert.equal(first.recipient,b.email);assert.equal(first.read,false);assert.equal(first.name,'Para você');await assert.rejects(()=>api.sendRecado(a,{...input,title:'Outro título'}),e=>e.status===409);
 await assert.rejects(()=>api.sendRecado(a,{date:today,text:'Outro texto'}),e=>e.status===409);await assert.rejects(()=>api.markRecadoRead(a,first.id),e=>e.status===403);const read=await api.markRecadoRead(b,first.id);assert.equal(read.read,true);assert.ok(read.readAt);assert.equal(read.text,first.text);const again=await api.markRecadoRead(b,first.id);assert.equal(again.readAt,read.readAt);assert.equal(writes,2);
 rows.push({id:'other',parent:{data_source_id:'source'},properties:{sender:'stranger@example.com',recipient:b.email,date:today,text:'Private'}});const list=await api.listRecados(b,today.slice(0,7));assert.equal(list.items.length,1);assert.equal(lastFilter.and[0].date.on_or_after,today.slice(0,7)+'-01');await assert.rejects(()=>api.listRecados(a,'2026-99'));delete process.env.NOTION_RECADOS_DATABASE_ID;assert.equal((await api.listRecados(a)).configured,false);
 console.log('PASSOU: dia de Brasília, virada do ano, remetente protegido, imagem de outro usuário rejeitada, envio concorrente sem duplicação, limite diário e leitura exclusiva pelo destinatário com horário preservado.');
}finally{fs.rmSync(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
