const assert=require('node:assert/strict'),path=require('path'),fs=require('fs'),swc=require('next/dist/build/swc'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const folder=path.resolve('.shopping-test');
for(const dir of ['lib','components']){fs.mkdirSync(path.join(folder,dir),{recursive:true});for(const name of fs.readdirSync(dir)){if(!name.endsWith('.js'))continue;fs.writeFileSync(path.join(folder,dir,name),swc.transformSync(fs.readFileSync(path.join(dir,name),'utf8'),{filename:name,jsc:{parser:{syntax:'ecmascript',jsx:true},transform:{react:{runtime:'automatic'}},target:'es2022'},module:{type:'commonjs'}}).code);}}
try{
 const {shoppingFromInbox,validateShopping,decodeShoppingItems,moveShoppingItem,normalizeShoppingOrder}=require(path.join(folder,'lib/shopping'));
 const created=shoppingFromInbox([],'Mercado\r\nLeite\r\n\r\nOvos','personal');assert.deepEqual(created.lists[0].items.map(p=>p.text),['Leite','Ovos']);const merged=shoppingFromInbox(created.lists,' mERCADO \nBananas\nCafé','personal');assert.equal(merged.id,created.id);assert.equal(merged.lists.length,1);assert.deepEqual(merged.lists[0].items.map(p=>p.text),['Bananas','Café','Leite','Ovos']);const separate=shoppingFromInbox(merged.lists,'Mercado\nPapel','work');assert.equal(separate.lists.length,2);assert.equal(separate.lists[1].context,'work');assert.equal(created.lists[0].items.length,2,'Conversão não modifica a base');
 assert.throws(()=>shoppingFromInbox([],'Só título','personal'),/pelo menos um item/);assert.throws(()=>shoppingFromInbox([],'Mercado\n'+'X'.repeat(501),'personal'),/500/);assert.throws(()=>shoppingFromInbox([created.lists[0],{...created.lists[0],id:'dup'}],'mercado\nOvos','personal'),/mais de uma/);assert.ok(validateShopping({...created.lists[0],context:'all'}));assert.deepEqual(decodeShoppingItems(JSON.stringify(merged.lists[0].items)),merged.lists[0].items);assert.deepEqual(decodeShoppingItems('Arroz\nCafé'),decodeShoppingItems('Arroz\nCafé'));assert.throws(()=>decodeShoppingItems('[bad'),/inválido/);
 const {default:View}=require(path.join(folder,'components/ShoppingView'));const html=renderToStaticMarkup(React.createElement(View,{lists:merged.lists,selected:merged.id,configured:true,context:'personal',setLists:()=>{}}));assert.ok(html.includes('type="checkbox"'));assert.ok(html.includes('Finalizar e excluir lista'));assert.ok(!html.includes('Histórico'));const cards=renderToStaticMarkup(React.createElement(View,{lists:separate.lists,selected:null,configured:true,context:'personal',setLists:()=>{}}));assert.ok(!cards.includes('Trabalho'));assert.ok(cards.includes('Pessoal'));assert.ok(cards.includes('shopping-card'));assert.ok(!cards.includes('Abrir lista'));assert.ok(cards.includes('Reordenar lista'));assert.ok(html.includes('Voltar às listas'));assert.ok(html.includes('Reordenar'));const Icon=require(path.join(folder,'components/TabIcon')).default;assert.ok(renderToStaticMarkup(React.createElement(Icon,{id:'compras'})).includes('width="15"'));
 const items=merged.lists[0].items,down=moveShoppingItem(items,items[0].id,items[3].id);assert.deepEqual(down.map(p=>p.text),['Café','Leite','Ovos','Bananas']);assert.deepEqual(moveShoppingItem(down,down[3].id,down[0].id),items);assert.equal(moveShoppingItem(items,'missing',items[0].id),items);assert.equal(items[0].text,'Bananas');const appended=shoppingFromInbox([{...merged.lists[0],items:down}],'Mercado\nArroz','personal');assert.deepEqual(appended.lists[0].items.map(p=>p.text),['Arroz','Café','Leite','Ovos','Bananas']);
 assert.deepEqual(normalizeShoppingOrder(['c','a','a','missing'],['a','b','c']),['c','a','b']);
 const originals={useState:React.useState,useRef:React.useRef};const slots=[];let slot=0;
 React.useRef=value=>{const index=slot++;return slots[index]||(slots[index]={current:value});};React.useState=value=>{const index=slot++;if(!slots[index])slots[index]={value};return [slots[index].value,update=>{slots[index].value=typeof update==='function'?update(slots[index].value):update;}];};
 try{
 const dragHook=require(path.join(folder,'components/useShoppingDrag')).default;let moved=[],target='b';global.document={elementFromPoint:()=>({closest:()=>({getAttribute:()=>target})})};global.window={innerHeight:900,scrollBy(){}};
 function render(){slot=0;return dragHook('data-shopping-item',(from,to)=>moved.push([from,to]));}
 const handle={setPointerCapture(){}};const event=(pointerType,x,y)=>({pointerType,button:0,pointerId:1,clientX:x,clientY:y,currentTarget:handle,preventDefault(){}});
 for(const type of ['mouse','touch','pen']){const hook=render(),handlers=hook.bind('a');handlers.onPointerDown(event(type,10,100));handlers.onPointerMove(event(type,10,150));assert.equal(render().dragging,'a');handlers.onPointerUp(event(type,10,150));assert.deepEqual(moved.at(-1),['a','b']);assert.equal(render().dragging,null);}
 const hook=render(),handlers=hook.bind('a'),count=moved.length;handlers.onPointerDown(event('mouse',10,100));handlers.onPointerUp(event('mouse',10,100));assert.equal(moved.length,count,'Clique sem movimento não reordena');handlers.onPointerDown(event('touch',10,100));handlers.onPointerMove(event('touch',10,150));handlers.onPointerCancel();assert.equal(moved.length,count,'Cancelar não reordena');
 }finally{Object.assign(React,originals);delete global.document;delete global.window;}
 console.log('PASSOU: criação e acréscimo pelo Inbox, nome sem distinção de maiúsculas, ordem dos itens, contextos separados, limites, persistência e ícones compactos.');
}finally{fs.rmSync(folder,{recursive:true,force:true});}
