const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),swc=require('next/dist/build/swc'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const root=path.resolve('.wellness-test');
for(const dir of ['lib','components']){fs.mkdirSync(path.join(root,dir),{recursive:true});for(const name of fs.readdirSync(dir)){if(!name.endsWith('.js'))continue;fs.writeFileSync(path.join(root,dir,name),swc.transformSync(fs.readFileSync(path.join(dir,name),'utf8'),{filename:name,jsc:{parser:{syntax:'ecmascript',jsx:true},transform:{react:{runtime:'automatic'}},target:'es2022'},module:{type:'commonjs'}}).code);}}
try{
 const {validateWellness,upsertWellness,latestMeasurements,dailyPressure,maskPressure,parsePressure,aspectFilled,updateCycleChoice}=require(path.join(root,'lib/wellness')),day=require(path.join(root,'lib/habits')).habitToday();
 const pressure={id:'p1',name:'Pressão',date:day,type:'pressure',data:{time:'09:00',systolic:124,diastolic:76,bpm:62}};
 assert.equal(validateWellness(pressure),'');assert.ok(validateWellness({...pressure,data:{...pressure.data,bpm:0}}));assert.ok(validateWellness({...pressure,date:'2999-01-01'}));assert.ok(validateWellness({...pressure,date:'2026-02-30'}));
 assert.equal(validateWellness({...pressure,data:{systolic:124,diastolic:76,bpm:62}}),'','Horário não é obrigatório');
 assert.equal(maskPressure('12476'),'124/76');assert.equal(maskPressure('124/100'),'124/10');assert.equal(maskPressure('98/65'),'98/65');assert.deepEqual(parsePressure('124/76'),{systolic:124,diastolic:76});assert.equal(parsePressure('124/'),null);assert.equal(parsePressure('124/100'),null);assert.equal(maskPressure('123456'),'123/45');
 const another={...pressure,id:'p2',data:{systolic:126,diastolic:78,bpm:66}};let avg=dailyPressure([pressure,another]);assert.equal(avg[0].count,2);assert.deepEqual(avg[0].data,{systolic:125,diastolic:77,bpm:64});assert.equal(dailyPressure([pressure])[0].data.systolic,124);assert.equal(dailyPressure([{...another,date:'2026-01-01'},pressure]).length,2);assert.deepEqual(dailyPressure([pressure,{...another,data:{systolic:125,diastolic:77,bpm:63}}])[0].data,{systolic:125,diastolic:77,bpm:63});assert.equal(pressure.data.systolic,124,'Média não modifica registros originais');
 const body={...pressure,type:'body',data:{weight:136,fat:null}};assert.equal(validateWellness(body),'');assert.ok(validateWellness({...body,data:{weight:136,fat:101}}));assert.equal(validateWellness({...body,data:{weight:136,fat:28.4}}),'');
 const cycle={...pressure,type:'cycle',data:{subject:'leticiacost3@gmail.com',menstruation:'Sim',flow:'Leve',cramps:'Leve'}};assert.equal(validateWellness(cycle,'cycle'),'');assert.ok(validateWellness({...cycle,data:{...cycle.data,subject:'periclesbernardes@gmail.com'}},'cycle'));assert.equal(validateWellness({...cycle,data:{subject:'leticiacost3@gmail.com',menstruation:'Sim',flow:'',cramps:''}},'cycle'),'');assert.ok(validateWellness({...cycle,data:{...cycle.data,flow:0}},'cycle'));const withNotes={...cycle,data:{...cycle.data,notes:'Preservar'}};assert.equal(updateCycleChoice([withNotes],day,'flow','Leve')[0].data.notes,'Preservar');
 assert.equal(upsertWellness([pressure],{...pressure,data:{...pressure.data,bpm:64}}).length,1);assert.equal(latestMeasurements([pressure,{...pressure,id:'p2',data:{...pressure.data,time:'10:00'}}],'pressure')[0].id,'p2');
 const {measurementScales,chartScale}=require(path.join(root,'lib/measurementChart'));const scales=measurementScales([pressure,another],'pressure');assert.ok(scales.left.min<=76&&scales.left.max>=126);assert.ok(scales.right.min<=62&&scales.right.max>=66);assert.ok(scales.left.max-scales.left.min<150);assert.ok(chartScale([136,136],{minimumSpan:2}).max>136);assert.equal(chartScale([null,undefined]),null);const bs=measurementScales([body],'body');assert.equal(bs.right,null);assert.ok(bs.left.min<body.data.weight);const fatScale=chartScale([99.8,100],{minimumSpan:2,ceiling:100});assert.equal(fatScale.max,100);assert.ok(fatScale.min<99.8);
 const Chart=require(path.join(root,'components/MeasurementChart')).default;const graph=renderToStaticMarkup(React.createElement(Chart,{type:'pressure',records:[pressure,another]}));assert.equal((graph.match(/<svg/g)||[]).length,1);assert.ok(graph.includes('direita'));assert.ok(graph.includes('Diastólica'));
 const View=require(path.join(root,'components/WellnessView')).default;
 const html=renderToStaticMarkup(React.createElement(View,{remote:{user:{id:'test'},wellness:[pressure,body],cycle:[],setWellness(){},habits:[],habitLogs:[],habitsConfigured:true,wellnessConfigured:true,cycleConfigured:true}}));
 for(const label of ['Bem-estar','Ciclo da Letícia','Pressão e BPM','Peso e gordura','Seu progresso','Mostrar hábitos encerrados','Atualize quando houver uma nova medição'])assert.ok(html.includes(label),label);
 assert.ok(html.includes('well-choices'));assert.ok(html.includes('Média de 1 medição'));assert.ok(!html.includes('Preencher / editar'));
 assert.ok(html.includes('well-petal'));assert.ok(html.includes('habit-matrix'));
 // Inline choices write only the selected aspect and never open a modal.
 const oldState=React.useState,oldRef=React.useRef,oldEffect=React.useEffect;
 let index=0;const slots=[];React.useState=initial=>{const i=index++;if(!slots[i])slots[i]={value:typeof initial==='function'?initial():initial};return [slots[i].value,value=>slots[i].value=typeof value==='function'?value(slots[i].value):value];};
 let state={wellness:[],cycle:[]};const props={remote:{user:{id:'A'},...state,setWellness:fn=>{state=fn(state);},habitsConfigured:true,wellnessConfigured:true,cycleConfigured:true}};
 const render=()=>{index=0;return View({remote:{...props.remote,...state}});};
 const buttons=(node,out=[])=>{if(Array.isArray(node))node.forEach(p=>buttons(p,out));else if(node?.props){if(node.type==='button')out.push(node);buttons(node.props.children,out);}return out;};
 try{let tree=render();buttons(tree).find(p=>p.props.className==='well-choice'&&p.props.children[0]==='Boa').props.onClick();assert.equal(state.wellness[0].data.sono,'Boa');tree=render();assert.ok(buttons(tree).find(p=>p.props.className?.includes('well-petal recorded')||p.props.className?.includes('selected recorded')));assert.equal(slots[2].value,null,'Escolha lateral não abre formulário');buttons(tree).find(p=>p.props.title==='8h').props.onClick();assert.equal(state.wellness[0].data.sleepDuration,'8');assert.equal(state.wellness[0].data.sono,'Boa');assert.equal(aspectFilled({sleepDuration:'9+'},'sono'),true);assert.ok(validateWellness({...pressure,type:'day',data:{sleepDuration:'12'}}));assert.equal(validateWellness({...pressure,type:'day',data:{sleepDuration:'6-',painIntensity:'Leve'}}),'');tree=render();buttons(tree).find(p=>p.props.className==='ghost well-clear').props.onClick();assert.equal(state.wellness[0].data.sono,'');assert.equal(state.wellness.length,1,'Reutiliza o registro do dia');tree=render();buttons(tree).find(p=>p.props.className==='cycle-choice'&&p.props.children==='Sim').props.onClick();assert.equal(state.cycle.length,1);assert.equal(state.cycle[0].data.menstruation,'Sim');assert.equal(state.cycle[0].data.cramps,'','Escolha não inventa resposta para os outros campos');assert.equal(slots[2].value,null,'Ciclo preenchido sem abrir painel');tree=render();buttons(tree).find(p=>p.props.className==='cycle-choice'&&p.props.children==='Não').props.onClick();assert.equal(state.cycle[0].data.flow,'—');assert.equal(state.cycle.length,1);}finally{React.useState=oldState;React.useRef=oldRef;React.useEffect=oldEffect;}
 // A selected graph point opens its exact source, or only the day's measurements for averages.
 {const old=React.useState;let cursor=0;const slots=[];React.useState=initial=>{const i=cursor++;if(!slots[i])slots[i]={value:typeof initial==='function'?initial():initial};return [slots[i].value,v=>slots[i].value=typeof v==='function'?v(slots[i].value):v];};
 const source=[pressure,body];const render=()=>{cursor=0;return View({remote:{...props.remote,wellness:source,cycle:[]}});};const nodes=(n,out=[])=>{if(Array.isArray(n))n.forEach(v=>nodes(v,out));else if(n?.props){out.push(n);nodes(n.props.children,out);}return out;};try{
 let tree=render();nodes(tree).find(n=>n.type===Chart&&n.props.type==='body').props.onSelect(body);tree=render();buttons(tree).find(n=>n.props.children==='Editar registro').props.onClick();assert.equal(slots[2].value.id,body.id);
 slots[2].value=null;tree=render();nodes(tree).find(n=>n.type===Chart&&n.props.type==='pressure').props.onSelect(dailyPressure(source)[0]);tree=render();buttons(tree).filter(n=>n.props.children==='Editar registro')[0].props.onClick();assert.equal(slots[2].value.id,pressure.id);
 source.push(another);slots[2].value=null;tree=render();nodes(tree).find(n=>n.type===Chart&&n.props.type==='pressure').props.onSelect(dailyPressure(source)[0]);tree=render();buttons(tree).filter(n=>n.props.children==='Editar registro')[0].props.onClick();assert.equal(slots[2].value,null);assert.equal(slots[4].value,'pressure');assert.equal(slots[8].value,day);
 }finally{React.useState=old;}}
 // Both measurement forms save in place; blank/invalid forms never create records.
 const Inline=require(path.join(root,'components/InlineMeasurement')).default;
 {const savedState=React.useState,savedEffect=React.useEffect;let slot=0;const stateSlots=[];React.useState=initial=>{const i=slot++;if(!stateSlots[i])stateSlots[i]={value:initial};return [stateSlots[i].value,v=>stateSlots[i].value=typeof v==='function'?v(stateSlots[i].value):v];};React.useEffect=()=>{};
 let saved={wellness:[],cycle:[]};let type='pressure';const renderForm=()=>{slot=0;return Inline({type,date:day,configured:true,setWellness:fn=>saved=fn(saved)});};
 const inputs=(node,result=[])=>{if(Array.isArray(node))node.forEach(n=>inputs(n,result));else if(node?.props){if(node.type==='input')result.push(node);inputs(node.props.children,result);}return result;};
 try{let form=renderForm();form.props.onSubmit({preventDefault(){}});assert.equal(saved.wellness.length,0);inputs(form).find(n=>n.props['aria-label']==='Pressão na tela').props.onChange({target:{value:'12476'}});inputs(form).find(n=>n.props['aria-label']==='BPM na tela').props.onChange({target:{value:'62'}});form=renderForm();form.props.onSubmit({preventDefault(){}});assert.equal(saved.wellness.length,1);assert.equal(saved.wellness[0].data.systolic,124);assert.equal(saved.wellness[0].data.time,undefined);assert.equal(stateSlots[1].value,'');
 type='body';stateSlots.length=0;form=renderForm();inputs(form).find(n=>n.props['aria-label']==='Peso na tela').props.onChange({target:{value:'136,2'}});form=renderForm();form.props.onSubmit({preventDefault(){}});assert.equal(saved.wellness[1].data.weight,136.2);assert.equal(saved.wellness[1].data.fat,null);assert.ok(!renderToStaticMarkup(React.createElement(Inline,{type,date:day,configured:true,setWellness(){}})).includes('role="dialog"'));
 }finally{React.useState=savedState;React.useEffect=savedEffect;}}
 const {ASPECTS,painLocations,togglePainLocation,deletePetalDay}=require(path.join(root,'lib/wellness'));
 assert.equal(ASPECTS.length,9);for(const key of ['energy','stress'])assert.deepEqual(ASPECTS.find(a=>a[0]===key)[4],[1,2,3,4,5]);
 let pain=togglePainLocation({dores:'Cabeça',sono:'Boa'},'Costas');assert.deepEqual(painLocations(pain),['Cabeça','Costas']);pain=togglePainLocation(pain,'Cabeça');assert.deepEqual(painLocations(pain),['Costas']);assert.equal(pain.sono,'Boa');
 assert.equal(validateWellness({...pressure,type:'day',data:pain}),'');assert.ok(validateWellness({...pressure,type:'day',data:{painLocations:['Cabeça','Cabeça']}}));assert.ok(validateWellness({...pressure,type:'day',data:{painLocations:['Inválida']}}));assert.equal(aspectFilled({water:0},'water'),true);assert.equal(aspectFilled({painLocations:[]},'dores'),false);
 const daily={...pressure,id:'daily',type:'day',data:{}},otherDay={...daily,id:'older',date:'2026-01-01'};assert.deepEqual(deletePetalDay([daily,pressure,body,otherDay],day),[pressure,body,otherDay]);
 assert.ok(!html.includes('Mais registros'));assert.ok(!html.includes('opcional'));assert.ok(!html.includes('aprox.'));assert.equal((html.match(/class="well-petal(?: selected)?(?: recorded)?"/g)||[]).length,9);
 const Water=require(path.join(root,'components/WaterChoice')).default;
 {const savedState=React.useState,savedEffect=React.useEffect;let index=0;const slots=[];React.useState=initial=>{const i=index++;if(!slots[i])slots[i]={value:initial};return [slots[i].value,v=>slots[i].value=v];};React.useEffect=()=>{};let saved=[];const render=()=>{index=0;return Water({date:day,onSave:v=>saved.push(v)});};try{let form=render();form.props.onSubmit({preventDefault(){}});assert.deepEqual(saved,[]);form.props.children[0].props.children[1].props.onChange({target:{value:'2,5'}});render().props.onSubmit({preventDefault(){}});assert.deepEqual(saved,[2.5]);}finally{React.useState=savedState;React.useEffect=savedEffect;}}
 // Clicking a point keeps the selection; clicking outside restores the chart and parent history action.
 {const old=React.useState;let selected=null,notified='unset';React.useState=()=>[selected,v=>selected=v];const walk=(n,out=[])=>{if(Array.isArray(n))n.forEach(v=>walk(v,out));else if(n?.props){out.push(n);walk(n.props.children,out);}return out;};try{for(const type of ['pressure','body']){const record=type==='pressure'?pressure:body;let tree=Chart({type,records:[record],onSelect:v=>notified=v});let stopped=false;walk(tree).find(n=>n.type==='circle').props.onClick({stopPropagation(){stopped=true;}});assert.equal(stopped,true);assert.equal(selected,record.id);assert.equal(notified,record);tree=Chart({type,records:[record],onSelect:v=>notified=v});assert.ok(walk(tree).some(n=>n.props.className==='well-chart-detail'));tree.props.onClick();assert.equal(selected,null);assert.equal(notified,null);tree=Chart({type,records:[record],onSelect:v=>notified=v});assert.ok(!walk(tree).some(n=>n.props.className==='well-chart-detail'));}}finally{React.useState=old;}}
 const nav=require(path.join(root,'lib/nav')).NAV;assert.ok(nav.some(p=>p.id==='bemestar'));assert.ok(!nav.some(p=>p.id==='habitos'));
 console.log('PASSOU: validação de medidas e ciclo, datas, campos opcionais, histórico, painel e preservação do resumo de hábitos.');
}finally{fs.rmSync(root,{recursive:true});}
