"use client";
import ModalLayer from "./ModalLayer";
import {useEffect,useState} from 'react';
import {birthdayLabel,birthdayDayMonth,parseBirthday,birthdaySummary,nextBirthday,upcomingLabel,ageInYear,todayLocal} from '../lib/birthdays';
import {maskDateInput} from '../lib/dateInput';
import MonthInput from './MonthInput';
export default function BirthdaysView({contacts=[],setContacts,configured,openContact,onOpenHandled}){
 const today=todayLocal(),current=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`;
 const [month,setMonth]=useState(current),[query,setQuery]=useState(''),[editing,setEditing]=useState(null),[name,setName]=useState(''),[date,setDate]=useState(''),[year,setYear]=useState(''),[error,setError]=useState('');
 function edit(person){setEditing(person||{});setName(person?.name||'');setDate(person?birthdayDayMonth(person):'');setYear(person?.year?String(person.year):'');setError('');}
 useEffect(()=>{if(openContact){const person=contacts.find(p=>p.id===openContact);if(person){edit(person);onOpenHandled?.();}}},[openContact,contacts]);
 const [viewYear,viewMonth]=month.split('-').map(Number),summary=birthdaySummary(contacts,query,viewYear,viewMonth,today);
 function shift(delta){const value=new Date(viewYear,viewMonth-1+delta,1);if(value.getFullYear()>=1000&&value.getFullYear()<=9999)setMonth(`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}`);}
 function save(event){event.preventDefault();const result=parseBirthday(date+(year?'/'+year:''),name.trim());if(result.error){setError(result.error);return;}const person={...editing,...result.person,id:editing.id||'contact'+Date.now().toString(36)+Math.random().toString(36).slice(2)};setContacts(previous=>editing.id?previous.map(p=>p.id===person.id?person:p):[...previous,person]);setEditing(null);}
 function remove(person){if(!window.confirm(`Excluir o contato “${person.name}”? Esta ação não pode ser desfeita no LifeOS.`))return;setContacts(previous=>previous.filter(p=>p.id!==person.id));if(editing?.id===person.id)setEditing(null);}
 const ageText=age=>age===null?'':` · ${age} anos`;
 if(!configured)return <section className="diary-setup"><h2>Configure Aniversários no Notion</h2><p>Crie o banco Contatos com Nome (título), Dia e Mês (número), e Ano de nascimento (número, opcional).</p><p>Adicione <code>NOTION_CONTACTS_DATABASE_ID</code> na Vercel e faça um novo deploy. Consulte o README do pacote.</p></section>;
 return <section className="finance-view birthdays-view"><div className="finance-heading"><div><h1>Aniversários</h1><p className="muted">Lembre das pessoas e das datas especiais.</p></div><button className="primary" onClick={()=>edit(null)}>+ Novo contato</button></div>
 <input className="search birthday-search" aria-label="Buscar contatos" placeholder="Buscar contato…" value={query} onChange={e=>setQuery(e.target.value)}/>
 <div className="birthday-grid"><section className="birthday-card"><h2>Próximos 7 dias <span className="muted">({summary.week.length})</span></h2>{summary.week.map(person=><button className="birthday-row" key={person.id} onClick={()=>edit(person)}><strong>{person.name}</strong><span>{birthdayDayMonth(person)} · {upcomingLabel(person.next)}{ageText(person.next.age)}</span>{person.next.days===0&&<small className="birthday-today">Aniversário hoje</small>}</button>)}{!summary.week.length&&<p className="muted">Nenhum aniversário nos próximos 7 dias.</p>}</section>
 <section className="birthday-card"><h2>Aniversariantes do mês <span className="muted">({summary.monthly.length})</span></h2><div className="finance-period"><button className="ghost" aria-label="Mês anterior" onClick={()=>shift(-1)}>‹</button><MonthInput value={month} onChange={setMonth} label="Mês dos aniversários"/><button className="ghost" aria-label="Próximo mês" onClick={()=>shift(1)}>›</button><button className="ghost" onClick={()=>setMonth(current)}>Hoje</button></div>{summary.monthly.map(person=><button className="birthday-row" key={person.id} onClick={()=>edit(person)}><strong>{person.name}</strong><span>{birthdayDayMonth(person)}{ageText(ageInYear(person,viewYear))}</span></button>)}{!summary.monthly.length&&<p className="muted">Nenhum aniversário neste mês.</p>}</section></div>
 <section className="birthday-card"><h2>Contatos <span className="muted">({summary.contacts.length})</span></h2><div className="birthday-table-scroll"><table className="birthday-table"><thead><tr><th>Nome</th><th>Nascimento / aniversário</th><th>Próximo aniversário</th><th>Ações</th></tr></thead><tbody>{summary.contacts.map(person=>{const next=nextBirthday(person,today);return <tr key={person.id}><td>{person.name}</td><td>{birthdayLabel(person)}</td><td>{upcomingLabel(next)}{ageText(next.age)}</td><td><button className="ghost" onClick={()=>edit(person)}>Editar</button> <button className="danger" onClick={()=>remove(person)}>Excluir</button></td></tr>;})}</tbody></table></div>{!summary.contacts.length&&<p className="muted">Nenhum contato encontrado.</p>}</section>
 <ModalLayer open={!!(editing)} onClose={()=>{setEditing(null)}}>{editing&&<div className="overlay" onClick={()=>setEditing(null)}><div className="panel finance-modal" role="dialog" aria-modal="true" aria-label={editing.id?'Editar contato':'Novo contato'} onClick={e=>e.stopPropagation()}><div className="panel-head"><h2 className="grow">{editing.id?'Editar contato':'Novo contato'}</h2><button className="ghost" onClick={()=>setEditing(null)}>Fechar</button></div><form onSubmit={save}><div className="finance-form"><label>Nome<input autoFocus className="search" value={name} maxLength={200} onChange={e=>setName(e.target.value)} required/></label><label>Dia e mês<input className="search" inputMode="numeric" placeholder="DD/MM" value={date} maxLength={5} onChange={e=>setDate(maskDateInput(e.target.value).slice(0,5))} required/></label><label>Ano de nascimento (opcional)<input className="search" inputMode="numeric" placeholder="AAAA" value={year} maxLength={4} onChange={e=>setYear(e.target.value.replace(/\D/g,''))}/></label></div><p className="muted small">Deixe o ano vazio quando não souber. A idade só aparece quando o ano é informado.</p>{error&&<p role="alert" className="date-error">{error}</p>}<div className="finance-period"><button type="submit" className="primary">Salvar contato</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>Cancelar</button>{editing.id&&<button type="button" className="danger" onClick={()=>remove(editing)}>Excluir contato</button>}</div></form></div></div>}</ModalLayer>
 </section>;
}
