"use client";
import {useRef,useState} from 'react';
import {money,currentMonth,formatMonth,parseMoney,consolidate,sankeyLayout} from '../lib/finance';
import MonthInput from './MonthInput';
const uid=prefix=>prefix+Date.now().toString(36)+Math.random().toString(36).slice(2);
function Sankey({summary,onSelect}){
 const [offsets,setOffsets]=useState({}),drag=useRef(null),svg=useRef(null),moved=useRef(false);
 const layout=sankeyLayout(summary,offsets);
 const color=node=>node.flow==='deficit'?'#f26d64':node.flow==='balance'?'#59ce9b':node.flow==='in'?'#6ea8fe':'#e6a07d';
 function start(e,node){if(node.system)return;drag.current={id:node.id,y:e.clientY,offset:offsets[node.id]||0};moved.current=false;e.currentTarget.setPointerCapture(e.pointerId);}
 function move(e){if(!drag.current)return;const delta=(e.clientY-drag.current.y)*layout.height/svg.current.getBoundingClientRect().height;if(Math.abs(delta)>5){moved.current=true;setOffsets(old=>({...old,[drag.current.id]:drag.current.offset+delta}));}}
 function end(){drag.current=null;setTimeout(()=>{moved.current=false;},0);}
 if(!summary.total)return <p className="finance-empty">Crie suas categorias e adicione valores para montar o fluxo do período.</p>;
 const ribbon=(x1,y1,x2,y2,h)=>`M${x1},${y1} C${(x1+x2)/2},${y1} ${(x1+x2)/2},${y2} ${x2},${y2} L${x2},${y2+h} C${(x1+x2)/2},${y2+h} ${(x1+x2)/2},${y1+h} ${x1},${y1+h} Z`;
 return <div className="finance-graph-scroll"><svg ref={svg} className="finance-graph" viewBox={`0 0 1100 ${layout.height}`} role="group" aria-label="Fluxo financeiro do período">
  <text x="550" y="22" textAnchor="middle" fill="#a8caff">{summary.balance<0?'Entradas + saldo faltante':'Disponível no período'}</text><text x="550" y="44" textAnchor="middle" fill="#a8caff">{money(summary.total)}</text>
  <rect x="540" y={layout.centerY} width="20" height={layout.centralHeight} rx="5" fill="#6ea8fe"/>
  {['left','right'].flatMap(side=>layout[side].map(node=>{
   const left=side==='left',x=left?200:900,c=color(node),path=left?ribbon(216,node.y,540,node.center,node.h):ribbon(560,node.center,900,node.y,node.h);
   return <g key={node.id} role={node.system?undefined:'button'} tabIndex={node.system?undefined:0} aria-label={`${node.name}: ${money(node.value)}${node.system?'':'. Editar lançamentos'}`} onClick={()=>{if(!node.system&&!moved.current)onSelect(node.id);}} onKeyDown={e=>{if(!node.system&&['Enter',' '].includes(e.key)){e.preventDefault();onSelect(node.id);}}} className={node.system?'finance-system':'finance-node'}>
    <title>{`${node.name}: ${money(node.value)}${node.system?' · Cálculo automático':' · Clique para editar ou excluir lançamentos'}`}</title>
    <path d={path} fill={c} opacity=".35"/>
    <rect x={x} y={node.y} width="16" height={Math.max(2,node.h)} rx="4" fill={c} onPointerDown={e=>start(e,node)} onPointerMove={move} onPointerUp={end} onPointerCancel={end}/>
    <text x={left?185:930} y={node.y+node.h/2-3} textAnchor={left?'end':'start'} fill="#e8eaef">{node.name.length>22?node.name.slice(0,21)+'…':node.name}</text>
    <text x={left?185:930} y={node.y+node.h/2+19} textAnchor={left?'end':'start'} fill={c}>{money(node.value)}</text>
   </g>;
  }))}
 </svg></div>;
}
export default function FinanceView({categories=[],transactions=[],setFinance,configured}){
 const [mode,setMode]=useState('month'),[month,setMonth]=useState(currentMonth()),[year,setYear]=useState(new Date().getFullYear()),[start,setStart]=useState(currentMonth()),[end,setEnd]=useState(currentMonth());
 const [flow,setFlow]=useState('in'),[category,setCategory]=useState(''),[amount,setAmount]=useState(''),[entryMonth,setEntryMonth]=useState(currentMonth()),[error,setError]=useState('');
 const [entryMonthValid,setEntryMonthValid]=useState(true),[editMonthValid,setEditMonthValid]=useState(true);
 const [yearText,setYearText]=useState(String(year));
 const [manage,setManage]=useState(false),[categoryEdit,setCategoryEdit]=useState(null),[categoryName,setCategoryName]=useState(''),[categoryFlow,setCategoryFlow]=useState('in');
 const [selected,setSelected]=useState(null),[editing,setEditing]=useState(null),[editAmount,setEditAmount]=useState(''),[editMonth,setEditMonth]=useState(''),[editCategory,setEditCategory]=useState('');
 const from=mode==='month'?month:mode==='year'?`${year}-01`:start,to=mode==='month'?month:mode==='year'?`${year}-12`:end;
 const valid=from<=to,summary=consolidate(categories,transactions,from,to);
 const selectedCategory=categories.find(item=>item.id===selected);
 const rows=transactions.filter(item=>item.category===selected&&item.month>=from&&item.month<=to).sort((a,b)=>b.month.localeCompare(a.month));
 const filtered=categories.filter(item=>item.flow===flow);
 function shift(delta){const y=Number(month.slice(0,4)),m=Number(month.slice(5));const date=new Date(y,m-1+delta,1);if(date.getFullYear()<1000||date.getFullYear()>9999)return;setMonth(`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`);}
 function add(){if(!entryMonthValid){setError('Confirme um mês válido com Tab antes de adicionar.');return;}const value=parseMoney(amount),cat=categories.find(item=>item.id===category&&item.flow===flow);if(!cat||!value){setError('Escolha uma categoria e informe um valor positivo, por exemplo 1.250,50.');return;}setFinance(prev=>({...prev,transactions:[...prev.transactions,{id:uid('f'),name:cat.name,category:cat.id,month:entryMonth,amount:value}]}));setAmount('');setError('');}
 function saveCategory(){if(!categoryName.trim()||categoryName.trim().length>100){setError('Informe um nome de categoria com até 100 caracteres.');return;}const old=categories.find(item=>item.id===categoryEdit);if(old&&old.flow!==categoryFlow&&transactions.some(item=>item.category===old.id)&&!window.confirm('Mudar o tipo desta categoria altera todos os lançamentos vinculados, inclusive de outros meses. Continuar?'))return;const value={...(old||{}),id:old?.id||uid('c'),name:categoryName.trim(),flow:categoryFlow};setFinance(prev=>({...prev,categories:old?prev.categories.map(item=>item.id===old.id?value:item):[...prev.categories,value]}));setCategoryName('');setCategoryEdit(null);setError('');}
 function deleteCategory(item){const count=transactions.filter(row=>row.category===item.id).length;if(!window.confirm(`Excluir a categoria “${item.name}”${count?` e seus ${count} lançamento(s), de todos os meses`:''}?`))return;setFinance(prev=>({categories:prev.categories.filter(cat=>cat.id!==item.id),transactions:prev.transactions.filter(row=>row.category!==item.id)}));if(category===item.id)setCategory('');if(selected===item.id)setSelected(null);if(categoryEdit===item.id){setCategoryEdit(null);setCategoryName('');}}
 function deleteEntry(item){if(!window.confirm(`Excluir o lançamento de ${money(item.amount)} em ${formatMonth(item.month)}?`))return;setFinance(prev=>({...prev,transactions:prev.transactions.filter(row=>row.id!==item.id)}));if(editing===item.id)setEditing(null);}
 function editEntry(item){setEditing(item.id);setEditAmount((item.amount/100).toFixed(2).replace('.',','));setEditMonth(item.month);setEditMonthValid(true);setEditCategory(item.category);setError('');}
 function saveEntry(){if(!editMonthValid){setError('Confirme um mês válido com Tab antes de salvar.');return;}const value=parseMoney(editAmount);if(!value||!categories.some(cat=>cat.id===editCategory)){setError('Informe categoria e valor válidos.');return;}setFinance(prev=>({...prev,transactions:prev.transactions.map(row=>row.id===editing?{...row,category:editCategory,month:editMonth,amount:value,name:categories.find(cat=>cat.id===editCategory).name}:row)}));setEditing(null);setError('');}
 if(!configured)return <section className="diary-setup"><h2>Configure Finanças no Notion</h2><p>Crie os bancos Categorias financeiras e Lançamentos financeiros conforme o README do pacote.</p><p>Adicione <code>NOTION_FINANCE_CATEGORIES_DATABASE_ID</code> e <code>NOTION_FINANCE_TRANSACTIONS_DATABASE_ID</code> na Vercel e faça um novo deploy.</p></section>;
 return <section className="finance-view">
  <div className="finance-heading"><div><h1>Finanças</h1><p className="muted">Veja de onde vem e para onde vai seu dinheiro.</p></div><button className="ghost" onClick={()=>{setManage(true);setError('');}}>Gerenciar categorias</button></div>
  <div className="finance-period"><div className="segmented" aria-label="Período">{[['month','Mês'],['year','Ano'],['range','Período']].map(([id,label])=><button key={id} className={mode===id?'on':''} onClick={()=>{setMode(id);setSelected(null);}}>{label}</button>)}</div>
   {mode==='month'?<><button className="ghost" onClick={()=>shift(-1)} aria-label="Mês anterior">‹</button><MonthInput value={month} onChange={setMonth} label="Mês do resumo"/><button className="ghost" onClick={()=>shift(1)} aria-label="Próximo mês">›</button></>:mode==='year'?<><button className="ghost" disabled={year<=1000} onClick={()=>{setYear(year-1);setYearText(String(year-1));}} aria-label="Ano anterior">‹</button><input className="search finance-year" type="text" inputMode="numeric" maxLength={4} aria-label="Ano do resumo" value={yearText} onChange={e=>setYearText(e.target.value.replace(/\D/g,''))} onBlur={()=>{const value=Number(yearText);if(value>=1000&&value<=9999){setYear(value);setError('');}else{setYearText(String(year));setError('Informe um ano entre 1000 e 9999.');}}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><button className="ghost" disabled={year>=9999} onClick={()=>{setYear(year+1);setYearText(String(year+1));}} aria-label="Próximo ano">›</button></>:<><MonthInput value={start} onChange={setStart} label="Início do período"/><span>a</span><MonthInput value={end} onChange={setEnd} label="Fim do período"/></>}
  </div>
  {!valid?<p className="date-error" role="alert">O início do período deve ser anterior ou igual ao fim.</p>:<>
   <div className="finance-summary"><div><span>Entradas</span><strong className="finance-income">{money(summary.income)}</strong></div><div><span>Saídas</span><strong className="finance-expense">{money(summary.expense)}</strong></div><div><span>Saldo {mode==='month'?'do mês':'do período'}</span><strong className={summary.balance<0?'finance-expense':'finance-balance'}>{money(summary.balance)}</strong><small>Entradas − saídas</small></div></div>
   <div className="finance-card"><div className="finance-heading"><h2>Fluxo {mode==='month'?'do mês':'do período'}</h2><span className="muted small">Clique no nome para editar · Arraste os blocos para organizar</span></div><Sankey summary={summary} onSelect={id=>{setSelected(id);setEditing(null);setError('');}}/><p className="muted small">Saldo restante e saldo faltante são cálculos automáticos.</p></div>
  </>}
  <div className="finance-card"><h2>Adicionar valor</h2><div className="finance-form">
   <label>Tipo<select className="search" value={flow} onChange={e=>{setFlow(e.target.value);setCategory('');}}><option value="in">Entrada</option><option value="out">Saída</option></select></label>
   <label>Categoria<select className="search" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Selecionar…</option>{filtered.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
   <label>Mês<MonthInput value={entryMonth} onChange={setEntryMonth} label="Mês do lançamento" onValidityChange={setEntryMonthValid}/></label>
   <label>Valor<input className="search" inputMode="decimal" placeholder="R$ 0,00" value={amount} onChange={e=>setAmount(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add();}}/></label>
   <button className="primary" onClick={add}>+ Adicionar</button>
  </div>{!filtered.length&&<p className="muted small">Crie uma categoria de {flow==='in'?'entrada':'saída'} em Gerenciar categorias.</p>}</div>
  {error&&!manage&&!selected&&<p className="date-error" role="alert">{error}</p>}
  {manage&&<div className="overlay" onClick={()=>setManage(false)}><div className="panel finance-modal" role="dialog" aria-modal="true" aria-label="Categorias financeiras" onClick={e=>e.stopPropagation()}><div className="panel-head"><h2 className="grow">Categorias</h2><button className="ghost" onClick={()=>setManage(false)}>Fechar</button></div><p className="muted">Crie os nomes que você quer usar nas entradas e saídas.</p><div className="finance-form"><label>Nome<input className="search" value={categoryName} maxLength={100} onChange={e=>setCategoryName(e.target.value)}/></label><label>Tipo<select className="search" value={categoryFlow} onChange={e=>setCategoryFlow(e.target.value)}><option value="in">Entrada</option><option value="out">Saída</option></select></label><button className="primary" onClick={saveCategory}>{categoryEdit?'Salvar categoria':'+ Criar categoria'}</button>{categoryEdit&&<button className="ghost" onClick={()=>{setCategoryEdit(null);setCategoryName('');}}>Cancelar edição</button>}</div>{error&&<p className="date-error" role="alert">{error}</p>}<ul className="finance-list">{categories.map(item=><li key={item.id}><span className="grow">{item.name} <small className="muted">· {item.flow==='in'?'Entrada':'Saída'}</small></span><button className="ghost" onClick={()=>{setCategoryEdit(item.id);setCategoryName(item.name);setCategoryFlow(item.flow);}}>Editar</button><button className="danger" onClick={()=>deleteCategory(item)}>Excluir</button></li>)}</ul></div></div>}
  {selectedCategory&&<div className="overlay" onClick={()=>setSelected(null)}><div className="panel finance-modal" role="dialog" aria-modal="true" aria-label={`Lançamentos de ${selectedCategory.name}`} onClick={e=>e.stopPropagation()}><div className="panel-head"><h2 className="grow">{selectedCategory.name}</h2><button className="ghost" onClick={()=>setSelected(null)}>Fechar</button></div><p className="muted">Lançamentos de {formatMonth(from)} a {formatMonth(to)} · {selectedCategory.flow==='in'?'Entrada':'Saída'}</p><ul className="finance-list">{rows.map(item=><li key={item.id}><span className="grow">{formatMonth(item.month)} · {money(item.amount)}</span><button className="ghost" onClick={()=>editEntry(item)}>Editar</button><button className="danger" onClick={()=>deleteEntry(item)}>Excluir</button></li>)}</ul>{!rows.length&&<p className="muted">Nenhum lançamento neste período.</p>}{editing&&<div className="finance-edit"><h3>Editar lançamento</h3><div className="finance-form"><label>Categoria<select className="search" value={editCategory} onChange={e=>setEditCategory(e.target.value)}>{categories.map(item=><option key={item.id} value={item.id}>{item.name} · {item.flow==='in'?'Entrada':'Saída'}</option>)}</select></label><label>Mês<MonthInput value={editMonth} onChange={setEditMonth} label="Editar mês do lançamento" onValidityChange={setEditMonthValid}/></label><label>Valor<input className="search" inputMode="decimal" value={editAmount} onChange={e=>setEditAmount(e.target.value)}/></label><button className="primary" onClick={saveEntry}>Salvar</button><button className="ghost" onClick={()=>setEditing(null)}>Cancelar</button></div></div>}{error&&<p className="date-error" role="alert">{error}</p>}</div></div>}
 </section>;
}
