"use client";
import {useEffect,useState} from 'react';
import {HABIT_COLORS,HABIT_ICONS,habitColor,habitToday,habitUid,validHabit,toggleHabit,habitPeriod,habitMonthDays,duplicateHabit} from '../lib/habits';
import {formatDateInput} from '../lib/dateInput';
import MonthInput from './MonthInput';
import DateInput from './DateInput';
import HabitIcon from './HabitIcon';
import ModalLayer from './ModalLayer';
export default function HabitsView({habits=[],logs=[],setHabits,context,configured}){
 const [today,setToday]=useState(habitToday),[date,setDate]=useState(habitToday),[month,setMonth]=useState(()=>habitToday().slice(0,7)),[mode,setMode]=useState('month'),[year,setYear]=useState(()=>Number(habitToday().slice(0,4))),[yearText,setYearText]=useState(()=>habitToday().slice(0,4));
 const [editing,setEditing]=useState(null),[name,setName]=useState(''),[color,setColor]=useState('blue'),[icon,setIcon]=useState('book'),[error,setError]=useState('');
 useEffect(()=>{const check=()=>{const now=habitToday();if(now!==today){setToday(now);setDate(previous=>previous===today?now:previous);}};const timer=setInterval(check,30000);window.addEventListener('focus',check);document.addEventListener('visibilitychange',check);return()=>{clearInterval(timer);window.removeEventListener('focus',check);document.removeEventListener('visibilitychange',check);};},[today]);
 const [showEnded,setShowEnded]=useState(false);
 const visible=habits.filter(p=>p.context==='personal'&&(showEnded||!p.archived)),daily=visible.filter(p=>!p.archived&&p.start<=date),marked=new Set(logs.filter(p=>p.date===date).map(p=>p.habit)),completed=daily.filter(p=>marked.has(p.id));
 const [viewYear,viewMonth]=month.split('-').map(Number),days=habitMonthDays(viewYear,viewMonth),start=days[0],end=days.at(-1);
 function edit(habit){setEditing(habit||{});setName(habit?.name||'');setColor(habit?.color||'blue');setIcon(habit?.icon||'book');setError('');}
 const duplicate=editing?duplicateHabit(habits,name,editing.id):null;
 function recover(habit){if(!window.confirm(`Recuperar o hábito “${habit.name}” e voltar a acompanhá-lo? O histórico será mantido e o período sem marcações continuará como não marcado.`))return;setHabits(previous=>({...previous,habits:previous.habits.map(p=>p.id===habit.id?{...p,archived:false}:p)}));setEditing(null);setError('');setDate(today);}
 function endHabit(){if(!window.confirm(`Encerrar o acompanhamento do hábito “${editing.name}”? Ele ficará oculto, com o histórico preservado, e poderá ser recuperado depois.`))return;setHabits(previous=>({...previous,habits:previous.habits.map(p=>p.id===editing.id?{...p,archived:true}:p)}));setEditing(null);setError('');}
 function save(event){event.preventDefault();if(duplicate){setError(duplicate.archived?'Já existe um hábito encerrado com este nome. Você pode recuperá-lo abaixo, mantendo o histórico.':'Já existe um hábito ativo com este nome. Edite o hábito existente.');return;}const value={...editing,id:editing.id||habitUid(),name:name.trim(),context:'personal',color,icon,start:editing.start||today};const message=validHabit(value);if(message){setError(message);return;}setHabits(previous=>({...previous,habits:editing.id?previous.habits.map(p=>p.id===value.id?value:p):[...previous.habits,value]}));if(!editing.id)setDate(today);setEditing(null);setError('');}
 function toggle(habit,day){try{setHabits(previous=>({...previous,habitLogs:toggleHabit(previous.habitLogs,habit,day)}));setError('');}catch(e){setError(e.message);}}
 function remove(){if(!window.confirm(`Excluir o hábito “${editing.name}” e todas as suas marcações? O progresso será removido do LifeOS.`))return;setHabits(previous=>({habits:previous.habits.filter(p=>p.id!==editing.id),habitLogs:previous.habitLogs.filter(p=>p.habit!==editing.id)}));setEditing(null);}
 function shiftMonth(delta){const next=new Date(viewYear,viewMonth-1+delta,1,12);if(next.getFullYear()>=1000&&next.getFullYear()<=9999)setMonth(`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}`);}
 function shiftDate(delta){const next=new Date(date+'T12:00:00');next.setDate(next.getDate()+delta);const value=`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}-${String(next.getDate()).padStart(2,'0')}`;if(value<=today)setDate(value);}
 if(!configured)return <section className="diary-setup"><h2>Configure Hábitos no Notion</h2><p>Crie os bancos Hábitos e Registros de hábitos conforme o README.</p><p>Adicione <code>NOTION_HABITS_DATABASE_ID</code> e <code>NOTION_HABIT_LOGS_DATABASE_ID</code> na Vercel e faça um novo deploy.</p></section>;
 return <section className="habits-view"><div className="finance-heading"><div><h1>Hábitos</h1><p className="muted">Pequenos passos, todos os dias.</p></div><div className="finance-period"><button className="ghost" aria-pressed={showEnded} onClick={()=>setShowEnded(!showEnded)}>{showEnded?'Ocultar hábitos encerrados':'Mostrar hábitos encerrados'}</button><button className="primary" onClick={()=>edit(null)}>+ Novo hábito</button></div></div>
 <div className="finance-period"><button className="ghost" aria-label="Dia anterior" onClick={()=>shiftDate(-1)}>‹</button><DateInput className="search" value={date} max={today} onChange={e=>{if(e.target.value)setDate(e.target.value);}} aria-label="Dia dos hábitos"/><button className="ghost" aria-label="Próximo dia" disabled={date>=today} onClick={()=>shiftDate(1)}>›</button><button className="ghost" onClick={()=>setDate(today)}>Hoje</button><span className="muted small">{date===today?'Hoje':formatDateInput(date)}</span></div>
 <div className="habit-daily-summary"><strong>{completed.length} de {daily.length} concluídos {date===today?'hoje':'neste dia'}</strong><div className="habit-daily-progress" role="progressbar" aria-label="Hábitos concluídos no dia" aria-valuemin={0} aria-valuemax={daily.length||1} aria-valuenow={completed.length}>{completed.map(habit=><span key={habit.id} style={{background:habitColor(habit.color).hex,width:`${100/Math.max(1,daily.length)}%`}}/>)}</div></div>
 <div className="habit-grid">{daily.map(habit=>{const done=marked.has(habit.id),hex=habitColor(habit.color).hex;return <div key={habit.id} className={'habit-card'+(done?' complete':'')} style={{'--habit-color':hex,'--habit-bg':hex+'30'}}><button className="habit-check-card" aria-pressed={done} aria-label={`${done?'Desmarcar':'Concluir'} ${habit.name}`} onClick={()=>toggle(habit,date)}><span className="habit-check">{done?'✓':''}</span><HabitIcon id={habit.icon}/><span className="habit-card-copy"><strong>{habit.name}</strong><small>{done?(date===today?'Concluído hoje':'Concluído neste dia'):'Marcar como feito'}</small></span></button><button className="ghost habit-edit" aria-label={`Editar ${habit.name}`} onClick={()=>edit(habit)}>✎</button></div>;})}</div>
 {!daily.length&&<p className="empty">Nenhum hábito disponível neste dia e contexto. Crie seu primeiro hábito.</p>}<p className="muted small">A cada novo dia, os hábitos ficam disponíveis para marcar novamente. O progresso anterior é preservado.</p>
 <section className="birthday-card habit-analytics"><div className="finance-heading"><div><h2>Seu progresso</h2><p className="muted small">Acompanhe a constância de cada hábito.</p></div><div className="segmented">{[['month','Mês'],['year','Ano']].map(([id,label])=><button key={id} className={mode===id?'on':''} onClick={()=>setMode(id)}>{label}</button>)}</div></div>
 <div className="finance-period">{mode==='month'?<><button className="ghost" aria-label="Mês anterior" onClick={()=>shiftMonth(-1)}>‹</button><MonthInput value={month} onChange={value=>{if(value)setMonth(value);}} label="Mês do acompanhamento"/><button className="ghost" aria-label="Próximo mês" onClick={()=>shiftMonth(1)}>›</button></>:<><button className="ghost" disabled={year<=1000} onClick={()=>{setYear(year-1);setYearText(String(year-1));}}>‹</button><input className="search finance-year" aria-label="Ano do acompanhamento" inputMode="numeric" maxLength={4} value={yearText} onChange={e=>setYearText(e.target.value.replace(/\D/g,''))} onBlur={()=>{const value=Number(yearText);if(value>=1000&&value<=9999){setYear(value);setError('');}else{setYearText(String(year));setError('Informe um ano válido.');}}}/><button className="ghost" disabled={year>=9999} onClick={()=>{setYear(year+1);setYearText(String(year+1));}}>›</button></>}<button className="ghost" onClick={()=>{setMonth(today.slice(0,7));setYear(Number(today.slice(0,4)));setYearText(today.slice(0,4));}}>Atual</button></div>
 <div className="habit-matrix-scroll"><table className={"habit-matrix "+(mode==='year'?'habit-matrix-year':'habit-matrix-month')}><thead><tr><th>Hábito</th>{mode==='month'?days.map(day=><th key={day}>{day.slice(-2)}</th>):['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'].map(label=><th key={label}>{label}</th>)}<th>Constância</th></tr></thead><tbody>{visible.map(habit=>{const hex=habitColor(habit.color).hex,summary=habitPeriod(habit,logs,mode==='month'?start:`${year}-01-01`,mode==='month'?end:`${year}-12-31`,today);return <tr key={habit.id} style={{'--habit-color':hex}}><th><span className="habit-matrix-name"><HabitIcon id={habit.icon} size={18}/>{habit.name}</span>{habit.archived&&<div className="habit-ended-actions"><span className="chip">Encerrado</span><button className="ghost" onClick={()=>edit(habit)} aria-label={`Editar hábito encerrado ${habit.name}`}>✎</button><button className="ghost" onClick={()=>recover(habit)}>Recuperar</button></div>}</th>{mode==='month'?days.map(day=>{const done=logs.some(log=>log.habit===habit.id&&log.date===day),eligible=!habit.archived&&day>=habit.start&&day<=today;return <td key={day} data-day={day.slice(-2)}><button className={'habit-day'+(done?' done':'')+(!eligible?' unavailable':'')} disabled={!eligible} aria-pressed={done} aria-label={`${habit.name}, ${formatDateInput(day)}: ${done?'concluído':eligible?'não marcado':'indisponível'}`} title={formatDateInput(day)+(day>today?' · Dia futuro':day<habit.start?' · Antes do início':done?' · Concluído':' · Não marcado')} onClick={()=>toggle(habit,day)}/></td>;}):Array.from({length:12},(_,index)=>{const monthDays=habitMonthDays(year,index+1),value=habitPeriod(habit,logs,monthDays[0],monthDays.at(-1),today);return <td key={index} data-day={['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'][index]}><button className="habit-year-cell" disabled={!value.total} title={`${value.done}/${value.total} dias · ${value.percent}%`} style={{background:value.total?hex+(value.percent>=75?'aa':value.percent>=40?'66':'25'):undefined}} onClick={()=>{setMonth(`${year}-${String(index+1).padStart(2,'0')}`);setMode('month');}}>{value.total?value.percent+'%':'—'}</button></td>;})}<td className="habit-stat"><div className="habit-stat-bar"><span style={{width:summary.percent+'%',background:hex}}/></div><span>{summary.done}/{summary.total} dias · {summary.percent}%</span></td></tr>;})}</tbody></table></div>
 {!visible.length&&<p className="muted">Crie um hábito para acompanhar seu progresso.</p>}<p className="muted small">{mode==='month'?'Clique nos dias para marcar ou corrigir.':'Clique em um mês para ver os dias.'} Dias futuros e dias anteriores à criação não entram no cálculo.</p><div className="habit-legend"><span>■ Concluído</span><span>□ Não marcado</span><span className="muted">■ Futuro / antes do início</span></div></section>
 {error&&<p className="date-error" role="alert">{error}</p>}
 {editing&&<ModalLayer><div className="overlay" onClick={()=>setEditing(null)}><div className="panel finance-modal" role="dialog" aria-modal="true" aria-label={editing.id?'Editar hábito':'Novo hábito'} onClick={e=>e.stopPropagation()}><h2>{editing.id?'Editar hábito':'Novo hábito'}</h2><form onSubmit={save}><label className="habit-field">Nome<input className="search" autoFocus maxLength={200} value={name} onChange={e=>setName(e.target.value)} required/></label><h3>Cor</h3><div className="habit-palette">{HABIT_COLORS.map(c=><button type="button" key={c.id} className={'habit-swatch'+(color===c.id?' selected':'')} style={{background:c.hex}} aria-label={c.name} aria-pressed={color===c.id} title={c.name} onClick={()=>setColor(c.id)}>{color===c.id?'✓':''}</button>)}</div><h3>Ícone</h3><div className="habit-icon-picker">{HABIT_ICONS.map(([id,label])=><button type="button" key={id} className={icon===id?'selected':''} style={{color:habitColor(color).hex}} aria-label={label} aria-pressed={icon===id} title={label} onClick={()=>setIcon(id)}><HabitIcon id={id}/><small>{label}</small></button>)}</div><div className="habit-preview" style={{color:habitColor(color).hex,background:habitColor(color).hex+'25',borderColor:habitColor(color).hex}}><HabitIcon id={icon}/><strong>{name.trim()||'Seu hábito'}</strong><span>✓</span></div><p className="muted small">Hábito diário · {editing.start?'Início: '+formatDateInput(editing.start):'Começa hoje'}</p>{duplicate&&<div className="date-error" role="alert">Já existe um hábito {duplicate.archived?'encerrado':'ativo'} com este nome.{duplicate.archived&&<button type="button" className="ghost" onClick={()=>recover(duplicate)}>Recuperar hábito existente</button>}</div>}{error&&<p className="date-error" role="alert">{error}</p>}<div className="finance-period"><button className="primary">Salvar hábito</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>Cancelar</button>{editing.id&&<button type="button" className="ghost" onClick={()=>editing.archived?recover(editing):endHabit()}>{editing.archived?'Recuperar hábito':'Encerrar hábito'}</button>}{editing.id&&<button type="button" className="danger" onClick={remove}>Excluir hábito</button>}</div></form></div></div></ModalLayer>}
 </section>;
}
