"use client";
import {useState} from 'react';
import {CHART_SERIES,measurementScales} from '../lib/measurementChart';
import {formatDateInput} from '../lib/dateInput';
const number=(v,type)=>v==null?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:type==='pressure'?0:2});
export default function MeasurementChart({records,type,onSelect}){
 const [selected,setSelected]=useState(null),points=records.slice(0,12).reverse(),series=CHART_SERIES[type],scales=measurementScales(points,type);
 const left=44,right=376,top=30,bottom=196,start=Date.parse(points[0]?.date||''),end=Date.parse(points.at(-1)?.date||'');
 const x=p=>start===end?(left+right)/2:left+(Date.parse(p.date)-start)/(end-start)*(right-left),y=(value,axis)=>bottom-(value-scales[axis].min)/(scales[axis].max-scales[axis].min)*(bottom-top);
 const dates=[...new Map(points.map(p=>[p.date,p])).values()],dateLabels=[...new Set([0,Math.floor((dates.length-1)/2),dates.length-1])].filter(i=>i>=0).map(i=>dates[i]);
 const current=points.find(p=>p.id===selected),hasRight=!!scales.right;
 function select(point){setSelected(point.id);onSelect?.(point);}
 function clearSelection(){setSelected(null);onSelect?.(null);}
 function segments(key){const groups=[];let group=[];for(const p of points){if(Number.isFinite(p.data[key]))group.push(p);else if(group.length){groups.push(group);group=[];}}if(group.length)groups.push(group);return groups;}
 return <div className="well-combined-chart" onClick={clearSelection}><div className="well-chart-legend">{series.map(s=><span key={s.key}><i style={{background:s.color}}/>{s.label} · {s.unit} ({s.axis==='left'?'esquerda':'direita'})</span>)}</div><svg viewBox="0 0 420 240" role="img" aria-label={type==='pressure'?'Pressão sistólica e diastólica com escala à esquerda e BPM à direita':'Peso em kg à esquerda e gordura em porcentagem à direita'}>{scales.left?.ticks.map(tick=><g key={tick}><line x1={left} x2={right} y1={y(tick,'left')} y2={y(tick,'left')} stroke="#ffffff12"/><text x={left-8} y={y(tick,'left')+4} textAnchor="end">{number(tick,type)}</text></g>)}{scales.right?.ticks.map(tick=><text key={tick} x={right+8} y={y(tick,'right')+4} style={{fill:'#f69cbc'}}>{number(tick,type)}</text>)}<text x={left} y="15" fill="#81bdff">{type==='pressure'?'mmHg':'kg'}</text>{hasRight&&<text x={right} y="15" textAnchor="end" fill="#f69cbc">{type==='pressure'?'bpm':'%'}</text>}<line x1={left} x2={left} y1={top} y2={bottom} stroke="#40516a"/>{hasRight&&<line x1={right} x2={right} y1={top} y2={bottom} stroke="#40516a"/>}{series.map(s=><g key={s.key}>{segments(s.key).map((group,i)=><polyline key={i} points={group.map(p=>`${x(p)},${y(p.data[s.key],s.axis)}`).join(' ')} fill="none" stroke={s.color} strokeWidth="2"/>)}{points.filter(p=>Number.isFinite(p.data[s.key])).map(p=><circle key={p.id} cx={x(p)} cy={y(p.data[s.key],s.axis)} r={selected===p.id?5:3.5} fill={s.color} tabIndex="0" role="button" aria-label={`${formatDateInput(p.date)}: ${s.label} ${number(p.data[s.key],type)} ${s.unit}`} onClick={e=>{e.stopPropagation();select(p);}} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();select(p);}}}><title>{`${formatDateInput(p.date)}: ${s.label} ${number(p.data[s.key],type)} ${s.unit}`}</title></circle>)}</g>)}{dateLabels.map((point,index)=><text key={point.date} x={x(point)} y={bottom+22} textAnchor={dateLabels.length===1?'middle':index===0?'start':index===dateLabels.length-1?'end':'middle'}>{formatDateInput(point.date).slice(0,5)}</text>)}</svg>{current?<p className="well-chart-detail">{formatDateInput(current.date)} · {series.filter(s=>Number.isFinite(current.data[s.key])).map(s=>`${s.label}: ${number(current.data[s.key],type)} ${s.unit}`).join(' · ')}</p>:<p className="muted small">Últimos {points.length} {type==='pressure'?'dias com medições':'registros'} · toque em um ponto para ver os valores.</p>}{!hasRight&&type==='body'&&<p className="muted small">A escala de gordura aparece quando houver um percentual registrado.</p>}</div>;
}
