"use client";
import {useEffect,useRef,useState} from 'react';
import {api} from '../lib/api';
export default function QrLogin({onComplete,onClose}){
 const [request,setRequest]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[expired,setExpired]=useState(false);const redeemed=useRef(false),generation=useRef(0),controller=useRef(null);
 async function start(){controller.current?.abort();controller.current=new AbortController();const run=++generation.current;setBusy(true);setError('');setRequest(null);setExpired(false);redeemed.current=false;try{const value=await api('/api/auth/qr',{method:'POST',signal:controller.current.signal,body:JSON.stringify({action:'start'})});if(run===generation.current)setRequest(value);}catch(e){if(run===generation.current)setError(e.message);}finally{if(run===generation.current)setBusy(false);}}
 useEffect(()=>{start();return()=>{generation.current++;controller.current?.abort();};},[]);
 useEffect(()=>{if(!request)return;let stopped=false,timer=null;async function poll(){if(stopped||redeemed.current)return;if(Date.now()>=request.expiresAt){setExpired(true);return;}if(!document.hidden){try{const result=await api('/api/auth/qr');if(stopped)return;if(result.status==='denied'){setError('O acesso foi recusado no celular.');setExpired(true);return;}if(result.status==='approved'){redeemed.current=true;await api('/api/auth/qr',{method:'POST',body:JSON.stringify({action:'redeem'})});if(!stopped)onComplete();return;}}catch(e){if(stopped)return;setError(e.message);if([401,409,410].includes(e.status)){setExpired(true);return;}redeemed.current=false;}}if(!stopped)timer=setTimeout(poll,2500);}poll();return()=>{stopped=true;clearTimeout(timer);};},[request,onComplete]);
 return <div className="qr-login"><h2>Entrar com QR Code</h2><p className="muted">Leia com a câmera do celular e confirme no LifeOS com sua conta Google já conectada.</p>{busy&&<p>Gerando QR Code…</p>}{request&&!expired&&<><img className="qr-code" src={request.image} width="280" height="280" alt="QR Code para autorizar este computador"/><p>Confira este código nas duas telas:</p><strong className="qr-number">{request.code.slice(0,3)} {request.code.slice(3)}</strong><p className="muted small">O QR Code expira em 2 minutos e funciona uma única vez.</p></>}{expired&&<p className="muted">Gere um novo código para tentar novamente.</p>}{error&&<p className="date-error" role="alert">{error}</p>}<p className="small muted">Sessão de até 30 minutos, encerrada após 10 minutos sem interação. Os rascunhos ficam somente na memória deste computador: aguarde “Salvo no Notion” antes de sair.</p><div className="qr-actions">{(expired||error)&&<button className="primary" disabled={busy} onClick={start}>Gerar novo QR Code</button>}<button className="ghost" onClick={onClose}>Voltar</button></div></div>;
}
