"use client";
import {useState,useEffect} from 'react';
import useShoppingDrag from './useShoppingDrag';
import {shoppingId,validateShopping,moveShoppingItem,normalizeShoppingOrder} from '../lib/shopping';
export default function ShoppingView({lists,setLists,selected,onSelect,context,configured,creating,onCreate,onCreated}){
 const list=lists.find(item=>item.id===selected&&(context==='all'||item.context===context));
 const [query,setQuery]=useState(''),[cardOrder,setCardOrder]=useState([]),[orderReady,setOrderReady]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('lifeos-shopping-order'));setCardOrder(Array.isArray(saved)?saved:[]);}catch{}setOrderReady(true);},[]);
 useEffect(()=>{if(orderReady)try{localStorage.setItem('lifeos-shopping-order',JSON.stringify(cardOrder));}catch{}},[cardOrder,orderReady]);
 const normalize=text=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
 const order=normalizeShoppingOrder(cardOrder,lists.map(p=>p.id));
 const visible=order.map(id=>lists.find(p=>p.id===id)).filter(p=>(context==='all'||p.context===context)&&normalize(p.name).includes(normalize(query.trim())));
 function reorder(from,to){if(!list)return;setLists(previous=>previous.map(p=>p.id===list.id?{...p,items:moveShoppingItem(p.items,from,to)}:p));}
 const itemDrag=useShoppingDrag('data-shopping-item',reorder);
 const cardDrag=useShoppingDrag('data-shopping-card',(from,to)=>setCardOrder(previous=>moveShoppingItem(normalizeShoppingOrder(previous,lists.map(p=>p.id)).map(id=>({id})),from,to).map(p=>p.id)));
 const [name,setName]=useState(''),[listContext,setListContext]=useState('personal'),[text,setText]=useState(''),[error,setError]=useState(''),[editing,setEditing]=useState(null),[editText,setEditText]=useState(''),[renaming,setRenaming]=useState(false),[rename,setRename]=useState(''),[renameContext,setRenameContext]=useState('personal');
 function update(next){const err=validateShopping(next);if(err){setError(err);return false;}setLists(prev=>prev.map(item=>item.id===next.id?next:item));setError('');return true;}
 function create(e){e.preventDefault();const value={id:shoppingId(),name:name.trim(),context:context==='all'?listContext:context,items:[]};const err=validateShopping(value);if(err){setError(err);return;}if(lists.some(p=>p.context===value.context&&p.name.trim().toLocaleLowerCase('pt-BR')===value.name.toLocaleLowerCase('pt-BR'))){setError('Já existe uma lista com esse nome neste contexto. Selecione-a para adicionar itens.');return;}setLists(prev=>[...prev,value]);onSelect(value.id);setName('');setError('');onCreated();}
 function add(e){e.preventDefault();if(!text.trim())return;if(update({...list,items:[{id:shoppingId(),text:text.trim()},...list.items]}))setText('');}
 function removeList(){if(window.confirm(`Finalizar e excluir “${list.name}” e todos os seus itens? Não haverá histórico no LifeOS.`)){setLists(prev=>prev.filter(item=>item.id!==list.id));onSelect(null);}}
 function saveRename(e){e.preventDefault();const name=rename.trim();if(lists.some(p=>p.id!==list.id&&p.context===renameContext&&p.name.trim().toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR'))){setError('Já existe outra lista com esse nome neste contexto.');return;}if(update({...list,name,context:renameContext}))setRenaming(false);}
 if(!configured)return <section className="diary-setup"><h2>Configure Compras no Notion</h2><p>Crie o banco Listas de compras com Nome (título), Contexto (seleção: Pessoal e Trabalho) e Itens (texto).</p><p>Adicione <code>NOTION_SHOPPING_DATABASE_ID</code> na Vercel e faça um novo deploy. As instruções completas estão no README.</p></section>;
 return <section className="shopping-view"><div className="finance-heading"><div><h1>Listas de compras</h1><p className="muted">Crie, compre e finalize. Sem histórico.</p></div><button className="primary" onClick={()=>{setError('');onCreate();}}>+ Nova lista</button></div>
 {list?<><button className="ghost shopping-back" onClick={()=>{onSelect(null);setEditing(null);setRenaming(false);setError('');}}>← Voltar às listas</button><section className="birthday-card" key={list.id}><div className="finance-heading"><div><h2>{list.name}</h2><span className="muted small">{list.context==='work'?'Trabalho':'Pessoal'} · {list.items.length} itens restantes</span></div><button className="ghost" onClick={()=>{setRename(list.name);setRenameContext(list.context);setRenaming(true);setError('');}}>Editar lista</button></div><p className="muted small">Marcou como comprado? O item sai da lista. Arraste pela alça para mudar a ordem.</p><form className="shopping-add" onSubmit={add}><input className="search" aria-label="Novo item da lista" placeholder="Adicionar item…" maxLength={500} value={text} onChange={e=>setText(e.target.value)}/><button className="primary">+ Adicionar</button></form><ul className="shopping-items">{list.items.map(item=><li key={item.id} data-shopping-item={item.id} className={(itemDrag.dragging===item.id?'shopping-dragging ':'')+(itemDrag.over===item.id?'shopping-drop':'')}>
 <button type="button" className="ghost shopping-drag-handle" {...itemDrag.bind(item.id)} aria-label={`Reordenar ${item.text}`} title="Arraste para reordenar · Alt + seta também move"
 onKeyDown={e=>{if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const index=list.items.findIndex(p=>p.id===item.id),target=list.items[index+(e.key==='ArrowUp'?-1:1)];if(target)reorder(item.id,target.id);}}}>⋮⋮</button><input type="checkbox" aria-label={`Marcar ${item.text} como comprado e remover`} checked={false} onChange={()=>update({...list,items:list.items.filter(p=>p.id!==item.id)})}/>{editing===item.id?<form className="shopping-add grow" onSubmit={e=>{e.preventDefault();if(update({...list,items:list.items.map(p=>p.id===item.id?{...p,text:editText.trim()}:p)}))setEditing(null);}}><input className="search" autoFocus aria-label="Editar item" maxLength={500} value={editText} onChange={e=>setEditText(e.target.value)}/><button className="ghost">Salvar</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>Cancelar</button></form>:<><span className="grow shopping-item-text">{item.text}</span><button className="ghost" onClick={()=>{setEditing(item.id);setEditText(item.text);}}>Editar</button></>}</li>)}</ul>{!list.items.length&&<p className="muted">Nenhum item restante. Adicione itens ou finalize a lista.</p>}<button className="primary shopping-finish" onClick={removeList}>Finalizar e excluir lista</button><p className="muted small">A lista será apagada após confirmação.</p></section></>:<><input className="search shopping-search" aria-label="Buscar lista de compras" placeholder="Buscar lista…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="shopping-card-grid">{visible.map(p=><div className={'shopping-card-wrap'+(cardDrag.dragging===p.id?' shopping-dragging':'')+(cardDrag.over===p.id?' shopping-drop':'')} key={p.id} data-shopping-card={p.id}><button className="ghost shopping-card-handle shopping-drag-handle" {...cardDrag.bind(p.id)} aria-label={`Reordenar lista ${p.name}`} title="Arraste para reordenar as listas" onKeyDown={e=>{if(e.altKey&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const index=visible.findIndex(item=>item.id===p.id),target=visible[index+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)];if(target)setCardOrder(moveShoppingItem(order.map(id=>({id})),p.id,target.id).map(item=>item.id));}}}>⋮⋮</button><button className="shopping-card" onClick={()=>{if(cardDrag.suppress.current)return;onSelect(p.id);setEditing(null);setRenaming(false);setError('');}}><strong>{p.name}</strong><span className="chip">{p.context==='work'?'Trabalho':'Pessoal'}</span><span className="muted small">{p.items.length} {p.items.length===1?'item restante':'itens restantes'}</span><span className="shopping-card-preview muted small">{p.items.slice(0,3).map(item=>item.text).join(' · ')||'Lista vazia'}</span></button></div>)}</div>{!visible.length&&<p className="empty">Nenhuma lista encontrada. Crie uma nova lista.</p>}</>}
 {error&&<p className="date-error" role="alert">{error}</p>}
 {(creating||renaming&&list)&&<div className="overlay" onClick={()=>{onCreated();setRenaming(false);}}><div className="panel finance-modal" role="dialog" aria-modal="true" aria-label={creating?'Nova lista':'Editar lista'} onClick={e=>e.stopPropagation()}><h2>{creating?'Nova lista':'Editar lista'}</h2><form onSubmit={creating?create:saveRename}><div className="finance-form"><label>Nome<input className="search" autoFocus maxLength={200} value={creating?name:rename} onChange={e=>creating?setName(e.target.value):setRename(e.target.value)} required/></label><label>Contexto<select className="search" value={creating?(context==='all'?listContext:context):renameContext} disabled={creating&&context!=='all'} onChange={e=>creating?setListContext(e.target.value):setRenameContext(e.target.value)}><option value="personal">Pessoal</option><option value="work">Trabalho</option></select></label></div>{error&&<p className="date-error" role="alert">{error}</p>}<div className="finance-period"><button className="primary">{creating?'Criar lista':'Salvar'}</button><button type="button" className="ghost" onClick={()=>{onCreated();setRenaming(false);setError('');}}>Cancelar</button></div></form></div></div>}
 </section>;
}
