"use client";
import {useState} from 'react';
import {shoppingId,validateShopping} from '../lib/shopping';
export function ShoppingMenu({lists,context,selected,onSelect,onCreate}){
 const [query,setQuery]=useState('');const normalize=text=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
 const visible=lists.filter(list=>(context==='all'||list.context===context)&&normalize(list.name).includes(normalize(query.trim()))).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR',{sensitivity:'base'}));
 return <section className="shopping-menu" aria-label="Listas de compras"><div className="panel-head"><h2 className="grow">Listas de compras</h2><button className="ghost" onClick={onCreate}>+ Nova</button></div><input className="search" placeholder="Buscar lista…" aria-label="Buscar lista de compras" value={query} onChange={e=>setQuery(e.target.value)}/><div className="shopping-list-menu">{visible.map(list=><button key={list.id} className={'shopping-list-link'+(list.id===selected?' on':'')} onClick={()=>onSelect(list.id)}><strong>{list.name}</strong><span>{list.context==='work'?'Trabalho':'Pessoal'} · {list.items.length} {list.items.length===1?'item':'itens'}</span></button>)}</div>{!visible.length&&<p className="muted small">Nenhuma lista encontrada.</p>}</section>;
}
export default function ShoppingView({lists,setLists,selected,onSelect,context,configured,creating,onCreate,onCreated}){
 const list=lists.find(item=>item.id===selected&&(context==='all'||item.context===context));
 const [name,setName]=useState(''),[listContext,setListContext]=useState('personal'),[text,setText]=useState(''),[error,setError]=useState(''),[editing,setEditing]=useState(null),[editText,setEditText]=useState(''),[renaming,setRenaming]=useState(false),[rename,setRename]=useState(''),[renameContext,setRenameContext]=useState('personal');
 function update(next){const err=validateShopping(next);if(err){setError(err);return false;}setLists(prev=>prev.map(item=>item.id===next.id?next:item));setError('');return true;}
 function create(e){e.preventDefault();const value={id:shoppingId(),name:name.trim(),context:context==='all'?listContext:context,items:[]};const err=validateShopping(value);if(err){setError(err);return;}if(lists.some(p=>p.context===value.context&&p.name.trim().toLocaleLowerCase('pt-BR')===value.name.toLocaleLowerCase('pt-BR'))){setError('Já existe uma lista com esse nome neste contexto. Selecione-a para adicionar itens.');return;}setLists(prev=>[...prev,value]);onSelect(value.id);setName('');setError('');onCreated();}
 function add(e){e.preventDefault();if(!text.trim())return;if(update({...list,items:[...list.items,{id:shoppingId(),text:text.trim()}]}))setText('');}
 function removeList(){if(window.confirm(`Finalizar e excluir “${list.name}” e todos os seus itens? Não haverá histórico no LifeOS.`)){setLists(prev=>prev.filter(item=>item.id!==list.id));onSelect(null);}}
 function saveRename(e){e.preventDefault();const name=rename.trim();if(lists.some(p=>p.id!==list.id&&p.context===renameContext&&p.name.trim().toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR'))){setError('Já existe outra lista com esse nome neste contexto.');return;}if(update({...list,name,context:renameContext}))setRenaming(false);}
 if(!configured)return <section className="diary-setup"><h2>Configure Compras no Notion</h2><p>Crie o banco Listas de compras com Nome (título), Contexto (seleção: Pessoal e Trabalho) e Itens (texto).</p><p>Adicione <code>NOTION_SHOPPING_DATABASE_ID</code> na Vercel e faça um novo deploy. As instruções completas estão no README.</p></section>;
 return <section className="shopping-view"><div className="finance-heading"><div><h1>Listas de compras</h1><p className="muted">Crie, compre e finalize. Sem histórico.</p></div><button className="primary" onClick={()=>{setError('');onCreate();}}>+ Nova lista</button></div>
 {list?<section className="birthday-card" key={list.id}><div className="finance-heading"><div><h2>{list.name}</h2><span className="muted small">{list.context==='work'?'Trabalho':'Pessoal'} · {list.items.length} itens restantes</span></div><button className="ghost" onClick={()=>{setRename(list.name);setRenameContext(list.context);setRenaming(true);setError('');}}>Editar lista</button></div><p className="muted small">Marcou como comprado? O item sai da lista.</p><form className="shopping-add" onSubmit={add}><input className="search" aria-label="Novo item da lista" placeholder="Adicionar item…" maxLength={500} value={text} onChange={e=>setText(e.target.value)}/><button className="primary">+ Adicionar</button></form><ul className="shopping-items">{list.items.map(item=><li key={item.id}><input type="checkbox" aria-label={`Marcar ${item.text} como comprado e remover`} checked={false} onChange={()=>update({...list,items:list.items.filter(p=>p.id!==item.id)})}/>{editing===item.id?<form className="shopping-add grow" onSubmit={e=>{e.preventDefault();if(update({...list,items:list.items.map(p=>p.id===item.id?{...p,text:editText.trim()}:p)}))setEditing(null);}}><input className="search" autoFocus aria-label="Editar item" maxLength={500} value={editText} onChange={e=>setEditText(e.target.value)}/><button className="ghost">Salvar</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>Cancelar</button></form>:<><span className="grow shopping-item-text">{item.text}</span><button className="ghost" onClick={()=>{setEditing(item.id);setEditText(item.text);}}>Editar</button><button className="danger" onClick={()=>{if(window.confirm(`Excluir o item “${item.text}”?`))update({...list,items:list.items.filter(p=>p.id!==item.id)});}}>Excluir</button></>}</li>)}</ul>{!list.items.length&&<p className="muted">Nenhum item restante. Adicione itens ou finalize a lista.</p>}<button className="primary shopping-finish" onClick={removeList}>Finalizar e excluir lista</button><p className="muted small">A lista será apagada após confirmação.</p></section>:<p className="empty">Selecione uma lista no menu ou crie uma nova.</p>}
 {error&&<p className="date-error" role="alert">{error}</p>}
 {(creating||renaming&&list)&&<div className="overlay" onClick={()=>{onCreated();setRenaming(false);}}><div className="panel finance-modal" role="dialog" aria-modal="true" aria-label={creating?'Nova lista':'Editar lista'} onClick={e=>e.stopPropagation()}><h2>{creating?'Nova lista':'Editar lista'}</h2><form onSubmit={creating?create:saveRename}><div className="finance-form"><label>Nome<input className="search" autoFocus maxLength={200} value={creating?name:rename} onChange={e=>creating?setName(e.target.value):setRename(e.target.value)} required/></label><label>Contexto<select className="search" value={creating?(context==='all'?listContext:context):renameContext} disabled={creating&&context!=='all'} onChange={e=>creating?setListContext(e.target.value):setRenameContext(e.target.value)}><option value="personal">Pessoal</option><option value="work">Trabalho</option></select></label></div>{error&&<p className="date-error" role="alert">{error}</p>}<div className="finance-period"><button className="primary">{creating?'Criar lista':'Salvar'}</button><button type="button" className="ghost" onClick={()=>{onCreated();setRenaming(false);setError('');}}>Cancelar</button></div></form></div></div>}
 </section>;
}
