"use client";
import {useState} from 'react';
import HabitsView from './HabitsView';
import HabitIcon from './WellnessIcon';
import DateInput from './DateInput';
import ModalLayer from './ModalLayer';
import {habitToday} from '../lib/habits';
import {formatDateInput} from '../lib/dateInput';
import {ASPECTS,validateWellness,recordUid,upsertWellness,latestMeasurements} from '../lib/wellness';
const decimal=value=>value===''?null:Number(String(value).replace(',','.'));
const display=value=>value==null?'—':Number(value).toLocaleString('pt-BR',{maximumFractionDigits:2});
function Sparkline({records,field,color}){const points=records.slice(0,12).reverse().filter(p=>Number.isFinite(p.data[field]));if(!points.length)return <p className="muted small">O gráfico aparece após a primeira medição.</p>;const values=points.map(p=>p.data[field]),min=Math.min(...values),span=Math.max(1,Math.max(...values)-min);return <div className="well-trend"><svg viewBox="0 0 300 85" role="img" aria-label="Evolução das medições, da mais antiga à mais recente"><polyline fill="none" stroke={color} strokeWidth="2" points={points.map((p,i)=>`${15+i*270/Math.max(1,points.length-1)},${65-(p.data[field]-min)/span*50}`).join(' ')}/>{points.map((p,i)=><circle key={p.id} cx={15+i*270/Math.max(1,points.length-1)} cy={65-(p.data[field]-min)/span*50} r="3" fill={color}><title>{`${formatDateInput(p.date)}: ${display(p.data[field])}`}</title></circle>)}</svg><span>{formatDateInput(points[0].date)} → {formatDateInput(points.at(-1).date)} · registros em sequência</span></div>;}
export default function WellnessView({remote}){
 const {wellness=[],cycle=[],setWellness,user}=remote;
 const [date,setDate]=useState(habitToday),[active,setActive]=useState('sono'),[editing,setEditing]=useState(null),[error,setError]=useState(''),[history,setHistory]=useState(null),[validDate,setValidDate]=useState(true);
 const daily=wellness.find(p=>p.type==='day'&&p.date===date),cycleDay=cycle.find(p=>p.date===date),completed=ASPECTS.filter(([key])=>daily?.data?.[key]).length;
 const pressure=latestMeasurements(wellness,'pressure'),body=latestMeasurements(wellness,'body');
 function open(type,item){setError('');setValidDate(true);const now=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}).format(new Date());const defaults=type==='cycle'?{subject:'leticiacost3@gmail.com',menstruation:'Não',flow:'—',cramps:'Nenhuma'}:type==='pressure'?{time:now}:{};setEditing(item||{id:type==='day'?`well-day-${user.id}-${date}`:type==='cycle'?`well-cycle-leticia-${date}`:recordUid(),name:type==='cycle'?'Ciclo da Letícia':type==='day'?'Meu dia':type==='pressure'?'Pressão e BPM':'Peso e gordura',type,date,data:defaults});}
 function patch(key,value){setEditing(p=>({...p,data:{...p.data,[key]:value}}));}
 function save(event){event.preventDefault();const kind=editing.type==='cycle'?'cycle':'wellness',message=validateWellness(editing,kind);if(message||!validDate){setError(message||'Confira a data.');return;}const item={...editing,data:{...editing.data,createdAt:editing.data.createdAt||new Date().toISOString()}};setWellness(previous=>({...previous,[kind]:upsertWellness(previous[kind],item)}));setEditing(null);}
 function remove(item){if(!window.confirm(`Excluir o registro de ${formatDateInput(item.date)}? Não há histórico de excluídos.`))return;const kind=item.type==='cycle'?'cycle':'wellness';setWellness(p=>({...p,[kind]:p[kind].filter(r=>r.id!==item.id)}));setEditing(null);}
 function shiftDay(delta){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+delta);const next=d.toISOString().slice(0,10);if(next<=habitToday())setDate(next);}
 function jump(id){document.getElementById('well-'+id)?.scrollIntoView({behavior:'smooth',block:'start'});}
 const field=(label,key,min,max,step='1',required=false)=><label className="habit-field">{label}<input className="search" type="number" inputMode="decimal" min={min} max={max} step={step} required={required} value={editing.data[key]??''} onChange={e=>patch(key,decimal(e.target.value))}/></label>;
 return <section className="wellness-view"><div className="finance-heading"><div><h1>Bem-estar</h1><p className="muted">Seu dia, seus hábitos e sua evolução.</p></div><div className="finance-period"><button className="ghost" aria-label="Dia anterior" onClick={()=>shiftDay(-1)}>‹</button><DateInput className="search" aria-label="Dia do bem-estar" value={date} max={habitToday()} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/><button className="ghost" aria-label="Próximo dia" disabled={date>=habitToday()} onClick={()=>shiftDay(1)}>›</button><button className="ghost" onClick={()=>setDate(habitToday())}>Hoje</button></div></div>
 <nav className="well-shortcuts" aria-label="Seções de bem-estar">{[['day','Meu dia'],['habits','Hábitos'],['pressure','Pressão e BPM'],['body','Peso e gordura']].map(([id,label])=><button className="ghost" key={id} onClick={()=>jump(id)}>{label}</button>)}</nav>
 {!remote.wellnessConfigured&&<p className="well-setup">Para salvar os novos registros, configure <code>NOTION_WELLNESS_DATABASE_ID</code> conforme o README. Seus hábitos continuam no mesmo banco.</p>}
 <div className="well-top"><section className="well-card" id="well-day"><h2>Como você está hoje?</h2><div className="well-daily"><div className="well-wheel"><div className="well-center"><strong>Como você<br/>está?</strong><small>{completed} de 6 registros</small></div>{ASPECTS.map(([key,label,icon,color],i)=><button key={key} style={{'--aspect':color,'--angle':`${i*60}deg`}} className={'well-petal'+(active===key?' selected':'')+(daily?.data?.[key]?' recorded':'')} onClick={()=>setActive(key)} aria-pressed={active===key}><HabitIcon id={['humor','mente','intestino'].includes(key)?key:icon} size={32}/><strong>{label}</strong>{daily?.data?.[key]&&<span className="well-tick">✓</span>}</button>)}</div><div className="well-aspect" style={{'--aspect':ASPECTS.find(p=>p[0]===active)[3]}}><HabitIcon id={ASPECTS.find(p=>p[0]===active)[2]} size={36}/><h3>{ASPECTS.find(p=>p[0]===active)[1]}</h3><strong>{daily?.data?.[active]||'Ainda não registrado'}</strong>{active==='sono'&&daily?.data?.hours!=null&&<p>{display(daily.data.hours)} horas</p>}<button className="primary" disabled={!remote.wellnessConfigured} onClick={()=>open('day',daily)}>Preencher / editar</button></div></div><div className="well-extras"><span>Água · Energia · Estresse</span><button className="ghost" disabled={!remote.wellnessConfigured} onClick={()=>open('day',daily)}>Mais registros e observações</button></div></section>
 <section className="well-card well-cycle"><h2><HabitIcon id="plant"/> Ciclo da Letícia</h2><p className="small">Dados da Letícia · edição pelos dois usuários nesta fase de testes.</p><div className="cycle-ring"><HabitIcon id="plant" size={42}/><strong>{formatDateInput(date)}</strong></div><dl>{[['Menstruação','menstruation'],['Fluxo','flow'],['Cólicas','cramps']].map(([label,key])=><div key={key}><dt>{label}</dt><dd>{cycleDay?.data?.[key]||'—'}</dd></div>)}</dl>{!remote.cycleConfigured&&<p className="small">Configure o banco Ciclo da Letícia conforme o README.</p>}<button className="ghost" disabled={!remote.cycleConfigured} onClick={()=>open('cycle',cycleDay)}>Registrar / editar ciclo</button></section></div>
 <div className="well-card well-habits" id="well-habits"><HabitsView habits={remote.habits||[]} logs={remote.habitLogs||[]} setHabits={remote.setHabits} context="personal" configured={remote.habitsConfigured}/></div>
 <div className="well-measurements">{[['pressure','Pressão e BPM','pressure',pressure],['body','Peso e gordura','body',body]].map(([type,label,icon,records])=><section className="well-card" id={'well-'+type} key={type}><div className="finance-heading"><h2><HabitIcon id={icon}/>{label}</h2><button className="ghost" disabled={!remote.wellnessConfigured} onClick={()=>open(type)}>+ {type==='pressure'?'Registrar medição':'Atualizar medidas'}</button></div>{records[0]?<><div className="well-values">{type==='pressure'?<><strong>{display(records[0].data.systolic)} / {display(records[0].data.diastolic)}<small> mmHg</small></strong><strong>{display(records[0].data.bpm)}<small> bpm</small></strong></>:<><strong>{display(records[0].data.weight)}<small> kg</small></strong><strong>{display(records[0].data.fat)}<small>% gordura</small></strong></>}</div><p className="muted small">Último registro: {formatDateInput(records[0].date)} {records[0].data.time||''}</p>{type==='pressure'?<><div className="well-graph-label">Pressão sistólica · mmHg</div><Sparkline records={records} field="systolic" color="#81bdff"/><div className="well-graph-label">Pressão diastólica · mmHg</div><Sparkline records={records} field="diastolic" color="#b9a0f5"/><div className="well-graph-label">Frequência cardíaca · bpm</div><Sparkline records={records} field="bpm" color="#f69cbc"/></>:<><Sparkline records={records} field="weight" color="#81bdff"/><div className="well-graph-label">Gordura · %</div><Sparkline records={records} field="fat" color="#b9a0f5"/></>}</>:<p className="muted">Nenhuma medição registrada.</p>}{type==='body'&&<p className="small muted">Atualize quando houver uma nova medição. Não precisa preencher diariamente.</p>}<button className="ghost" onClick={()=>setHistory(type)}>Ver histórico</button></section>)}</div>
 <ModalLayer open={!!editing} onClose={()=>setEditing(null)}>{editing&&<div className="overlay" onClick={()=>setEditing(null)}><div className="panel finance-modal well-form" role="dialog" aria-modal="true" aria-label={editing.name} onClick={e=>e.stopPropagation()}><h2>{editing.name}</h2><form onSubmit={save}><label className="habit-field">Data<DateInput className="search" value={editing.date} max={habitToday()} disabled={['day','cycle'].includes(editing.type)} onValidityChange={setValidDate} onChange={e=>{if(!['day','cycle'].includes(editing.type))setEditing(p=>({...p,date:e.target.value}));}}/></label>{editing.type==='day'?<><div className="well-form-grid">{ASPECTS.map(([key,label,,,options])=><label className="habit-field" key={key}>{label}<select className="search" value={editing.data[key]||''} onChange={e=>patch(key,e.target.value)}><option value="">Não registrado</option>{options.map(v=><option key={v}>{v}</option>)}</select></label>)}{field('Horas de sono','hours',0,24,'.1')}{field('Exercício (minutos)','minutes',0,1440)}{field('Água (litros)','water',0,20,'.1')}{field('Energia (0 a 10)','energy',0,10)}{field('Estresse (0 a 10)','stress',0,10)}</div></>:editing.type==='pressure'?<><label className="habit-field">Horário<input className="search" type="time" required value={editing.data.time||''} onChange={e=>patch('time',e.target.value)}/></label><div className="well-form-grid">{field('Sistólica (mmHg)','systolic',1,400,'1',true)}{field('Diastólica (mmHg)','diastolic',1,300,'1',true)}{field('Frequência cardíaca (BPM)','bpm',1,300,'1',true)}</div></>:editing.type==='body'?<div className="well-form-grid">{field('Peso (kg)','weight',1,600,'.01',true)}{field('Gordura (%) · opcional','fat',0,100,'.1')}</div>:<>{[['Menstruação','menstruation',['Não','Sim']],['Fluxo','flow',['—','Leve','Moderado','Intenso']],['Cólicas','cramps',['Nenhuma','Leve','Moderada','Forte']]].map(([label,key,options])=><label className="habit-field" key={key}>{label}<select className="search" value={editing.data[key]} onChange={e=>patch(key,e.target.value)}>{options.map(v=><option key={v}>{v}</option>)}</select></label>)}<p className="muted small">Este registro é sempre do ciclo da Letícia.</p></>}<label className="habit-field">Observações<textarea className="search" rows="3" maxLength={5000} value={editing.data.notes||''} onChange={e=>patch('notes',e.target.value)}/></label>{error&&<p className="date-error" role="alert">{error}</p>}<div className="finance-period"><button className="primary" disabled={!validDate}>Salvar</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>Cancelar</button>{(editing._notionId||wellness.some(p=>p.id===editing.id)||cycle.some(p=>p.id===editing.id))&&<button type="button" className="danger" onClick={()=>remove(editing)}>Excluir registro</button>}</div></form></div></div>}</ModalLayer>
 <ModalLayer open={!!history} onClose={()=>setHistory(null)}>{history&&<div className="overlay" onClick={()=>setHistory(null)}><div className="panel finance-modal" role="dialog" aria-modal="true" aria-label="Histórico de medições" onClick={e=>e.stopPropagation()}><div className="finance-heading"><h2>Histórico de {history==='pressure'?'pressão e BPM':'peso e gordura'}</h2><button className="ghost" onClick={()=>setHistory(null)}>Fechar</button></div>{latestMeasurements(wellness,history).map(item=><div className="well-history-row" key={item.id}><div><strong>{formatDateInput(item.date)} {item.data.time||''}</strong><p>{history==='pressure'?`${display(item.data.systolic)} / ${display(item.data.diastolic)} mmHg · ${display(item.data.bpm)} bpm`:`${display(item.data.weight)} kg · ${display(item.data.fat)}% gordura`}</p><p className="muted small">{item.data.notes}</p></div><button className="ghost" onClick={()=>{setHistory(null);open(history,item);}}>Editar</button></div>)}</div></div>}</ModalLayer></section>;
}
