"use client";
import {useState} from 'react';
import HabitsView from './HabitsView';
import InlineMeasurement from './InlineMeasurement';
import MeasurementChart from './MeasurementChart';
import HabitIcon from './WellnessIcon';
import DateInput from './DateInput';
import ModalLayer from './ModalLayer';
import {habitToday} from '../lib/habits';
import {formatDateInput} from '../lib/dateInput';
import {CYCLE_CHOICES,updateCycleChoice,ASPECTS,aspectFilled,ASPECT_LABELS,validateWellness,recordUid,upsertWellness,latestMeasurements,dailyPressure,maskPressure,parsePressure} from '../lib/wellness';
const decimal=value=>value===''?null:Number(String(value).replace(',','.'));
const pressureDisplay=value=>value==null?'—':Math.round(value).toLocaleString('pt-BR');
const display=value=>value==null?'—':Number(value).toLocaleString('pt-BR',{maximumFractionDigits:2});
export default function WellnessView({remote}){
 const {wellness=[],cycle=[],setWellness,user}=remote;
 const [date,setDate]=useState(habitToday),[active,setActive]=useState('sono'),[editing,setEditing]=useState(null),[error,setError]=useState(''),[history,setHistory]=useState(null),[validDate,setValidDate]=useState(true),[pressureText,setPressureText]=useState('');
 const daily=wellness.find(p=>p.type==='day'&&p.date===date),cycleDay=cycle.find(p=>p.date===date),completed=ASPECTS.filter(([key])=>aspectFilled(daily?.data,key)).length;
 const pressure=dailyPressure(wellness),body=latestMeasurements(wellness,'body');
 function open(type,item){setError('');setValidDate(true);setPressureText(type==='pressure'&&item?`${item.data.systolic}/${item.data.diastolic}`:'');const defaults=type==='cycle'?{subject:'leticiacost3@gmail.com',menstruation:'',flow:'',cramps:''}:{};setEditing(item||{id:type==='day'?`well-day-${user.id}-${date}`:type==='cycle'?`well-cycle-leticia-${date}`:recordUid(),name:type==='cycle'?'Ciclo da Letícia':type==='day'?'Meu dia':type==='pressure'?'Pressão e BPM':'Peso e gordura',type,date,data:defaults});}
 function chooseAspect(value,key=active){setWellness(previous=>{const existing=previous.wellness.find(p=>p.type==='day'&&p.date===date);const item=existing||{id:`well-day-${user.id}-${date}`,name:'Meu dia',type:'day',date,data:{}};return {...previous,wellness:upsertWellness(previous.wellness,{...item,data:{...item.data,[key]:value,...(key==='painIntensity'&&value==='Nenhuma'?{dores:''}:{})}})};});}
 function patch(key,value){setEditing(p=>({...p,data:{...p.data,[key]:value}}));}
 function save(event){event.preventDefault();let candidate=editing;if(editing.type==='pressure'){const parsed=parsePressure(pressureText);if(!parsed){setError('Informe a pressão no formato 124/76.');return;}candidate={...editing,data:{...editing.data,...parsed}};}const kind=candidate.type==='cycle'?'cycle':'wellness',message=validateWellness(candidate,kind);if(message||!validDate){setError(message||'Confira a data.');return;}const item={...candidate,data:{...candidate.data,createdAt:candidate.data.createdAt||new Date().toISOString()}};setWellness(previous=>({...previous,[kind]:upsertWellness(previous[kind],item)}));setEditing(null);}
 function remove(item){if(!window.confirm(`Excluir o registro de ${formatDateInput(item.date)}? Não há histórico de excluídos.`))return;const kind=item.type==='cycle'?'cycle':'wellness';setWellness(p=>({...p,[kind]:p[kind].filter(r=>r.id!==item.id)}));setEditing(null);}
 function shiftDay(delta){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+delta);const next=d.toISOString().slice(0,10);if(next<=habitToday())setDate(next);}
 function jump(id){document.getElementById('well-'+id)?.scrollIntoView({behavior:'smooth',block:'start'});}
 const field=(label,key,min,max,step='1',required=false)=><label className="habit-field">{label}<input className="search" type="number" inputMode="decimal" min={min} max={max} step={step} required={required} value={editing.data[key]??''} onChange={e=>patch(key,decimal(e.target.value))}/></label>;
 return <section className="wellness-view"><div className="finance-heading"><div><h1>Bem-estar</h1><p className="muted">Seu dia, seus hábitos e sua evolução.</p></div><div className="finance-period"><button className="ghost" aria-label="Dia anterior" onClick={()=>shiftDay(-1)}>‹</button><DateInput className="search" aria-label="Dia do bem-estar" value={date} max={habitToday()} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/><button className="ghost" aria-label="Próximo dia" disabled={date>=habitToday()} onClick={()=>shiftDay(1)}>›</button><button className="ghost" onClick={()=>setDate(habitToday())}>Hoje</button></div></div>
 <nav className="well-shortcuts" aria-label="Seções de bem-estar">{[['day','Meu dia'],['habits','Hábitos'],['pressure','Pressão e BPM'],['body','Peso e gordura']].map(([id,label])=><button className="ghost" key={id} onClick={()=>jump(id)}>{label}</button>)}</nav>
 {!remote.wellnessConfigured&&<p className="well-setup">Para salvar os novos registros, configure <code>NOTION_WELLNESS_DATABASE_ID</code> conforme o README. Seus hábitos continuam no mesmo banco.</p>}
 <div className="well-top"><section className="well-card" id="well-day"><h2><HabitIcon id="plant"/> Como você está hoje?</h2><div className="well-daily"><div className="well-wheel"><div className="well-center"><strong>Como você<br/>está hoje?</strong><small>{completed} de 6 registros</small></div>{ASPECTS.map(([key,label,icon,color],i)=><button key={key} style={{'--aspect':color,'--angle':`${i*60}deg`}} className={'well-petal'+(active===key?' selected':'')+(aspectFilled(daily?.data,key)?' recorded':'')} onClick={()=>setActive(key)} aria-pressed={active===key}><svg className="well-petal-shape" viewBox="0 0 120 120" aria-hidden="true"><path d="M10 21Q60 -10 110 21Q123 33 114 50L90 97Q60 79 30 97L6 50Q-3 33 10 21Z"/></svg><span className="well-petal-content"><HabitIcon id={['humor','mente','intestino'].includes(key)?key:icon} size={32}/><strong>{label}</strong>{aspectFilled(daily?.data,key)&&<span className="well-tick">✓</span>}</span></button>)}</div><div className="well-aspect" style={{'--aspect':ASPECTS.find(p=>p[0]===active)[3]}}><div className="well-aspect-title"><HabitIcon id={['humor','mente','intestino'].includes(active)?active:ASPECTS.find(p=>p[0]===active)[2]} size={28}/><h3>{active==='sono'?'Seu sono':ASPECTS.find(p=>p[0]===active)[1]}</h3></div><strong>{ASPECT_LABELS[active]?.[daily?.data?.[active]]||daily?.data?.[active]||(active==='dores'?daily?.data?.painIntensity:active==='sono'&&daily?.data?.sleepDuration?'Duração registrada':'')||'Ainda não registrado'}</strong>{active==='sono'&&<><span className="well-choice-caption">Horas aproximadas de sono</span><div className="well-sleep-hours" role="group" aria-label="Horas aproximadas de sono">{[['6-','6h ou menos'],['7','7h'],['8','8h'],['9+','9h ou mais']].map(([value,label])=><button key={value} className={'well-choice'+(daily?.data?.sleepDuration===value?' chosen':'')} disabled={!remote.wellnessConfigured} aria-pressed={daily?.data?.sleepDuration===value} title={label} onClick={()=>chooseAspect(value,'sleepDuration')}><strong>{value==='6-'?'6h−':value==='9+'?'9h+':value+'h'}</strong><small>{value==='6-'?'ou menos':value==='9+'?'ou mais':'aprox.'}</small></button>)}</div>{!daily?.data?.sleepDuration&&daily?.data?.hours!=null&&<small>Registro anterior: {display(daily.data.hours)} horas</small>}<span className="well-choice-caption">Qualidade do sono</span></>}
 {active==='dores'?<><span className="well-choice-caption">Intensidade da dor</span><div className="well-choices" role="group" aria-label="Intensidade da dor">{['Nenhuma','Leve','Moderada','Forte'].map(value=><button key={value} className={'well-choice'+(daily?.data?.painIntensity===value?' chosen':'')} disabled={!remote.wellnessConfigured} aria-pressed={daily?.data?.painIntensity===value} onClick={()=>chooseAspect(value,'painIntensity')}>{value}</button>)}</div>{daily?.data?.painIntensity!=='Nenhuma'&&<><span className="well-choice-caption">Onde sente? (opcional)</span><div className="well-choices">{ASPECTS.find(p=>p[0]===active)[4].filter(v=>v!=='Nenhuma').map(value=><button key={value} className={'well-choice'+(daily?.data?.dores===value?' chosen':'')} disabled={!remote.wellnessConfigured} aria-pressed={daily?.data?.dores===value} onClick={()=>chooseAspect(value)}>{value}</button>)}</div></>}</>:<div className="well-choices" role="group" aria-label={`Escolhas de ${ASPECTS.find(p=>p[0]===active)[1]}`}>{ASPECTS.find(p=>p[0]===active)[4].map(value=><button className={'well-choice'+(daily?.data?.[active]===value?' chosen':'')} key={value} disabled={!remote.wellnessConfigured} aria-pressed={daily?.data?.[active]===value} onClick={()=>chooseAspect(value)}>{ASPECT_LABELS[active]?.[value]||value}{daily?.data?.[active]===value?' ✓':''}</button>)}</div>}
 {aspectFilled(daily?.data,active)&&<button className="ghost well-clear" disabled={!remote.wellnessConfigured} onClick={()=>{setWellness(previous=>({...previous,wellness:previous.wellness.map(item=>item.type==='day'&&item.date===date?{...item,data:{...item.data,[active]:'',...(active==='sono'?{sleepDuration:'',hours:null}:{}),...(active==='dores'?{painIntensity:''}:{})}}:item)}));}}>Limpar escolha</button>}<small>Escolha uma opção. O salvamento é automático.</small></div></div><div className="well-extras"><span>Água · Energia · Estresse</span><button className="ghost" disabled={!remote.wellnessConfigured} onClick={()=>open('day',daily)}>Mais registros e observações</button></div></section>
 <section className="well-card well-cycle"><h2><HabitIcon id="plant"/> Ciclo da Letícia</h2><p className="small">Dados da Letícia · edição pelos dois usuários nesta fase de testes.</p><div className="well-cycle-inner"><h3><HabitIcon id="plant" size={24}/> Seu ciclo</h3><div className="cycle-ring"><HabitIcon id="plant" size={42}/><strong>{formatDateInput(date)}</strong></div><div className="cycle-inline-choices">{CYCLE_CHOICES.map(([label,key,options])=><div className="cycle-choice-field" key={key}><span>{label}</span><div role="group" aria-label={label+' do ciclo'}>{options.map(value=><button key={value} className={'cycle-choice'+(cycleDay?.data?.[key]===value?' chosen':'')} aria-pressed={cycleDay?.data?.[key]===value} disabled={!remote.cycleConfigured} onClick={()=>setWellness(previous=>({...previous,cycle:updateCycleChoice(previous.cycle,date,key,value)}))}>{value==='—'?'Sem fluxo':value}</button>)}</div></div>)}</div><p className="small cycle-save-note">Escolha as opções. O salvamento é automático.</p>{!remote.cycleConfigured&&<p className="small">Configure o banco Ciclo da Letícia conforme o README.</p>}<button className="ghost" disabled={!remote.cycleConfigured} onClick={()=>open('cycle',cycleDay)}>Editar detalhes</button></div></section></div>
 <div className="well-card well-habits" id="well-habits"><HabitsView habits={remote.habits||[]} logs={remote.habitLogs||[]} setHabits={remote.setHabits} context="personal" configured={remote.habitsConfigured}/></div>
 <div className="well-measurements">{[['pressure','Pressão e BPM','pressure',pressure],['body','Peso e gordura','body',body]].map(([type,label,icon,records])=><section className="well-card" id={'well-'+type} key={type}><div className="finance-heading"><h2><HabitIcon id={icon}/>{label}</h2></div><InlineMeasurement type={type} date={date} configured={remote.wellnessConfigured} setWellness={setWellness}/>{records[0]?<><div className="well-values">{type==='pressure'?<><strong>{display(records[0].data.systolic)} / {display(records[0].data.diastolic)}<small> mmHg</small></strong><strong>{display(records[0].data.bpm)}<small> bpm</small></strong></>:<><strong>{display(records[0].data.weight)}<small> kg</small></strong><strong>{display(records[0].data.fat)}<small>% gordura</small></strong></>}</div><p className="muted small">{type==='pressure'?`Média de ${records[0].count} ${records[0].count===1?'medição':'medições'} · `:'Último registro: '}{formatDateInput(records[0].date)}</p><MeasurementChart records={records} type={type}/></>:<p className="muted">Nenhuma medição registrada.</p>}{type==='body'&&<p className="small muted">Atualize quando houver uma nova medição. Não precisa preencher diariamente.</p>}<button className="ghost" onClick={()=>setHistory(type)}>Ver histórico</button></section>)}</div>
 <ModalLayer open={!!editing} onClose={()=>setEditing(null)}>{editing&&<div className="overlay" onClick={()=>setEditing(null)}><div className="panel finance-modal well-form" role="dialog" aria-modal="true" aria-label={editing.name} onClick={e=>e.stopPropagation()}><h2>{editing.type==='day'?'Mais registros do dia':editing.name}</h2><form onSubmit={save}><label className="habit-field">Data<DateInput className="search" value={editing.date} max={habitToday()} disabled={['day','cycle'].includes(editing.type)} onValidityChange={setValidDate} onChange={e=>{if(!['day','cycle'].includes(editing.type))setEditing(p=>({...p,date:e.target.value}));}}/></label>{editing.type==='day'?<><div className="well-form-grid">{field('Horas de sono','hours',0,24,'.1')}{field('Exercício (minutos)','minutes',0,1440)}{field('Água (litros)','water',0,20,'.1')}{field('Energia (0 a 10)','energy',0,10)}{field('Estresse (0 a 10)','stress',0,10)}</div></>:editing.type==='pressure'?<div className="well-form-grid"><label className="habit-field">Pressão (mmHg)<input className="search" aria-label="Pressão sistólica e diastólica" inputMode="numeric" placeholder="000/00" maxLength={6} required value={pressureText} onChange={e=>setPressureText(maskPressure(e.target.value))}/></label>{field('Frequência cardíaca (BPM)','bpm',1,300,'1',true)}</div>:editing.type==='body'?<div className="well-form-grid">{field('Peso (kg)','weight',1,600,'.01',true)}{field('Gordura (%) · opcional','fat',0,100,'.1')}</div>:<>{CYCLE_CHOICES.map(([label,key,options])=><label className="habit-field" key={key}>{label}<select className="search" value={editing.data[key]||''} onChange={e=>patch(key,e.target.value)}><option value="">Não registrado</option>{options.map(v=><option key={v}>{v}</option>)}</select></label>)}<p className="muted small">Este registro é sempre do ciclo da Letícia.</p></>}<label className="habit-field">Observações<textarea className="search" rows="3" maxLength={5000} value={editing.data.notes||''} onChange={e=>patch('notes',e.target.value)}/></label>{error&&<p className="date-error" role="alert">{error}</p>}<div className="finance-period"><button className="primary" disabled={!validDate}>Salvar</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>Cancelar</button>{(editing._notionId||wellness.some(p=>p.id===editing.id)||cycle.some(p=>p.id===editing.id))&&<button type="button" className="danger" onClick={()=>remove(editing)}>Excluir registro</button>}</div></form></div></div>}</ModalLayer>
 <ModalLayer open={!!history} onClose={()=>setHistory(null)}>{history&&<div className="overlay" onClick={()=>setHistory(null)}><div className="panel finance-modal" role="dialog" aria-modal="true" aria-label="Histórico de medições" onClick={e=>e.stopPropagation()}><div className="finance-heading"><h2>Histórico de {history==='pressure'?'pressão e BPM':'peso e gordura'}</h2><button className="ghost" onClick={()=>setHistory(null)}>Fechar</button></div>{latestMeasurements(wellness,history).map(item=><div className="well-history-row" key={item.id}><div><strong>{formatDateInput(item.date)} </strong><p>{history==='pressure'?`${pressureDisplay(item.data.systolic)} / ${pressureDisplay(item.data.diastolic)} mmHg · ${pressureDisplay(item.data.bpm)} bpm`:`${display(item.data.weight)} kg · ${display(item.data.fat)}% gordura`}</p><p className="muted small">{item.data.notes}</p></div><button className="ghost" onClick={()=>{setHistory(null);open(history,item);}}>Editar</button></div>)}</div></div>}</ModalLayer></section>;
}
