export const MEDIA_STATUS={planned:'Quero começar',active:'Em andamento',done:'Concluído'};
export const MEDIA_TYPES={book:'Livro',film:'Filme',game:'Jogo',series:'Série',custom:'Outro'};
export const MEDIA_ICONS=['book','film','game','series','music','headphones','podcast','comic','star','heart','camera','ticket','puzzle','globe','palette','sparkles'];
export const MEDIA_COLORS=['#6ea8fe','#f26d82','#57d98b','#a78bfa','#e6b84b','#51cbd5','#f59e70','#e8eaef'];
export const DEFAULT_SECTIONS=[{name:'Leitura',type:'book',icon:'book',color:MEDIA_COLORS[0]},{name:'Filmes',type:'film',icon:'film',color:MEDIA_COLORS[1]},{name:'Jogos',type:'game',icon:'game',color:MEDIA_COLORS[2]},{name:'Séries',type:'series',icon:'series',color:MEDIA_COLORS[3]}];
export function mediaLabels(type){return {book:{want:'Quero ler',active:'Lendo',done:'Lido',action:'Marcar como lido'},film:{want:'Quero assistir',active:'Assistindo',done:'Assistido',action:'Marcar como assistido'},game:{want:'Quero jogar',active:'Jogando',done:'Jogado',action:'Marcar como jogado'},series:{want:'Quero assistir',active:'Assistindo',done:'Assistida',action:'Marcar como assistida'}}[type]||{want:'Quero começar',active:'Em andamento',done:'Concluído',action:'Marcar como concluído'};}
export function safeMediaUrl(value){if(!value)return true;try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}
export function validMediaSection(item){return !!item.name?.trim()&&item.name.length<=100&&Object.hasOwn(MEDIA_TYPES,item.type)&&MEDIA_ICONS.includes(item.icon)&&MEDIA_COLORS.includes(item.color);}
export function validMedia(item){return !!item.name?.trim()&&item.name.length<=300&&typeof item.author==='string'&&item.author.length<=300&&typeof item.comment==='string'&&item.comment.length<=10000&&Object.hasOwn(MEDIA_STATUS,item.status)&&Number.isInteger(item.rating)&&item.rating>=0&&item.rating<=5&&safeMediaUrl(item.coverUrl)&&safeMediaUrl(item.sourceUrl)&&typeof item.provider==='string'&&item.provider.length<=100&&(!item.attachments||item.attachments.length<=1);}
export function filterMedia(items,query,status){const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const q=normalize(query.trim());return items.filter(item=>(status==='all'||item.status===status)&&normalize(item.name+' '+item.author+' '+item.comment).includes(q));}
